apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-identity-controller
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-identity-controller
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-identity-controller
    spec:
      containers:
      - name: {{ .Release.Name }}-identity-controller
        image: {{ include "unikorn.identityControllerImage" . }}
        args:
        {{- include "unikorn.core.flags" . | nindent 8 }}
        {{- include "unikorn.otlp.flags" . | nindent 8 }}
        {{- if not .Values.spiffe.enabled }}
        {{- include "unikorn.mtls.flags" . | nindent 8 }}
        {{- end }}
        {{- include "unikorn.identity.flags" . | nindent 8 }}
        {{- if .Values.spiffe.enabled }}
        {{- include "unikorn.spiffe.flags" . | nindent 8 }}
        {{- end }}
        {{- if .Values.spiffe.enabled }}
        env:
          {{- include "unikorn.spiffe.env" . | nindent 8 }}
        {{- end }}
        ports:
        - name: http
          containerPort: 6080
        - name: prometheus
          containerPort: 8080
        - name: pprof
          containerPort: 6060
        resources:
          {{- .Values.identityController.resources | toYaml | nindent 10 }}
        securityContext:
          readOnlyRootFilesystem: true
        {{- if .Values.spiffe.enabled }}
        volumeMounts:
          {{- include "unikorn.spiffe.volumeMounts" . | nindent 8 }}
        {{- end }}
      serviceAccountName: {{ .Release.Name }}-identity-controller
      securityContext:
        runAsNonRoot: true
      {{- if .Values.spiffe.enabled }}
      volumes:
        {{- include "unikorn.spiffe.volumes" . | nindent 6 }}
      {{- end }}
