// Code generated by MockGen. DO NOT EDIT.
// Source: ../image.go
//
// Generated by this command:
//
//	mockgen -source=../image.go -destination=interfaces.go -package=mock
//
// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	io "io"
	reflect "reflect"

	openapi "github.com/unikorn-cloud/identity/pkg/openapi"
	types "github.com/unikorn-cloud/region/pkg/providers/types"
	gomock "go.uber.org/mock/gomock"
)

// MockAllocationClient is a mock of AllocationClient interface.
type MockAllocationClient struct {
	ctrl     *gomock.Controller
	recorder *MockAllocationClientMockRecorder
}

// MockAllocationClientMockRecorder is the mock recorder for MockAllocationClient.
type MockAllocationClientMockRecorder struct {
	mock *MockAllocationClient
}

// NewMockAllocationClient creates a new mock instance.
func NewMockAllocationClient(ctrl *gomock.Controller) *MockAllocationClient {
	mock := &MockAllocationClient{ctrl: ctrl}
	mock.recorder = &MockAllocationClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAllocationClient) EXPECT() *MockAllocationClientMockRecorder {
	return m.recorder
}

// OrganizationScopedCreateRaw mocks base method.
func (m *MockAllocationClient) OrganizationScopedCreateRaw(ctx context.Context, organizationID, reference string, allocations openapi.ResourceAllocationList) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrganizationScopedCreateRaw", ctx, organizationID, reference, allocations)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrganizationScopedCreateRaw indicates an expected call of OrganizationScopedCreateRaw.
func (mr *MockAllocationClientMockRecorder) OrganizationScopedCreateRaw(ctx, organizationID, reference, allocations any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrganizationScopedCreateRaw", reflect.TypeOf((*MockAllocationClient)(nil).OrganizationScopedCreateRaw), ctx, organizationID, reference, allocations)
}

// OrganizationScopedDeleteRaw mocks base method.
func (m *MockAllocationClient) OrganizationScopedDeleteRaw(ctx context.Context, organizationID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrganizationScopedDeleteRaw", ctx, organizationID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// OrganizationScopedDeleteRaw indicates an expected call of OrganizationScopedDeleteRaw.
func (mr *MockAllocationClientMockRecorder) OrganizationScopedDeleteRaw(ctx, organizationID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrganizationScopedDeleteRaw", reflect.TypeOf((*MockAllocationClient)(nil).OrganizationScopedDeleteRaw), ctx, organizationID, id)
}

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// CreateImageForUpload mocks base method.
func (m *MockProvider) CreateImageForUpload(ctx context.Context, image *types.Image) (*types.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateImageForUpload", ctx, image)
	ret0, _ := ret[0].(*types.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateImageForUpload indicates an expected call of CreateImageForUpload.
func (mr *MockProviderMockRecorder) CreateImageForUpload(ctx, image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateImageForUpload", reflect.TypeOf((*MockProvider)(nil).CreateImageForUpload), ctx, image)
}

// DeleteImage mocks base method.
func (m *MockProvider) DeleteImage(ctx context.Context, imageID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImage", ctx, imageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteImage indicates an expected call of DeleteImage.
func (mr *MockProviderMockRecorder) DeleteImage(ctx, imageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImage", reflect.TypeOf((*MockProvider)(nil).DeleteImage), ctx, imageID)
}

// GetImage mocks base method.
func (m *MockProvider) GetImage(ctx context.Context, organizationID, imageID string) (*types.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", ctx, organizationID, imageID)
	ret0, _ := ret[0].(*types.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImage indicates an expected call of GetImage.
func (mr *MockProviderMockRecorder) GetImage(ctx, organizationID, imageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockProvider)(nil).GetImage), ctx, organizationID, imageID)
}

// ListImages mocks base method.
func (m *MockProvider) ListImages(ctx context.Context, organizationID string) (types.ImageList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListImages", ctx, organizationID)
	ret0, _ := ret[0].(types.ImageList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListImages indicates an expected call of ListImages.
func (mr *MockProviderMockRecorder) ListImages(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListImages", reflect.TypeOf((*MockProvider)(nil).ListImages), ctx, organizationID)
}

// UploadImageData mocks base method.
func (m *MockProvider) UploadImageData(ctx context.Context, imageID string, reader io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadImageData", ctx, imageID, reader)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadImageData indicates an expected call of UploadImageData.
func (mr *MockProviderMockRecorder) UploadImageData(ctx, imageID, reader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadImageData", reflect.TypeOf((*MockProvider)(nil).UploadImageData), ctx, imageID, reader)
}
