// Code generated by MockGen. DO NOT EDIT.
// Source: ../image.go
//
// Generated by this command:
//
//	mockgen -source=../image.go -destination=interfaces.go -package=mock
//
// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	types "github.com/unikorn-cloud/region/pkg/providers/types"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// CreateImage mocks base method.
func (m *MockProvider) CreateImage(ctx context.Context, image *types.Image, uri string) (*types.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateImage", ctx, image, uri)
	ret0, _ := ret[0].(*types.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateImage indicates an expected call of CreateImage.
func (mr *MockProviderMockRecorder) CreateImage(ctx, image, uri any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateImage", reflect.TypeOf((*MockProvider)(nil).CreateImage), ctx, image, uri)
}

// DeleteImage mocks base method.
func (m *MockProvider) DeleteImage(ctx context.Context, imageID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImage", ctx, imageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteImage indicates an expected call of DeleteImage.
func (mr *MockProviderMockRecorder) DeleteImage(ctx, imageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImage", reflect.TypeOf((*MockProvider)(nil).DeleteImage), ctx, imageID)
}

// GetImage mocks base method.
func (m *MockProvider) GetImage(ctx context.Context, organizationID, imageID string) (*types.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", ctx, organizationID, imageID)
	ret0, _ := ret[0].(*types.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImage indicates an expected call of GetImage.
func (mr *MockProviderMockRecorder) GetImage(ctx, organizationID, imageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockProvider)(nil).GetImage), ctx, organizationID, imageID)
}

// QueryImages mocks base method.
func (m *MockProvider) QueryImages() (types.ImageQuery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryImages")
	ret0, _ := ret[0].(types.ImageQuery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryImages indicates an expected call of QueryImages.
func (mr *MockProviderMockRecorder) QueryImages() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryImages", reflect.TypeOf((*MockProvider)(nil).QueryImages))
}
