// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/unikorn-cloud/region/pkg/providers/types (interfaces: ImageQuery)
//
// Generated by this command:
//
//	mockgen -destination=queryinterfaces.go -package=mock github.com/unikorn-cloud/region/pkg/providers/types ImageQuery
//
// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	types "github.com/unikorn-cloud/region/pkg/providers/types"
	gomock "go.uber.org/mock/gomock"
)

// MockImageQuery is a mock of ImageQuery interface.
type MockImageQuery struct {
	ctrl     *gomock.Controller
	recorder *MockImageQueryMockRecorder
}

// MockImageQueryMockRecorder is the mock recorder for MockImageQuery.
type MockImageQueryMockRecorder struct {
	mock *MockImageQuery
}

// NewMockImageQuery creates a new mock instance.
func NewMockImageQuery(ctrl *gomock.Controller) *MockImageQuery {
	mock := &MockImageQuery{ctrl: ctrl}
	mock.recorder = &MockImageQueryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageQuery) EXPECT() *MockImageQueryMockRecorder {
	return m.recorder
}

// AvailableToOrganization mocks base method.
func (m *MockImageQuery) AvailableToOrganization(arg0 ...string) types.ImageQuery {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AvailableToOrganization", varargs...)
	ret0, _ := ret[0].(types.ImageQuery)
	return ret0
}

// AvailableToOrganization indicates an expected call of AvailableToOrganization.
func (mr *MockImageQueryMockRecorder) AvailableToOrganization(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AvailableToOrganization", reflect.TypeOf((*MockImageQuery)(nil).AvailableToOrganization), arg0...)
}

// List mocks base method.
func (m *MockImageQuery) List() (types.ImageList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].(types.ImageList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockImageQueryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockImageQuery)(nil).List))
}

// OwnedByOrganization mocks base method.
func (m *MockImageQuery) OwnedByOrganization(arg0 ...string) types.ImageQuery {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "OwnedByOrganization", varargs...)
	ret0, _ := ret[0].(types.ImageQuery)
	return ret0
}

// OwnedByOrganization indicates an expected call of OwnedByOrganization.
func (mr *MockImageQueryMockRecorder) OwnedByOrganization(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OwnedByOrganization", reflect.TypeOf((*MockImageQuery)(nil).OwnedByOrganization), arg0...)
}

// StatusIn mocks base method.
func (m *MockImageQuery) StatusIn(arg0 ...types.ImageStatus) types.ImageQuery {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StatusIn", varargs...)
	ret0, _ := ret[0].(types.ImageQuery)
	return ret0
}

// StatusIn indicates an expected call of StatusIn.
func (mr *MockImageQueryMockRecorder) StatusIn(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatusIn", reflect.TypeOf((*MockImageQuery)(nil).StatusIn), arg0...)
}
