// Code generated by MockGen. DO NOT EDIT.
// Source: ../../providers/types/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=../../providers/types/interfaces.go -exclude_interfaces Provider -destination=mock/interfaces.go -package=mock
//
// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	io "io"
	reflect "reflect"

	v1alpha1 "github.com/unikorn-cloud/region/pkg/apis/unikorn/v1alpha1"
	types "github.com/unikorn-cloud/region/pkg/providers/types"
	gomock "go.uber.org/mock/gomock"
)

// MockImageProvider is a mock of ImageProvider interface.
type MockImageProvider struct {
	ctrl     *gomock.Controller
	recorder *MockImageProviderMockRecorder
}

// MockImageProviderMockRecorder is the mock recorder for MockImageProvider.
type MockImageProviderMockRecorder struct {
	mock *MockImageProvider
}

// NewMockImageProvider creates a new mock instance.
func NewMockImageProvider(ctrl *gomock.Controller) *MockImageProvider {
	mock := &MockImageProvider{ctrl: ctrl}
	mock.recorder = &MockImageProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageProvider) EXPECT() *MockImageProviderMockRecorder {
	return m.recorder
}

// CreateImageForUpload mocks base method.
func (m *MockImageProvider) CreateImageForUpload(ctx context.Context, image *types.Image) (*types.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateImageForUpload", ctx, image)
	ret0, _ := ret[0].(*types.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateImageForUpload indicates an expected call of CreateImageForUpload.
func (mr *MockImageProviderMockRecorder) CreateImageForUpload(ctx, image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateImageForUpload", reflect.TypeOf((*MockImageProvider)(nil).CreateImageForUpload), ctx, image)
}

// CreateImageFromServer mocks base method.
func (m *MockImageProvider) CreateImageFromServer(ctx context.Context, identity *v1alpha1.Identity, server *v1alpha1.Server, image *types.Image) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateImageFromServer", ctx, identity, server, image)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateImageFromServer indicates an expected call of CreateImageFromServer.
func (mr *MockImageProviderMockRecorder) CreateImageFromServer(ctx, identity, server, image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateImageFromServer", reflect.TypeOf((*MockImageProvider)(nil).CreateImageFromServer), ctx, identity, server, image)
}

// DeleteImage mocks base method.
func (m *MockImageProvider) DeleteImage(ctx context.Context, imageID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImage", ctx, imageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteImage indicates an expected call of DeleteImage.
func (mr *MockImageProviderMockRecorder) DeleteImage(ctx, imageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImage", reflect.TypeOf((*MockImageProvider)(nil).DeleteImage), ctx, imageID)
}

// PublishImage mocks base method.
func (m *MockImageProvider) PublishImage(ctx context.Context, imageID string) (*types.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishImage", ctx, imageID)
	ret0, _ := ret[0].(*types.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishImage indicates an expected call of PublishImage.
func (mr *MockImageProviderMockRecorder) PublishImage(ctx, imageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishImage", reflect.TypeOf((*MockImageProvider)(nil).PublishImage), ctx, imageID)
}

// UploadImage mocks base method.
func (m *MockImageProvider) UploadImage(ctx context.Context, imageID string, reader io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadImage", ctx, imageID, reader)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadImage indicates an expected call of UploadImage.
func (mr *MockImageProviderMockRecorder) UploadImage(ctx, imageID, reader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadImage", reflect.TypeOf((*MockImageProvider)(nil).UploadImage), ctx, imageID, reader)
}
