// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock/interfaces.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	io "io"
	reflect "reflect"

	v1alpha1 "github.com/unikorn-cloud/region/pkg/apis/unikorn/v1alpha1"
	types "github.com/unikorn-cloud/region/pkg/providers/types"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// ClearImageCache mocks base method.
func (m *MockProvider) ClearImageCache(ctx context.Context, organizationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearImageCache", ctx, organizationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearImageCache indicates an expected call of ClearImageCache.
func (mr *MockProviderMockRecorder) ClearImageCache(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearImageCache", reflect.TypeOf((*MockProvider)(nil).ClearImageCache), ctx, organizationID)
}

// CreateConsoleSession mocks base method.
func (m *MockProvider) CreateConsoleSession(ctx context.Context, identity *v1alpha1.Identity, server *v1alpha1.Server) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConsoleSession", ctx, identity, server)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateConsoleSession indicates an expected call of CreateConsoleSession.
func (mr *MockProviderMockRecorder) CreateConsoleSession(ctx, identity, server any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConsoleSession", reflect.TypeOf((*MockProvider)(nil).CreateConsoleSession), ctx, identity, server)
}

// CreateIdentity mocks base method.
func (m *MockProvider) CreateIdentity(ctx context.Context, identity *v1alpha1.Identity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIdentity", ctx, identity)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateIdentity indicates an expected call of CreateIdentity.
func (mr *MockProviderMockRecorder) CreateIdentity(ctx, identity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIdentity", reflect.TypeOf((*MockProvider)(nil).CreateIdentity), ctx, identity)
}

// CreateImageForUpload mocks base method.
func (m *MockProvider) CreateImageForUpload(ctx context.Context, image *types.Image) (*types.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateImageForUpload", ctx, image)
	ret0, _ := ret[0].(*types.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateImageForUpload indicates an expected call of CreateImageForUpload.
func (mr *MockProviderMockRecorder) CreateImageForUpload(ctx, image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateImageForUpload", reflect.TypeOf((*MockProvider)(nil).CreateImageForUpload), ctx, image)
}

// CreateImageFromServer mocks base method.
func (m *MockProvider) CreateImageFromServer(ctx context.Context, identity *v1alpha1.Identity, server *v1alpha1.Server, image *types.Image) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateImageFromServer", ctx, identity, server, image)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateImageFromServer indicates an expected call of CreateImageFromServer.
func (mr *MockProviderMockRecorder) CreateImageFromServer(ctx, identity, server, image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateImageFromServer", reflect.TypeOf((*MockProvider)(nil).CreateImageFromServer), ctx, identity, server, image)
}

// CreateNetwork mocks base method.
func (m *MockProvider) CreateNetwork(ctx context.Context, identity *v1alpha1.Identity, network *v1alpha1.Network) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNetwork", ctx, identity, network)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNetwork indicates an expected call of CreateNetwork.
func (mr *MockProviderMockRecorder) CreateNetwork(ctx, identity, network any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNetwork", reflect.TypeOf((*MockProvider)(nil).CreateNetwork), ctx, identity, network)
}

// CreateSecurityGroup mocks base method.
func (m *MockProvider) CreateSecurityGroup(ctx context.Context, identity *v1alpha1.Identity, securityGroup *v1alpha1.SecurityGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSecurityGroup", ctx, identity, securityGroup)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSecurityGroup indicates an expected call of CreateSecurityGroup.
func (mr *MockProviderMockRecorder) CreateSecurityGroup(ctx, identity, securityGroup any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecurityGroup", reflect.TypeOf((*MockProvider)(nil).CreateSecurityGroup), ctx, identity, securityGroup)
}

// CreateServer mocks base method.
func (m *MockProvider) CreateServer(ctx context.Context, identity *v1alpha1.Identity, server *v1alpha1.Server) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateServer", ctx, identity, server)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateServer indicates an expected call of CreateServer.
func (mr *MockProviderMockRecorder) CreateServer(ctx, identity, server any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateServer", reflect.TypeOf((*MockProvider)(nil).CreateServer), ctx, identity, server)
}

// DeleteIdentity mocks base method.
func (m *MockProvider) DeleteIdentity(ctx context.Context, identity *v1alpha1.Identity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIdentity", ctx, identity)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIdentity indicates an expected call of DeleteIdentity.
func (mr *MockProviderMockRecorder) DeleteIdentity(ctx, identity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIdentity", reflect.TypeOf((*MockProvider)(nil).DeleteIdentity), ctx, identity)
}

// DeleteImage mocks base method.
func (m *MockProvider) DeleteImage(ctx context.Context, imageID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImage", ctx, imageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteImage indicates an expected call of DeleteImage.
func (mr *MockProviderMockRecorder) DeleteImage(ctx, imageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImage", reflect.TypeOf((*MockProvider)(nil).DeleteImage), ctx, imageID)
}

// DeleteNetwork mocks base method.
func (m *MockProvider) DeleteNetwork(ctx context.Context, identity *v1alpha1.Identity, network *v1alpha1.Network) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNetwork", ctx, identity, network)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNetwork indicates an expected call of DeleteNetwork.
func (mr *MockProviderMockRecorder) DeleteNetwork(ctx, identity, network any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNetwork", reflect.TypeOf((*MockProvider)(nil).DeleteNetwork), ctx, identity, network)
}

// DeleteSecurityGroup mocks base method.
func (m *MockProvider) DeleteSecurityGroup(ctx context.Context, identity *v1alpha1.Identity, securityGroup *v1alpha1.SecurityGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSecurityGroup", ctx, identity, securityGroup)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSecurityGroup indicates an expected call of DeleteSecurityGroup.
func (mr *MockProviderMockRecorder) DeleteSecurityGroup(ctx, identity, securityGroup any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSecurityGroup", reflect.TypeOf((*MockProvider)(nil).DeleteSecurityGroup), ctx, identity, securityGroup)
}

// DeleteServer mocks base method.
func (m *MockProvider) DeleteServer(ctx context.Context, identity *v1alpha1.Identity, server *v1alpha1.Server) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteServer", ctx, identity, server)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteServer indicates an expected call of DeleteServer.
func (mr *MockProviderMockRecorder) DeleteServer(ctx, identity, server any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServer", reflect.TypeOf((*MockProvider)(nil).DeleteServer), ctx, identity, server)
}

// Flavors mocks base method.
func (m *MockProvider) Flavors(ctx context.Context) (types.FlavorList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flavors", ctx)
	ret0, _ := ret[0].(types.FlavorList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Flavors indicates an expected call of Flavors.
func (mr *MockProviderMockRecorder) Flavors(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flavors", reflect.TypeOf((*MockProvider)(nil).Flavors), ctx)
}

// GetConsoleOutput mocks base method.
func (m *MockProvider) GetConsoleOutput(ctx context.Context, identity *v1alpha1.Identity, server *v1alpha1.Server, length *int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConsoleOutput", ctx, identity, server, length)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConsoleOutput indicates an expected call of GetConsoleOutput.
func (mr *MockProviderMockRecorder) GetConsoleOutput(ctx, identity, server, length any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConsoleOutput", reflect.TypeOf((*MockProvider)(nil).GetConsoleOutput), ctx, identity, server, length)
}

// GetImage mocks base method.
func (m *MockProvider) GetImage(ctx context.Context, organizationID, imageID string) (*types.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", ctx, organizationID, imageID)
	ret0, _ := ret[0].(*types.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImage indicates an expected call of GetImage.
func (mr *MockProviderMockRecorder) GetImage(ctx, organizationID, imageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockProvider)(nil).GetImage), ctx, organizationID, imageID)
}

// ListExternalNetworks mocks base method.
func (m *MockProvider) ListExternalNetworks(ctx context.Context) (types.ExternalNetworks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExternalNetworks", ctx)
	ret0, _ := ret[0].(types.ExternalNetworks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExternalNetworks indicates an expected call of ListExternalNetworks.
func (mr *MockProviderMockRecorder) ListExternalNetworks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExternalNetworks", reflect.TypeOf((*MockProvider)(nil).ListExternalNetworks), ctx)
}

// ListImages mocks base method.
func (m *MockProvider) ListImages(ctx context.Context, organizationID string) (types.ImageList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListImages", ctx, organizationID)
	ret0, _ := ret[0].(types.ImageList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListImages indicates an expected call of ListImages.
func (mr *MockProviderMockRecorder) ListImages(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListImages", reflect.TypeOf((*MockProvider)(nil).ListImages), ctx, organizationID)
}

// PublishImage mocks base method.
func (m *MockProvider) PublishImage(ctx context.Context, imageID string) (*types.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishImage", ctx, imageID)
	ret0, _ := ret[0].(*types.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishImage indicates an expected call of PublishImage.
func (mr *MockProviderMockRecorder) PublishImage(ctx, imageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishImage", reflect.TypeOf((*MockProvider)(nil).PublishImage), ctx, imageID)
}

// RebootServer mocks base method.
func (m *MockProvider) RebootServer(ctx context.Context, identity *v1alpha1.Identity, server *v1alpha1.Server, hard bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RebootServer", ctx, identity, server, hard)
	ret0, _ := ret[0].(error)
	return ret0
}

// RebootServer indicates an expected call of RebootServer.
func (mr *MockProviderMockRecorder) RebootServer(ctx, identity, server, hard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebootServer", reflect.TypeOf((*MockProvider)(nil).RebootServer), ctx, identity, server, hard)
}

// Region mocks base method.
func (m *MockProvider) Region(ctx context.Context) (*v1alpha1.Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Region", ctx)
	ret0, _ := ret[0].(*v1alpha1.Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Region indicates an expected call of Region.
func (mr *MockProviderMockRecorder) Region(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Region", reflect.TypeOf((*MockProvider)(nil).Region), ctx)
}

// StartServer mocks base method.
func (m *MockProvider) StartServer(ctx context.Context, identity *v1alpha1.Identity, server *v1alpha1.Server) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartServer", ctx, identity, server)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartServer indicates an expected call of StartServer.
func (mr *MockProviderMockRecorder) StartServer(ctx, identity, server any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartServer", reflect.TypeOf((*MockProvider)(nil).StartServer), ctx, identity, server)
}

// StopServer mocks base method.
func (m *MockProvider) StopServer(ctx context.Context, identity *v1alpha1.Identity, server *v1alpha1.Server) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopServer", ctx, identity, server)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopServer indicates an expected call of StopServer.
func (mr *MockProviderMockRecorder) StopServer(ctx, identity, server any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopServer", reflect.TypeOf((*MockProvider)(nil).StopServer), ctx, identity, server)
}

// UpdateServerState mocks base method.
func (m *MockProvider) UpdateServerState(ctx context.Context, identity *v1alpha1.Identity, server *v1alpha1.Server) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServerState", ctx, identity, server)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateServerState indicates an expected call of UpdateServerState.
func (mr *MockProviderMockRecorder) UpdateServerState(ctx, identity, server any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServerState", reflect.TypeOf((*MockProvider)(nil).UpdateServerState), ctx, identity, server)
}

// UploadImage mocks base method.
func (m *MockProvider) UploadImage(ctx context.Context, imageID string, reader io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadImage", ctx, imageID, reader)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadImage indicates an expected call of UploadImage.
func (mr *MockProviderMockRecorder) UploadImage(ctx, imageID, reader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadImage", reflect.TypeOf((*MockProvider)(nil).UploadImage), ctx, imageID, reader)
}
