package: generated
compatibility:
  always-prefix-enum-values: true
import-mapping:
  https://raw.githubusercontent.com/unikorn-cloud/core/v1.17.0/pkg/openapi/common.spec.yaml: github.com/unikorn-cloud/core/pkg/openapi
