// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	externalRef0 "github.com/unikorn-cloud/core/pkg/openapi"
	externalRef1 "github.com/unikorn-cloud/identity/pkg/openapi"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y9C3cbN7Ig/FdwuPeeJDskRVKULOk7c2ZlyQ9tYllj2c5MTK8P2F0kEXUDHQBNmfHV",
	"d/ZH7C/cX7IHr36Q3c0mRfmVztybUCSehapCVaEen1oeCyNGgUrROvnUijDHIUjg+q8JCUBIxvEULs6v",
	"3E/qFx+Ex0kkCaOtk9brGSDbDsWU/BEDIj5QSSYEeLfVbhHVKsJy1mq3KA6hdZIfu9VucfgjJhz81onk",
	"MbRbwptBiNVc/8Fh0jpp/be9dKl75lexp0a5tqP4rbu7dstMLBdrF+waoovzkiWmQ229vmQIu7iwDih1",
	"q4plhfeDmemfWdC1xyL4Zwx8UbGwpySQwNGEcbM+gdgtBR+NF0jOADE+xZT8iVVrJCLw1Nn7bcQ4wnNM",
	"AjwOAP0IRM6Ao2nAxjgIFupXyVb7T8kc6E/J9v9QS0v3L9RyW9ndAo3D1sm7ll5Rq91KZmy9b7fkItK9",
	"JCd0mtm0xDIWm+96vEBCdy1bnfsxXR6REIpap6IWBa27ZNGYc7zQaw6ATuVsDeIofAAhwUcsllEskelV",
	"Bkjza26pdl5CJUyBm5kZ9h/jAFMP+FrUVY3R2LYuR+H8mFtjcm4Yg9AU5C3jN2sXatuVLzEZaOvVuRGW",
	"FrYO5U6DgN0KxEGwmHsgFIWMAU00JhqCs2OVnWt26QVYuEQQBciWJcZKSJ7SPOGWQjM/4tYgjSm5YZx2",
	"vIDF/gfHXD/M+93+o+6jD9HN9AOLgOKIfBDA58A/5Cb2C3a3g+PIDlh2JisA2OpgIs5+B0+uxW7brvw8",
	"koE+41G4Of38VnZwAHasMthnN7sV2DlMgAP1oGqZyQpR0rwE+MnvlcBfvbc4TNcRpLkFppW06IbZ+ujt",
	"AH5uUTs4RjNU2Slmlr3VIQrwYk7k4hlncbRenLWt0VQ1Lwfm0qhbwzQ/jm9XrOimxlJVs6olmmHusTY9",
	"gF2UmJ0BV6K9hyWcxnLGeB1x+/r6OfLSjgi7nhULL5tq+52UjGi2lmdpHuNg2Vk/x848FoaMfpB4eg0B",
	"eJLxSrYgQCI2QRJPNc6HWHozhKeYUCEz5EColoMnjIdopCHw9zkOYhi12iMqZ7FAtzOgCKjHfPDRgsVo",
	"ChKNWv+QePr3CWP/uX/uYTmKe73BofpqjPl/7p/7bDpqlZGUxNPtqOnOHAAI+Zj5BHQfdwW8Mj+orzxG",
	"JVD9EUdRoIBOGN37XSjQfGrBRxxGAaiPIUjsY4mLADgHPmYCUPb7FR2to/9uqy2J1sm7T+53L4iFBN4h",
	"Si/QAG2dtI73D/vD3sDrTI6PjzrDY8/r4PGg3zkej4+P8cSb+HDUunuvsD0CT60pYXknLe/RweERDPzO",
	"5BiPO8ODfb9zjPdx56C//+hg8uhoODgcG0rZSEP8lRMl+quOqxeLhqjWQjBNFNfuChk43eaMA5Zw74Ow",
	"IIzH8WDQG3bm/e7goHvYmUZx52Bw0D066PYOOo888If9g2ErAy3MvRmR4MmYqwE+Hh1+OBy22q1pFOsD",
	"5mSuaKWVjNJqt0LmQ6COrnXa7/Va7dZz+59Br6fUuDlQn6lOl28vzi9O1XRMmL354ARfpnS+dssnQnJm",
	"lk5l3Gq3JjgkwaJ10vJhTLDCnxvgFAKlixAaf9TIwQlWMLIMU30FXJhDGAy7PbNFNpG3mMNb85NewU08",
	"VoNJRQctCyXVNuakddKaSRmJk709C+Sux8K9cezdgBR74cJolXv1YNzl+FYti3AZ48BKk2pO9wX4m2Be",
	"iirVeCcZ8nQzjX2ql0K9j50p6yi+0LHQv1hFvSX18e1gR5iZX+lVPA6Ih16fXeX1z5RL3MK4E4wL2IM6",
	"aqIFMccbCJ1yECJP/gEREqi2ir371MJKlAH/jPj6i1avq/+3p/GU+AG8JiGwWF6Dx6gvWif7vWQlChta",
	"7VbEWKAGngEO5OxsBt5N+ufi9YyDmLHAb50M2loZ53McJMP1e+2WXJriQF1fBd3v2q0QwnGydN/Xuztp",
	"9c2q+z29Gi5bJ0e9o97dey2Zf1xccSaZx4K3g9bJBAdC8RbXTDfRv6o7xItaqleq7Z60DvuTHvaPDjr7",
	"vV6/M+x7487RYIg7cIh7w0eHh0f+RIE80ud2ceXu8DmJTtP1HQ+6/cOjbr/XHfQ2wOoifKvBVvOY013F",
	"3DeR32Dud4m5eTTcFtMMfqxlpLFuVohvloI+r/xkJ31g8cmn4hKHYC5WjXlHXf2/lj41mJCPGZJXGDkY",
	"bkDzdhN1RajUfpZC/YGupq8f+ksGspNW/7A/PvYPcOdRr+93hhPAnaPhkd/pwf7wAPxJ/xCOW+Wnllp2",
	"1GCTfn9/DMeHnaHvDzpDrz/sHHs96MDxoXfQ600Gfei12huL16qH2o5etXm40sv5xVi0TwYHehlz4gN/",
	"ZTbuX+VbHCkdhsVaaFMQh49yxqLcfgyHSfbpmKWG7qa4uclV5GzTRujKY+mDXENfP5Z+1pOqw8pLTypn",
	"yPm85+Sm7mib1UNrxHFgD8QjvtLL+o/UaWi49wdaCePg2YU70cTdxJ9aNFZXu7qT7wou5fqHlgN37Qsg",
	"b91bPbcvcxt81vPbQl6/15EXCl9bnvMmzHT9UX8JlvrtkOpuz60+ay08N3U1XNl73aDAs22PTmkfRP34",
	"2pg2nXkmZwTuMj7dizh0DIPvcMD+oqUUEyHwVHV78lECpzjQTgHmBZ7o5wyYMK4f4vRinQGFCKTHMLY7",
	"rJeVjKFf/684RJiD37rbzDy/CpZTc6TrNBKBJRGTBcLJYu1u0TS909QMn5tC1JxllCHx1P3k6EJ9ZT7n",
	"kH8S4Dnjms0d4yPvcP9RrzPsHR50hv4Qd4593Os8Onx05E+GPc8/VoTm/GNqd7CsNKdiW0PGFSY8T3rO",
	"rHE8sFqO1rzrTpbVV0+DgHnWBPipBRSPg4whOEd4ZgkbTNOu3xr0omIB/Fyfc+ticCnG+29vfvn1cj4O",
	"f4t+u43IeHDc+/egf/Nyyqa/XD8O/j2YzS/Onxy8IMOPl79P4xdkePDy+rGEX2dzb/+f06vfh9NfBm97",
	"/14cs/H+Zc+7jW7//esl//evfvCv/be3v+3/z9lvz94cXjx/tfB/ffOz9+zp73jwlP72rxeHZ+RUXjz/",
	"LRr/k/29dbchGW0gQqjmGfL4UjLDt0YmW3QhdKphaEjrWr+YWQLTF9sqVb1ftS6uEETdRdSiAQXL74UG",
	"NhOvVsjgy8hT3xoZNDj9mXF6E9EzxWmKIzFj8no3EtC2L6ob7NYueLt3Pe3dakcgdLoEi2LniS9074lZ",
	"x8MPrDhtbxvd2AJqKPtnWNi9gT84OOgfo9PT09Oz/cs/8Vk/+O38on/5+smB+u7icUwC/yUNFq95LOQp",
	"9WaMI4+FoQL8BvhSfai1HBJKXXsM2hj3/C+EJmby+18MK6hQk9FmUQH2D73ewRHuHMEYd4aTg3HnuD8Z",
	"diaHk8n4+Gj/0fGBlzeG+0fHfX886XV6uNfvDGHidTDs486B/+jR5NDfHw6G41a7Jcif8Iw8bp0Mer0E",
	"4GcBFmITk7rtZ/ThTy060YZ1zpgUf8RYzNz72AbIlT/69chkO+Tx5ovIE7vCGywl9mahi69JZGBzWff2",
	"xweTsUYIhUj9ww4+Ohh2xkeTR/3Dsecfj8f6Fi484Ic4qE1fMdMD0y5hImJUgHXLoYIF8FIHIryyv2xs",
	"opEGcK1fCI0/IuuPgw66/YNur9PvHR12buYh+nGsmKH/PwJv0Rt0cOgfDju9g/2f0I9Tz0M/vtFeQKjf",
	"7w5VL+MU1P//B4Nub/iT/bqNnl2+QYGPflT/fUxoLEkgNFKa7j+hQXf/6Cf03477HTvg9Ysr9IJRdBpP",
	"0RD1j06G/ZPhI/Tm9Rka9AYHycSZ5XaP+3rF+qv+0cFPI3rGwhBTHwWEwgl6/PLl6w8XL06fPfn73pgx",
	"uTcPA0LjPzvLe1bH/fer01ev37y5OP97/xAfH+DJfudgcvCoM9wf9Dv4EE86fq936Hne+JHfGyLOkD2V",
	"v0u56Gf/uO6hCFPi/b3Tr294yh1xMc7YJi4exWGIJnD72zUIdajboUjMg4yLlVpjLKE7DVi/68O8S4WH",
	"jcvVyWHvqLc3p96HgEjozmQY/CPCcvb3/9x/KtkN0P/cP/cOhzA5GkNnAMe9zvC4P+wc7eOjzmH/0eDo",
	"8HA4fvSotzF07PaqwSNMozx8wJoFL615aRsIOauPtz85HjzqH3b6E9/rDMePxp3j3iEoEabXPxj6E8+f",
	"ZGLzGNNGnXobXV5n8VYDIrQf7BwHxEeuj3tBE3rHRvvadqNZZq/lWsLoa6I31D9+1Ov0+p1e/3Wvd6L/",
	"77fWJna3BDTT7rA7I9NZCGEX93u9bn/a7fem4zruj14UP3V+iBdUQoD+BYyiqwBLQuMQHfUPe6/Rj9c3",
	"iwDfwE+mh2idDLVH443i/okPZcCmxMPBGYsVcAbaV4bxRevkcGh9KfUkQhLqSfTiYnCgpczZQmS69TNu",
	"lacvzlt36TD7g7v6GGDPrfrgbSN90NaFlcDOzhr8xwqsv7MZ7foM/gf2Qk33Coh5XBj0Bup26Oz3X/eH",
	"J/2+xQXjgWSiAhVLMQ5JDknw4XByPDg87uwfQq8z3O8POuMjv985GPjH+/7B4fH40ThFkpj6MCEmFvEz",
	"Co7afq/4CKHTZCPJl/ZJwcmzEVAhsXHe0m8d2jl2guNAKpipb84YnZCp+v7ZLPIWj9X/zy6evwq8/X/+",
	"vLzE8bF3rIDxaHg49PvD8eToERz0JvjR4HD/qKd2JMTsZ1hchtixGGNd0N1x//jw0REeHPUHh8PjR/4Y",
	"D4bjg6F3fIh7h8MJbt1tIxdbr/V0rxvgdBZFsV+N2rYt5JB7sd2N1mB2g9lbYfamAQelaJ1GGOTlEW0h",
	"2hFS55B2v9MbdAaD1/3BSW940t//bUvcbOIUMnEKTmPs9zYLWqgOLmi7+PaTT/qTCczD/mLTuIMyzNNW",
	"SDnDEnmYojGgWICPGEVyRgSKAiwnjIcpPj6AsNhg5PeCke83Qsk18qvN/6BxE3NAahgsyTgAdEvkrABB",
	"8w7i36M4kEQnfHFZAKhvQxWbyIdtIx+ypHSvcJ7WoLev1tnfN2vdXL55gFCgCjG+MvRHbEe67xrabWi3",
	"od1l2n2/DfGKSuq193OOikU+oqpRxL+AIl4ddpTV0rMIezQYwpE39DoHRwdHneG4N+gcH/cOO/vH+pH9",
	"sD+e7CskC7Dea783GN5VRSN9Vt06QbgyZC2MPPse8TNcdOz+vkkEzfHTXSLXDuLWtohoquCeeAEc7Rch",
	"ZmObbxjnZzO3pzi37p7PvRi6P75TGb3hog/IRTfGzVpSaJ6fGiw1GzwHiUnwQAb0RxoNeyfDg5PhgULD",
	"5QVKFiEBHgeJ1EAeKC0HCRbC7Qw4uPxTb35ei8I13ckcv73p3IKQGyLVBLCMufEkco/WiX9BoiBlLYbG",
	"fui5h53fwuN5JnFVpmX96zN/bGUn7+vfwc86kumEX0kqvgwOPJi5+ms//05/pxhgdd773Dj2QKrJ2TYq",
	"iuxudMovcNl8jVHn5axhfexxg0bfHhoVR0Tf0wCXkYHGeP94PJkcdMY9/6gz9A57naNjOOiA3+/3hvsH",
	"h+Mhbm0dgb09tjb64PfJ9N5vhUk1NLU8QhVcot+r2tZwwM/CAbdE3DpqXDHqmhjA7+/GzkfPfk0Y+y1l",
	"fmiyODxctG/OkDTDivxar2Kq8EajEZljCfr5Mnlw7B708g+b/eGgOzjodQ8Pu/3jw40jiKsEp5UY+IZL",
	"NFwi6RA2Ef+75gEh9lIfgwk+6R+e7MNJf3CyPzw5OGxtl46Y3QK/ti6E92QuD6vQOR5TmyF9n6pbw5Aa",
	"seUvKLa834xR1FLUdcMsw/hONfOGZTQyTCPDPJwMsylvqmeLyXCnwnQ1BBpL4hezJO46c9H7+6Uusriw",
	"DqnKchYRENXJrpoXu+8Cy+6dH6sifHZNPiwdLLwdGlk+bsDQUf88fvLs4hK9vHpyqWa9enXx9vT1E/Tz",
	"k3/rX0d0vP84GFMNH/7bv26k//sTBZ7Tx88O5uPwjfr4ZBwex7/989T981j968Wt+rf8c0S9wVT+9us/",
	"F5ev33x8qVqdncn5q4PHT8npvw7/9uYZu7rdi5/tvemf47+Ry35w+fzfv/55c/Tv2dVLeHN7ejqipz+f",
	"zv48e/s/L7zb4PqfZtxNRh3RonFPn5wF//7939OPT39/8mL4x2xfBI8urgd+9PjP6483r173Ll8vji9+",
	"WUwJPh1R+cfg+PnNk18vHk/4wT/xdO/8b8Px8es3l/zwYv/XNz1/Nn75+iN5cnRw8Fqt8Pm/3sb4Vzn3",
	"wuH0t389ZiP626/9wAufiotnb29e/P6m/+L1zRQP3h6MqAb1k8vz0mNobYJu6nDL8eoGclnVdJKvX4iQ",
	"u7v/1nKeFWtDiIOgyPvJlYT31CK7u5bkbYYuPbiTkzfiKJjjIICAiLB1cpQ+aGmBlE7EfF9NNhFzLcM+",
	"pChUcJRrZaIsaN2VZb7bLTZ8XdpbPivb96K+7SZHnE1xcW3Td15xJs0D7pOscWYll5xrzgLi6Uqe795v",
	"kGEuq8/ktqFwicVUvowSJ10OIZMQMS6z8XCHHffpWOcfUp2MXpltdLIXUrmn1rGUR7oOdOrwhS1IfA3w",
	"0vyLx8eHB8fj4bDTf9RTi+xNOsfeodfxJv54OB73hkONY7EpKfCp5eEIe0QuHi+0Z2u/92j/0bB/NBiq",
	"AzOp9/xTaUjusNPra5IbpGmtYqGoVvc9Hg6PjgdHvYP+4G5zlvR2oJhJLU4k8jkbv8v3r4b7NNyn4T5b",
	"c5+NmU/FA1cmT+xmVbux50Ekwc8yqKIS+ibV6QwLNAagyHVDmProlgSBrl0fBxMSBOpbsaDejDPKYhEs",
	"uiP6bxajEC9QxILARgKYQt96gJBRIhlHRAqURQ79o+FRyGD2iEqG8C0mUucbCSArX7MIuGY/W8BhjH2b",
	"UXc7Vg2c65wyhOqEjh8sxFpt88uHPEwdPMfMXyDbRTEtjj34oFnxwaOx1x/6x2N/eNif9MYH+NHAHx/t",
	"9/rD4/HhI1xfhdoMDmYfBUj2KrvkiYnwMFOYFJYaMm3EuD1e09pnIBBl6rSoxISOKE4QwFYGmhAIfLHF",
	"kXmMTgLi3fPA3CglJ4VTTLVZbQAJHAJSlwnCgU6tg+AjEVJ89SdoN+K2LMyWMGVyBryNYhHjIFiYzD0h",
	"YCrUdhdohueQ3/gWpzVhfEx8H+j9jisZpuS8YmGKS+mMbTgQyGca/5I9JHgXcTInAUxBfCOUd4sF8oES",
	"8NF44Yxof1q6M2eGF4oPe1gnCRsv9IZzDRX/vAHqQKJ4bA4owmMRuDz2p1cXCUFruCpqpj+kwBxRCh4I",
	"gfkiA06TnSxT6yuXBGozoOjcIxQHpt7EEwWi++GPeTyxwC5GIcvcJEMGVl6ASfiV48gpRTGFjxF46lJm",
	"HMV0hqmv9qH7IOZ5Mefgd9HrDKZgJDmmggCVth2m/oiqX0XseWBSzSkeKPmii9DFxCAa0WigDtnDAtoo",
	"CgALhUZKnkREIix0DQ0h4m14BWXyKYupf7+jpkx+mKhhSs45c0+Bn7L55MrSTP0rP/c3WptQuDoh1Efp",
	"bbUF1NWfxLeaipYI9UjbHUKO63zIBEPPpIxO9vbU791EfX3fbo0Bc+AfQpAz5osPIo4ULilF6Z1SU33g",
	"xuwonDbikpwD9SNGqOxmlGHNxpYGMdsz6seE6Ox+EGISmLDsBzi0EngWHePLCOjFOTLRurERYk2mR8mQ",
	"T4TH5sA1J1fXmoG6ewdGtzOgaEakJHQ6orpsoZkRJaBBhup1tUUZc2rZm6LfQBO/HgPT5cvC8AQiEFBP",
	"qYKg7whmxAIP03RtM3arhswscRsUtEX8bRbE7TAvecMzExs9slOQiVGt47D76KFodnkvxbqbfpZLCjkQ",
	"qu5Jc7wTJ0obrwVkx9sCqjF1xwr3ZKlK7RPig5FCyiTmPJaa2/Rrvz6L1uxEH7NpKwwoDRg+RkpY2uok",
	"Is60xDQO4MyA/34nkhvxg+u/9sIzapySKG2c+y1ndIoM9n3lh/U6lS39ZD9qK2JBJfbUKSotxmOcgyfR",
	"ODaSCqFC8ljb4HTr2F2dIzrWAyoogo/8WN+nAkKsMMLIRUY/nbMgDh/2jbGkMkMeAr9gCdRbdARQQSSZ",
	"g+LPfKENMuOAeTfOIOQMu0P7T6fgX+6fTLkLLGSHzkPIPg8mMzjLZYg/kjAOr1MD5vCo3QrBJ1gJX3Nt",
	"aw0JzTXq99qtCLjGM+oZIzf+ePHy6rp1Mjjo9Xp63NczzuLpLIrlC/I4Eq2Tg17v7kHfHAtOdt2TY1Id",
	"mEIsOQ4M5DvuJdKMmHmQTMhEm18vn16/HVy7lDG5KS6fXiMFdTIh1tgdAZcEEqvvtbX6LndUvyFrEk5y",
	"QYwZCwBTW5DIqHlKHMoM9D5NHDH+HTypjr3Mo/HTujxEyOSeyWYGtmMpqgIdOIkmnIXGomA880f08QJZ",
	"k3kbMRosUIS9G5ArTX8QyURaN5xgD34Q6OIK2dSSI7o8pU7soUZwOb0QeiPAGA2JQMy80eseIjOTMTV6",
	"RpdBnMVqmFsiZyyW6Pry9DXSMaNdRWMSwiLY0GQdzthp1mhh1E1PSUhuU37aLzDneKEPIpcBe3mKs6s3",
	"KNtCDQk0DtUJJ8mysWpxOMycczpdvmbR6vi5ekUr2JhWpKruWLDTJXRMRipCxqXSQQVIWF44aHnJukJS",
	"kY37zatftARrb/sZLA+6fhNq7KL1L1UEKsSUly5ny0otoNU9KJ5ebKa3eHZxXohbhr9X9jTWvXUbJUkF",
	"oBrbreQarHTbecraoOBSERUphe/acOYLv2g9qkHiRWLAZ4Whk1YcG+t8DiTt1sfOlHXsl+ZqIr7oPs3M",
	"dJ5t1SFhkoHA3LNJJ3XAWM5aJ60pkbN4rLTYvLRks/PsRTfTPdXhLqkOVbgZ/csq3mTljh0qOhJL4jn1",
	"9oWbIyM7rK+VpG/CZSxLlmtHKsK11NW/DAz3O00z/Oc4yGJhoPwwly+GKiDn2t61W2PMQUG3gBX+OgM5",
	"sxemBSARthCwD77W7H0UYm9GaJZTJHJGrq5XwXY4aANziNTdZaop5JzloDvtIl3DAZlMHe2VG271Foti",
	"UczYzBCK05xdvRGZzkp6mAJXvU0xsaLeWD+Aq94QzSAEJeap1kpreva4eDRbmqLqOKZRbBA+rS9WPbtp",
	"pWclJdNGhFLQDr6FZ0qRltqTCsYoFsb4rw7XHHMYC2kFz4W23tIJx0Znijm8gom6Hk0pnIl5WpCYT0Gi",
	"GROyu17i1IeU7NiCfUnAKSfxylskqaVW88awrLPgophG8QtTLW51tmdXb3KIWYiKbgDtKVSx5OXB6i8+",
	"WWLx8ov5iJrOKRX2jXyZoeRL6BUhpG2RIapnV28EwnNMAq1MKyUcgDqjwsvrYlwtQ3oNk/WoHq49oMKT",
	"WSr2V7RB12R5hz96mPvip3SnxQtzlWXWnt9b03CZQmx/t8MMreTX3s6fVRHRpJMUblRBysyW1RhsQZy2",
	"Ln5YpC0sFYGrQO/k8c8hHUr71sb0fGmuVWx3vxdf//q+TWt33UcMuHATPawgkNtvwY5Kgbr4XLKedda7",
	"9liUfSHC/qZin1v41oJfboB7wiqXQ7ruqpXCdm2SbGZNU8Xa1VSbGDKV5EjG0wl8RGiFMaBO3k7tHLgM",
	"R909s7h1cEy3tLKNJ3PgCzkzTlkoaejejyiAL/QzZEy94uvFlh4sFNJwCM6Jy1ItzfxhnsWKBb9s9cJV",
	"JBhjAYdD/Xrlg58bTmt8xfdE6pC6POKV+clJQQS4tvAYmdg92OTlpsIpjAym432LpjHeDibX1rq55Nq5",
	"TDHGQtX/SSLV2lgaNAUKPD9FhmyKBr/KxGBVj2+jtfQ8kiXF7MYLNCNTpXMwrgnWPHSJwgldHcnlmd4I",
	"4MkVM9nuXO4qyONXTiQUGm4yxSH1U8TnYsV8S4U7t6N7s990lBXYOL+lCHMcggRu1Ejz4GH4SDlLzjLU",
	"9dzvwl+1b1cyvdA69xYXXPw2LCd6qU6PTB2/13cxTdedejJmKQDPdEhCsTlWF5635StN6MI3Qx/p1ran",
	"jqUx1oJojWp2H1tPDXuEXsOzKE5LYa5t/fJaw7OgbGWlK/tye8XROSmCz5tXF+qSiCNdx0rzbw2pCWdh",
	"XpDnpOiiWK6SWWNPb/NdVq37pLUyrgZYDSNGAuJSdczUMkVkol+qcRCAv4oIruDpmkGsP0nbeetZXS9B",
	"s8Kr1dVNrWd9MJFQO9R57dZKgVeo5LkKufdS7sKHt9U7minagQ1boFMkFkJCmLWGFojRSZHaKtuqamXE",
	"am1OvcVcLvbGagfFZ+/q3FafIhPnpt1dWgd3XQ9rCb5L6+Su6/GzaXeXKaRbtVXbyGzUB3EjWbTnMr4V",
	"MQbnALY8qGVKS9Ek6bHoCUamgO+otf6RzO43AVUC5XQNpchecmuUyidf7QXhHD+Wt/LCOIYYa7pqlfqg",
	"K64vIMPyq2yBu7iBdn9VuG3f77qweYuKeL0pvvyDQAGZgLfw9OOl9rlMrXmujqiLDdUfTSnotnVyLzby",
	"ZYTE8sl/EDYkaxUZhVt3LVF01Wxh+peC5e3KcS2/dmCJVFf9cmIeqrLYpNWQLKCy9bOzb2PtFqaLchBV",
	"vkhsWB27rkHUlIovsIQuv9VUmcQ6SyYxbVswL3yJAVy/6SD9cCRAtnMBHerovRn4cQD6cXC8iLB2ncPU",
	"zzjQLNu4TAb1YIEYtc7HyfT+8htSBtRKGKIe/OIQ/crkDSx8n0iIQScXVOeg37HMCF30knqQCzD8YFAY",
	"ccDeDMSIZtZrhacxeCwE4xASkLniU9gnFIRAgkwpDk7Q6dWF9hWJQ+BiRMWMxYGPpCI6ZHOOoR8pk1lo",
	"/ISwGXNkSNJyvVHL0vGI/jOG2MJUOwlrlZkDYmNTwQv5sYKR067+7//+P8h2mTA+ogkap37imOjrjFE0",
	"w9xXXLCdDq3O37XUoT2JAZUIhD1J5hAs0FhNqZrHURe9grHrbaLFMHURcTlIZvBhDKo1B43I2swXBdhG",
	"gRITdhFrV1YUU0mCEU0DPUF0kQ4ASkPTUiOviTyBPPpRhEdUAg8JxYGNb3HQzZD/VcInDfxa7ZaDSqvd",
	"Sjep/kgyyF1LFkWZj7qbXl4xw4jmwyS5XcG1fnE1HzrvsJwkqzq2qgdc99KYHXuTx5fMkgs4TrYe8fO0",
	"ivTbQeFSsrWIUcRY4MJ6PdVp9QpZrST9yTmcGidS61jaOukXSQUrJaszvfd7a7svF7ferHdRHewNVl9k",
	"hcwCu/ixKw/h+6hDv2TnelitKLutX2yJ80scQh0kciXRjccaeqGdFyTm0ga1ooDdAu946h4IQErQsW1I",
	"h7reEgEm/E2HLqPzy2sU4LF5Nw5xUhbxcF9vSwJXK/hf73Dnz/c/vuvgzp+9zvH7//7OfvjpH/9RRKJF",
	"u8uWNS9+YS/co8vFlJVapBe12q3YjwoZTtHkm4C1QMXIVZ0vZzfOBVFxnbOL81ci64yb8a7MzpQwpAy0",
	"f/zHyY//OBkcvOt1Dt7/1+BdrzN8/06B+7/e9frv/6E/mn//NBp1f/q0f1e/+d6P/zjZf9frDN7/17t+",
	"Z+B++I86DrlFBfYLpWQ/AGQ5ibqLhGncRefGz1k/lx329MX7+uwqgYdwl2FMk/g13ejNeaaRxVTDRY4O",
	"h+vZkjMa4CB4OdFhCHXLzS+R5t37dqHslaVH/Y7GWLBJVfsrpuniLq3UVDGLapKDweHBwf7BOhikRXo2",
	"332GdJcVljTbmhnd7sCC4P0ahv4CwnE94tQXZwjO92iJPlPxYoNr3YF6Ezgu7d5NbAdbt117zPUZvNp1",
	"mYSgZY5NTjMvqhhfpDFUc7QM2OuLT4UnXMBOIs4+LqquhcQhkyGTVh5dqS7I9UHzQQ3nO7fNdafzdlD+",
	"qpM/Hxe49K286xTtcusHntLBtmKwNhLorv1pCYKZ5Eq1SjJf+MaeFWV0jXrLybGFQgafhspbe0km6MZa",
	"ClxUXhsRadxJJzgItEBmHToEBCY02QXxKAmhu8pQk+2sAv99uy5irjyqrTnGUp+27PDfnKdVIaLVfC9e",
	"6ruDh+OC1ayD+A9ireeqk4qquHjx7bIdQ89I1Hf6rrwwI/QL+HuST76CsTtnFYSRaY8urmow9XTfNUBd",
	"YtBVKGUi7qwtLBuDjsdKeMXrKCDHpgrcuyytyxUFZwwBo1MlCRd7YmVgtys2lrVLJbBOTS91ffk23svD",
	"MOXsbgrYcrlXTLuSxy4jzxud5m69TGDS4X2bEsFOZAFRcYsU8aHt2I8LT17lNvZQz9NipUU4nNQyTery",
	"x0Hu6SgtcGoCdgtNDA6BztcZIB39X5yLimDZNK43eZSoo45X8J7TzMzb28Mu3TYf1BRmV3qVUVALtF+8",
	"AI72/5bYg9zdcZs9PEx1QlcvjNQeEytRuzXnPKo6yTLMLY1D/coln8y2tibu5TGKntWSoBHTdr284lNx",
	"iUNIsiLVvgWc001th3W7JOfcLZy/uglAL3+KML8nrrMZDFhBngdxfS+/tuzK28tArDw81QgnqW+X0i1Y",
	"HsEzrZCH+VxLYxYOSRICbWG2XDOrw4yU1LTkYqzdGETszRAW+QBjbeGzqe2SV+ARdZ7Pqr3h0Wkav6Wh",
	"3ctXd0SfMo5sdpG2Sde2Nxgmi8PZjbn9BNrArfYxOBhR0wAEcqWQet3e3uCgjQIwKQLT7/uDo0761+Bg",
	"qFHk/PnZVXdEs3DWT5UT8hF8k1sqCy8i7KOled1ULUkYxhKPAxhRPJHAbzH3CzwLzPKdeX75JM910Rah",
	"c1GFCuxL5ySZhQW0zUHqJ1VpnjvHMCXmqbbgdLsIrYHyiOpU0gakKIGoERNvgaMZDiZLQ7cR6UJ3RPNg",
	"18m60uldyogfu72fNLimWMItXqAfu/2fFOxG1CFQx07rpxo3lkhE2FMbZu5lNWmVvAna3StYdAd2/nKs",
	"0Yr9GNBUn6FiEJiOaBZkufY5K+1+1kzdKzHRasR+ZVd5VXnkJqG1yfeDNcTX0GyyeQ0W81SevCLHAtbS",
	"k35dyuLh3wcHJmti1cr/Pjhq58nryGRjs6tZWYc+ascuYmFRiUOICfVNZOLqdtpZXOofdrJ0+6ibZG8M",
	"sfRmIHK7MB4ekzgIHD8wR0+EcWTQSZ1TD5IlMKrFUpasl2M6hRElAgUwkRshwBLjzxF8BYvPX3AlXpY2",
	"0USpOLNGjV0ZoSzNhskVs34Ym1OmZBQRjynI9aOYdmWjzANcejenITJvfzm9zI+QHkgK5CrbME1u0W9C",
	"9Vva0X3Fw+1MwEnnEuvvckWFQjzItFEXXCJZ5bOsl8QXbikGInS+oDgkHgqZn8i5lieN6NI1YP160sdM",
	"feUqxkJCaGve4TPtZ8tG9Fb7ThE6Z8Fc50vSd7QhFTQGeQtgsk5yUF9whn0P60TjijOKERUMARVKRHK+",
	"7wHmU0BAWTyd6a0sWMxRxKRJEe0cT3WphBG1XlXSupPpRaqd6U41QvsqogetwUZHEG58VJsHROlsqTnB",
	"dyO0zEnNq9Ynd/Pm5Walj0ZRsKgS+nQe4RFlIZHSuNlBIgO7JGDadQ/tJaKUQTDr2bE3OMpclvre7+hH",
	"dqEnJzo14xIxL9FS9pzaBepFrWeHCn2vnFF8p0r2pi8LabcdPCrk11AO3G00840ttUZHX0GX88tr7RqR",
	"+Fhqf0+TUxvCSNq0+7qWhnN/d1TxgxjRRF1UA1kPR609BQG71e6zwio4mnMCVvqPnAE3UxBFHiMasSgO",
	"sHWUpEpmS8ZVQ5jusSU2U9UjYkIQnfLCiTZrD9e2Wj7T+hr7Bs8V7omilH4+u6kjy/JqxPgvM+mNWfNa",
	"W0kloMtN+24b35ZRf4kfbS/TlUV8f6Oibo1w73XA+IoMoDsj6kJ9cyPr4tpUOBvnM8ya48tfPGo8NW07",
	"c/n7UhIBWDCrjm4jY3N7lOSRVCNU5IYz2eBMWshc8J1wKezlIrL5nX1r7dMXJfZudHCwfuEpmffnJP5w",
	"eV4TqadjhrIPKQGh8cfCBxPDY89BYhL8HI9VdwmFt9U064iSe1tPJGQdqkQEGrVukqFMfOES0WgV57Ii",
	"h6ea7AeR8dQxXUwgqM69oKNUMtnki5NsqHV4JUlVcjMt5VdJQbFUyqAk18pywGQ6bRG9ZYFehvmmzedm",
	"ydvIzdndbH1VrQyyApKLFW8OmRzgKpgmgJViK+ot/qlrbVEmpYK6G8/Qzs6yHSV7KAfY08w2V0rpgcko",
	"aJtkwGUK2Bm1U4naJvVR0SuFvQ/L899eTFxUHRGIUJNV00YLZia0JhOxcsMKY3FmFJCNNhvnfUE0sQex",
	"kDlVwwRvJrnp0Qw4aLWgaE5F2x0TQWaDKEXbRfgJSF4BMrOqBWVjCLVVEaRnwq3W+DKtAK38+C4qSP9e",
	"T/2GXT/wS7/56nthYPdkXV+WaX02huNKt1ZcpYk9a1kKSd/6c1y23RIkNLp8hYhS6RFpm9SWDjOYWyAa",
	"aqW/Ul9SDYpeXT7KGYvWhkWmBXHUOLoOwEeJZizahWU7WVtN9cAtuvDIExvJOoco07I+/DWEC0AvwIs5",
	"kYvShHLqWjNNbFK5+3DJ69xsD8ssczsr45n5vX1zFtTcHrfmp3lIxQHUwAIeB7CsrLddVQydBlAgLNHL",
	"6wvnemZMjmM2h+6IXkyQNeJrGjq7OH/l6MrPxLiZqtG9vZ7JoGIMlvp1HtPFrZJBuiOq30YYl7qqmLbv",
	"jZOsWFaeMUsYJs5vwoz3+uwKmeg4I56Q9G3BbMU9KRhfOT1LgdDmEZ9vGDvlZ70sa6jVqVdmJvCqNmao",
	"M71SnTaIY1v2KlyxyCYryoxZC7vKfD6t+FyAaOnjUG2Gt4rT65hfAqTixzeFYNpuQNx7qcFGyfHEpsVa",
	"upx0HuiK0bIOmJvFImonia0w4JXuWRgoXtG+fA96JSvAaNvg6GLS0yTq6K+tqG8VeEBLLOVAfefAki5g",
	"cwhqx57iGXI+P9vPsZqYRod1qo3VopLiOMcH5cLbMeBVY9MueNtS8lx1DDaxeiFStRGZGFeBhO87V6Uc",
	"494w5pdx+QIXiIIh/hiHcWjQo2pduu4B9YLYB4S3RdZUIN0kOveL8/m3gy/D6YuDZVdFpbXktf4xQi95",
	"4wWal4jltzc91FrAVjlSLcPz23hkKtzebmTZ7XyrlobYYXzt/UJV1yPnOmj8FbSgTb1JljvvwKekaD1f",
	"jNlYLrw1u7lX8Oc6xKoZ/bk80LqAyZrOFpsMum0w5BI0y10mvgvmvRu2Xeo+8R3AaDcQWus4kIeU2FKY",
	"KjHX5pey3pdgJ4spdywwjhZltkvt7XY/m6Ue/qGNlWqS0iKfrwuK2Jam2bJKwBUmvAaIM/OervR3PjNF",
	"VUMv09AoLCX2ZtkEipLVKQRajOeVKyo4ZK2ThnEgSRQAenF6tpeGsaMftc71E4oUNLTrNNZJxHSVaKMp",
	"Jz7nNi9UsXFv9UC00TJrxFlNi4690syNaoQXp2fJQisGWi6Gp1a0BejWxVq7XGtJpWEFsg2ItfrcSgnX",
	"dqkZCb7lgsxpfExzbVQm3jBdr+yzmtEhnpXc21Mswby+u2dtgSUR2gQxhgnLBFy6fKvaFlRkR2bU19bF",
	"1zUeF8vWWPjcmB+5HHdWhzstyQXgKrRIZve7QDjx3AE/Dfeye57ioge8He643QpBiMLaLM/jENMOB+zr",
	"IEZf+4+YR0FjJbP1H0NCXbBgv1CqxKIIFC+Mi0M6gWlo0uIa2LiwEAeFypkqzy5ZRrrfTY6z+DX5tPC4",
	"UDJz8rC8BkJls4rCclgrE2bdz7B0V0mSk0kS4xe4AfUXkHApH7qyGWNOTWhbaQaM5B7OpIBJuhRZshVO",
	"+A+Rw8cNXY4A5Qq/q3HwjSn6atmb6ve6z07UegPSEBNK6LQWmp9Vc8RMlnfKJPJizoFKpVO7O+TeCO+4",
	"YzHS5x7ktzENldWTL3QauIdAmFvoOllhe4VjFSbloCs161j+sMacky0/vr7gsInKy1SzqRlcZDsUp4By",
	"2c51YRD0krp4DVPamUCgk8mSKWUc/JNcIYQRTfIuZKRpQPO+zmmfpPOXqisyCQ50UIuN/u5m3dE3EuUS",
	"P/5Cfl2DRFb7rei0WyCKW1YsgJ9bFrpaZ1D9ou5ViQl1PtCdpMZkzvE5a09TkoQeyXlkojhiFAU4pt4s",
	"p9qOFxLWUlqCUilGZQ6jgghLbIFZpC8p7BG50guV2FpcsEG/Zun6j0W58ExorCkPmVH87ANuRTWf8vR6",
	"esjlBG9rR7wrhVv1o01eyvlmjFrZjd3DqrUyzAbvNKZvyQNNYV2Tauxb7rCcI6x2GtWoWDbY5v4Wtlbq",
	"mdqZvk3gNJYzxpPi1TWhVTLEecndcH39HHlpB4RdD1N5VTI0ZkwKyXGki7tTJLlSgJPYlLRyhwvetju5",
	"oL+n/gG1F5/2Kl6vmaSjY+7V2m26+BBL4AQHyMXTGJ93dZdTE/WTJWqUekS0XQ+dQcXDZmOlB6H2qf3y",
	"0yoBLmvVz7CIMOHd+7//lQkWpWRlr0zFnqqYtrOA5S6gUvvitWYYpy4D0NqaYcW9auU3ZVzLxbmMB2t0",
	"pO2u8reDJdfU5NGsFLbfpW61+eup7bUz/ar4JGoL++jifMsHhouKx4WqR9zNpf16PC+V+6tkd9OqayIc",
	"U5E9kc11SrREuug+gBLhg9C19/LKxNkMm2pPGV2Cm3pIIsNx2yPKISnrbNzpmTSl/XR2FxCSM20/I1KH",
	"BkoTOJVezZa51cHSDDuslNTPdiygGx9l09qJkYos1FFN2Rw4TZP1abLvEEp0TRrqY+4b5+QQL0zhGTNR",
	"e0QxenHx4ol9+sBcIl0bcA5tHTmV0+cgxQ0Oum6Wj25nLACBAzgxdx6hU1M0KwDMxYr61kWnyFOnmtXn",
	"FHe2iVOQrczGbdmyqbYP/9///X/0oBLfgEAwmYAnjdtAgaCgwzIMlkj0o60APTMPOIwjiynGKHJvjaeS",
	"Bd3P6aH4AtiNQLrJm9J6HSgn3m6U46eUH2RTdtujzXpWaLfKW6NLfucKYd4RpR500xxMJZUUkhTixbDl",
	"a8yT69lkpYHza9NFMi9Oy/zkFn8mzcPmzfHrqiBW9/CXlY/7OBkZtlXlXaRh8m3lY8mLpFtbFyrciTRQ",
	"vilo3BMWNRyHdLMNTebVrjm1XIS2mbbCJ4jiSMyYLLe7qUFj6Qza9k3mW0GF3O62R4nVYdYCyvWpY4Qo",
	"qK+NffOijIOrHHx3B1MB4dyETSwFhuvlRxy0TBEESoq1Vdvdfx3MindTeGcRqIHcZdcX2SCAt+TKrKCA",
	"0ju2ULopv2LLcsxWiQErgdPrht/SNe/6eckeH9RXr+woSplN1f6/OcN/9e63Z0Y1xr2vgLnDdLmVJLOu",
	"NlHNPK/bz1E/g2kdy3Mt9K1xH1SysI2o5tuzrlYj5C7ppeQep+hlBFRBNBbAS07TPOFg6s1YgQHDaMA/",
	"Q2ECNkHoNIBOQCi4mTqGq0vw0dmp059vYFEjWUYyU8nWc5rcLh+DsuYbl0bFUwex9JqjdDJGoTB/ihCz",
	"YiAZjLYQWE41qg0Whf3c/eyMGvVAmA5YCEOTb/9Ue26HQOUvRMhyw9e5/mtsk1olcTlJb+NNaQe11mhi",
	"GsfUJvh2hmKTf2rsKkmkY+hKE0RqS6f1kUizViWOUngsgEodhDyiijy6mSG6iaIs0Dg2HYQkQWDnAR9F",
	"pmY/4hCyOQ666EJaS+aIEurDxw4OyJTaUhioYgaTnKqe+LYM7vTJpEB0K2hcSNTrTiV7KOWxV3VTO2Ye",
	"xQpfMUU9RNseySq3E7KYSpNZvFLTWKHWktzkl0+vkR4TMTNoYq5JMMmhe9Flp7uaN89igjZj28TtZUMj",
	"W/vUPh2M4l5v35sxIfUnODFfKBnWfLHexltur9VSc5GsYt5dCZ1e13oS3E4MvVqdp/y5vHBZFch3FmCT",
	"/7WGIcIC3lNdNtHPMjNVKGWZVi7ivjzBV1qqbRFBYm3OLjB7S9GJmO+ra2ki5sPie2l1jUUX+fIEX3s2",
	"ufy2theoVodZB531z74R5jgIICAiLC86pTO5Yj6FJJcEm2TeGXRRL2GuJJlUyumO6AvGId/OwxSRUBEH",
	"oAi4ZhvUgy46zdzUsYARDQn9MbO4tqvwdHElHNNxjCFXmucnGwZQo1K+efTalHhyZFGUK65mzbjcQd27",
	"cJzbUTt3ohVodG3tZOd48XLyK8BNUT6XN6/PkI911uJbgBt9DagPwSK1s0UsIJ61FDlSDxn18ULtIAZh",
	"Pt2CT91nOYu5/TjhxHwQWMbcfox17woO4RZ/peZeWMmwrN6yi8/Cobq3lpedkws3ZKb5ZaSuKWkg13AJ",
	"P9qtj5000WFHra0T4qhzAwuheSQOtci+2soOE+JoHRxKfWAdJBLRNg8M82a8Y4iskyELQViUaLHg9BbL",
	"K12SHwuzSV8bt5OkYuMNLNJ3rvzwNhFOElB0rK1xErga53+9w50/3//4roM7f/Y6x+//+zv74ad//Efx",
	"S6uuyVPDCTwPmFeuX8bzSUlgNgveBiNd224lV5AGV2bw7JJr8JGlE1+tZpcgnUIyq8raU7WcsAD8y1d7",
	"SQBdIhTP8pF01gnCBNRVHfOqTPpVIc/XJOQaNNlMvi1D5gL/FduggMITCBcIfTcABdFBl4mwknQ1dWSU",
	"5r5OTlhO4K5mqLFFR2UXVAKf46DoWr1eYmMe9kFJQZkbdMZiHqj7wsckMPenunbVmhmVs6DW9bhE8avr",
	"sL87w1JdOvSVzPBCraNSZNAr1WPbNRcLDUmuscHROsnNd8LKhqwvK+TctfWI6my2ZKCZo1UXGwnh5eQc",
	"L4ph4WqsKZgQip4/P3nx4jetL3dbOZbw47te//07xQT+a/Cu19l//9PJu17nwHz123+sj05zm6pAUiWz",
	"rlUdftCVKFYNGJdPr9cB7PLpdeZ2KVvFG8XEy2+K4gzZseq0rGMSisYLkzF6KW4bR9gjcvF4URj1KJnE",
	"gavvGQRMm4AzgyWvfYTKw2GrCBWNp4p/WuD6q45cSBxGqcuPWf0tFijAQlo3Fz87k+/swUX8Pxbgl2wF",
	"WxtQahkw29JBEJtsaTmqOwfBCpyqjB1yOk7eewH9qkMVIvC6NpdjIkVwJo3d/ImJHVaKURLwcG6z3Sb8",
	"M22u2tlw4y568jFS7EVpq0GA6kxBqE4Iml2ZyAo2SlFIV4IYN3XNTIG/06sL44gqENW+tbwTYoqn4GdW",
	"6hgeumS0Y4qiWe6vxHJhDcHamxU+Yk8GC4SFrlgQ2CjbL/3omr5sfv5Snl9P3cmsKaBsQXnV/uJ8dWUp",
	"A7vn82iuwOPS2totQf6EZ+RxEfnWuvkcM39/D3tVeZbNJZPmhqrmWiPmegsiT7ylv9G8gvlTqh0Tk3Tb",
	"RVBMbg2VUsUaU2TmDWub1yoLgnXcvjyWKyk175h33evmJbUXXFtdEEIYZxntc6v1jWxDc/NnGka5evo2",
	"wQISoMMdukihhVAaS8xTnqadeZMm+dsuc5kVB59ZlrACBvWDEhiekcdLYlY9gWj5vtzKYpQx5eWl1pqj",
	"ZQTclQTXduP5YatRerNCnWUvf/dB7JxNbwPrcmKiqFeoc5eHl6x13VVp1jghNjd1HuMKZGA8rYsGeQ1j",
	"NdX50jWZvUKXAVGJIBX+7PaKWXJoRy+tBFlP+C1mDlV8yXIFE5EFZZwhv4wVSTedFj4SoSPfnG9EtXSr",
	"prUVf/XlnkZqhWZFGNFE/NUtbLCX2eBELVN9/dX7GOYv3i2Eo83WaR2gjARo8j0WC1W/uFR52Q4oqcs8",
	"w6YIyZRjKp3TkQuLs7DImfxX/IOKBlZXuwIM6COeMSFLK2Qui2qbgWEMmAN/AXLGCtjJY/0rkuxGKd0c",
	"U6Gz34emeca0BtgH3mq3xsxftNqtP2Lgxea07Ve3JrH8uGqpwtWpS2MuI0PgSjekfsQIlbUfZu4B4Xuf",
	"F3DOCnJTPgMKnHhI/4ysUb+t/fixJOMAjGMTU7g2KEhYVjzqKZLABdhRzSEqDoiNN5VVvJ6/fn1lm3jM",
	"hy56oj4b9XuMhdLtTcOXp7GcoUG3N1iuXuHctszYzg1LrZETkJgnUoGawLymnV5dCJN4QdGgmoCJbAmg",
	"8SIzX9YMbBn2B3t/tFzEigVtu2Vo+IMPlGh7EmXyw4TFVH32GJ0ExJM6FZ860Q/qV5vuoKUOM0G0DyH4",
	"BH+QLoOfnu2DESE+SMY+BJjrazmmEWdqSnVBfbDhzkZAHBPfB1pISHq1H3LntXx8b4GPFVAsOiDz69hF",
	"XesRilkKxx58KErz9YaSP2JAugEqEDYyDu3V+rcD9uo27s/a03feX/AYgrc4iAsFClOwJlOFNlDNTaBz",
	"O1M6WNv9JjoY2Ro/dGX+lPePwboRGvugC/VWyL9kkX7X6xyfdn7TT1X/OEn/6nzovv/Uax/27zItSl6u",
	"NgOG+pP4V47bOd246MEP6MU5wnKmTtXL3kbIJ8Jjc+CLtelCsnfZh5oFu3dzcd+1W4bVfrA8/0NCig/H",
	"0N3MvBSsr3N3jWu3wf0uPBbBg21Gj15cLcBtqV1yqgVLqziC+5N11mRXYeipHTCyE2+1e1tuM0w0Z1+9",
	"R6xHjfgOtwPkhlH3ZW5d+mxThNWGPZODY9eWuQc6sJrosnqENU3juzi4jWJyCs/MrWZXx+UGeA44kLMy",
	"a42Cw0y3sL4nSj/KqTtO2orpDWW3tNVumfb6/R2mHPuaXRgx4P6KworWuZqxeQV6+oU+CPRbUx5uminf",
	"cmKrrS691FeJXK+zmJD5KSnQZpxqggXC8dS4Zmq3SxxaCT1kHEzKm4+y0otmd4RSKC4pKRBPd3x1Szwt",
	"DifQLnpbH/pVoStPIeUm7erjrY0dWXLQyf6pMdmHpZ93jdqfg2cqoBDv1aoJ59MKEQSg85OTsETm0U4a",
	"OcZ4iwXS/ZaS+VQ+08+W+NDuL/Qcp/u6HMMKlrIEkW2vDcX37n1XpLJjuVnm5cX5mbmcMuFceRacFS5z",
	"Npgdm7psloDCtYZY6TxJVoBMCA6a97uD7n53RK84dDgEgLV3PvXRHHOCqXU0WMrl7eTeJf1vPhr5fxuN",
	"upn/7EDHUxI58VzSheIn2scxCfzMBlOHoER3t0m87GhtpB1utEpr7JkjOiYU8wXCEllAmAT9CJ3DHALF",
	"IJBN98ZBm9/cfKamaE1/YpfqjnhgEo1ZZbRURbKzVI/kVmwbt011U3u6ayU166PpZrq/NlPCah9Ye6lg",
	"6TZv0uOSYFQdQXw7Yy6/0oqBe+VUXJj4pndEUcK3yjuiLB99bIxVyeAlWS1C5muT4dqdWxez9Tt3I67Z",
	"Oc7v2w5fd9+rmfSXQF7jbtAxu+5tBRGRs3JZhv17LKR5tDLvTT6jP0jHwkcU00VesNIGjVQ3iIUx746B",
	"woRIW0g4yXNI/gR/RJMlmI2bINt7EpjEhQlwJZ6iEEeRXiofE8kVR7MGPWaMf6KL0OsZCEAzPFes3diV",
	"cYBCwFTnTNQ3F12ghDJNnDLX/kegbdiqSSxAXbdAzTOfKfnk63pLNlJ1RK20r39KgN/W3eEjDqNAF9v2",
	"sISpuicBEVmXk546GlC7LmefxQZShacm6aP1XZB4Wp9R6jHf7+IU1/k6KT3lgd5uFA6tlTucX4Ad6FFu",
	"IPu2sM4sdErz1pfNM+S4VRBfdF9mZ1uTGCfTr0ZqHNc6lxxnc3BUmFhOE5PG/WBwZad4+O3PWRCHm8Qb",
	"J1VhKMSS4wCNA+bddJx/gxlv42jkzDLK/fhyjV6AT3CJqjxbCOLhIHG6CMEncYjG2LvRnDO3ylyUha99",
	"PoR+OZuHxdkycsu4SoNWC6DmzxWTEzqJQ9IOeTgS/59iSgIS6XsaY46pBGMGAz7X+F8Uzow/Xry8uq6c",
	"zEZQIEKjWO6xWEaxtJXDdGIAJeoK8Bj11wfHhvjja1MuJYrlC/I4ErWmlkkfpY+EMCba8XyDqYsCBlbR",
	"pKo02HoMRXiOSWBiuCjCNs3K5/I2KTVY1PI5ycFia7+T1VHKK585eHo4wmMS6HxwCKdnr1TzCmAXlRrz",
	"+CKSVU6YZoBErjYSmDZH2gPkgJJhjG4nZMZNQq+82PPRoup1mQPkS1tqr5PJ2erQ2+3LBkVo15kocdBw",
	"q2srrNJZq9Ez8rhb5De5hvgck6uNCIYt3iUDb7Y70+dz7S7K887ae8zy3IfIWfzK5SzGErFbKsyec3yD",
	"0DlQybiSjiVfmHy9zmzy1ObuFhWBqdrrwt2pdkKT81usOL6sTJ/667nAEy3b63AT11nR50JTAyfeinWq",
	"bv2upWB1I5DbWHbJY6jIQZAS9yrfyRS9uNYvyeb5UTv4nMbZR/wyxHUJCAkHkfrK5B2pcG4kjaABu119",
	"6j9jPqx8+YYHrZPWTMpInOwlslOX3oguxIqLdW5ByGGXCg8HoMUts/69+WAvN1Ly1tw6+aRAqtZ2r9H1",
	"CLkLUv/UurvTsYwTVlAgQF1Izh04dYhQ6i5nscxYzrT2aJJhOeOTkk9yiqFPuJJxja/RiGZ1xC5y2Mwh",
	"MBw7pp5Beut+nPqmwMeI2YtjRqaK3Qcwh8BNLEZUm7nObEJXtdrU4aVtCNTyeCTisQCpc5wv2QCwfpTK",
	"kdSI6l/cltX1QGQA2pVbL/7abv306iJjODtp9bv9/W5PUYa9y1snrf1ur7tv5W+NXHvdWwiCjn6D2TMu",
	"LJ3Ei6JT7m1xodRl866mLc+rvpVqScnpqWVPQRa7o5unOT1MetyRDjEyT7+6REWhW6gaNxEWFVttPQP5",
	"KwTBz2pDL0tccrQbScSoLbAz6PXK+EzSbm8nzkCv7HCaID52ZsbrTHMn9TdlHcdqOpZhWM97x7/2cET2",
	"5v29rA4r9j7ltN7zO0ekRQ+prYvkN2NJQQEJifanVoTvnhM8DrodDnLuV0l9qsQSNaL5SgrOpG/oN7Hv",
	"pITkks8RwQzRJRZoz2MxlWJEFfFY5VS03b0CyZWfvGpEnMxJAFNIK3yj/GpGNGsyc/xC3cgG6cZYEGEe",
	"J5NSNz4L1fp0WRA1I/kTBOJE3CBCFTECAnWhml5ZOAWAb0oR/RlI/RiUHo1zJVBLz1slCrH6NCJv+1mD",
	"g8hbH9Jz3Qq/03WlSNpuDXdPGmPs2/rW+Yn6u54opo5laALMTLW/66kSD9LsPAe7h52Ok6c4MN542v03",
	"x1IcDmupslhEeff+7v0y77kzmZdCkNqJsEQiTZvs5fnNlfuhdfe+Po/K1iddrvlNsaLppCo9QpcuU6Ut",
	"1JN72BxjxSclDhBl/pL3gb6UMXr7y+lld0QvmasnryOgsE2smmTjUurC6tOiNgQ4uaeNsMgSMebaJ9VK",
	"HJKp1WWDliLgHS+IhTSqXSFv0JEP2Rr8GxO/g89WpO9mbgi/IfzPQPjuZt/75KzTjcTyhSWWHSFBe23X",
	"5MSzqNNuRazo5cnk5kAYUbjNBIXmTmuFWV4xsZZb2icLkTxdLMlOmkk9Zv6inIxdE5KKTgvL3aybepYJ",
	"92vLX4uGCf/lmPDOWOfeJ4dFF+d3ifcgFCVHVd/nYq11hCtdZAwSWAjmEc3wNEMzr+F5ajMD3YPeLpIF",
	"r4oug10foLMNNzS2Gxob9oa7nocy+ZTF1P9m5alGdPlajC1OuUss1tsoVluyrl5z4TfM6LtR7raT69f3",
	"SqWVB9Ekc+LQX9Te9E1iQC2F0MJw5xpgytZzRrUNdUK7unuphMkYzQXRXBDfjuKZcNq9T0lxo1raaDVZ",
	"71DVdIR96ZbX6J4NNX93uudf7hnNaH2JR3UpJ9mV2leDjfSaW77hC40auIUSsL5bIlx8BuXRwV7nWq5Q",
	"IRO7lmnYRde5LxD2pFCcD6M54TLGAZoQDrc4MBVedPl06hkTm8eo5CxAii+OFf5pKxmLpflDcjyZEO/7",
	"VvLy8HxAXe86f8BbaHxuqc/UCPfS+5ZGau6F5l74hrS/PKvc+5TD5rqa4Dq636EymKf86/xqG8WwIfTv",
	"VjH8MsJK1YPdGqrfleK2Icn3miu7oeRGlXtAVW5JRlhSE+IChmGqF4gaTOMq/lxM42EUhkHDfRru830r",
	"DEny6jI5JYn1+54tHWqTD2rhcNmkt+BUqus9bRpmiIY3Nbzp2+NNe5/Mh/rmi2Ji3qnZQq/s2q6rMVQ0",
	"RPwdGyoSAaDSelBMdLuzGqyhuF5zDTYU1BgIHsZAYIiutmWggh/sziCwyg92LFgPGo7ScJS/iGC95zEq",
	"WAAmBWQta0CpMKArjprhkE0pqfMIf24Z4Sy3pW0EBruLl3qEhsobKm/khnvKDes7BUCncvZZvMrKmKAA",
	"XWFdbM8Gc8ZFxwvtsF+UGSZbuwc7vDZjNPyw4YcNP7yvHvX5mNsMc5/DmDH53T72bK3KFr4QPcfcRwZi",
	"VQrtjp+IHMN+nh5XY11uePo3ztNtglVdOP9zq7aCTWTD+DZgfNdsIr8c47tOj6thfA3jaxjf9oxPYt7w",
	"vJo8T8Eq4XYmvvYWCxRxmBMWi2CBhGRRBD6aE6xtnOpvBNSPGKHyM/JHfaoNa2xYY8Ma78EaWdRwxpqc",
	"kUUI5+rmAu8iV3QWuEuYx0FfOOCjAEvgGT6pWOuXYJQsavhkwyf/ynzS5KYURaVf9A/IhwmhgDDSW3Rp",
	"I22GkimwKcfRTGf0sKVgAzbVf0aYS13ctTuiT4guwXaLF21Tg4oIW1aNhESSuc1XQkSSVDNJb5vW5RWx",
	"N0NYjGhu1oB5OID2cpGOH4Stfgg+GgdsrBN52uo/ID21JuzNXB2jGRaISIHYLU1KvRVk2M1Xo30ZAb2W",
	"2LvRBYFH1A1QkDZUMLVtOhWOFWaKi5iiuhPiIREQT1eZxSMqZpiDb4DuSiCi2xmWoBhqCN4MUyJCBbK0",
	"8qArNWZ6ZWvWlRc2MCXwp65E5MZvTRZPtnovsvM2ua7/ygUHLBLsfbIV387v9nyQmARFPElyAnNdKzIk",
	"tGNqfLlaZLqT6I6o5lCnVxeKOHTSIlM0TGlooBYvwRV/BKTz2+rqeXYduqNkJhXwiMY0M4JOa4unmkYF",
	"UGFYV4bQ1/jAmiVqDRFuXTnpslT59WnvlQXcuQHb9pRoBmjEh+Y59aGUGEfjO2MV8NHApDx/7GkQsFth",
	"Swwqyh61XKck+dqopW92d2PaPN82N5qi0rA7or/OSADuHg/IDaAzk/JMswx1sRM60aYhQMszKOkCgklb",
	"SQnolgQBGnPAN4hMEJGKLyjdBYWMa0mIIkahbaUGYbJ5K9HIZF4bUfgYBcQjuiAyizkSEEBSmbOC/7gq",
	"oSv73wX3ebJ8EtvwIbeyy8KiRw0vanjRV8yLbNXdAm8vq3iYBklR0krBXJN9orLYoXdBp0/tKrchT7uM",
	"xpLRkH9D/svkT0I8hQrq179vQ/xm4F3Q/oVZ4lYFMXTXhvK/KcofDga7h1zEmRKl8TiAM6aV44bZbMNs",
	"1iaeyNG/MVlgFMXjgHjozatfugi9pMECcXxrWYSuYpRkdG4jpq2utsoQ8BGdMB5iKZwpFf3hsdsBCmMh",
	"0RjQhHAhVfM56FcabZ1MRt/uXaacAW1axk/1NKApj8iry8ca7tJwl51zFxGHIeaLtRTs6/pZ+htFxa12",
	"S+KpYkAtSx3v73Ygh+x90v9dyYmxTcqLQiK+MMM3D6gNe/j21I6UVpOsMDlaLaTKdm3B/kvKFTV8Qgzl",
	"bqf4fN251svfOZfXs402VZCG/F6pSBt1qnlifUDmsNmGJZ5e63cExrflDPUzBVbRadJoC/pMk+htl/un",
	"ociGIr8ZihzsTUgAQjKOp1BOdtZx1Pkc2fZd9ApkzKnIvAuqy9f+3EYcppj7AQhdFFguIuiiaso1Pd1L",
	"qpqzlIoHTzMr3/QAdgHF9obH/M8Y+GI7f93Nuzqpbrnn+60Ym4GyOqK3g4a9ff/sLdVtNFkqHoFSUnNa",
	"zdPs14qn1MmC61jHNcWRmDGJrlhAPFc/PdQMx9e142hAKKAIc6AS6bmuTecR9UHoqnZCYgld9DIkUoKP",
	"GEcQRnKh/SG7ws6QTKDmBoEoQ7EA3rFzjWhkG2gnTLVORjtmHM3VIuBCP6jAR+zJYGGSD+EgAN4RcRQF",
	"BHzkxuiO6DlMcBzIzA45k8a5QhfOM5pIoGu1G1+yYIHGixHVq/ZNb9c57fuE4nEAfrkNdYkhbp6rzHR9",
	"O1hnIu3X5hgNt9iZwaUxlFYaSuuxqGK5Z+9T5o/aGYAtI6tIAZwlyKfZGRqDZ2Pw/A4MnnXFgs10ikr/",
	"w1S7QMQ+RRIdskAEujivpSusocRec7k1xPUliUvheW2BeyOlN3fL1U+0q4nrQeX2YnE9stFXSvAmQhI6",
	"rZDbUUZg9wLA3Pg/ZTugajl/RDlEAdbvBTNAk7iwu2nbRdVC/oiWSfloWyE/rsHIthX4zUHfL0txwxMb",
	"B4zvSa+wzO8+eoUXYCGK3DlT/8w08NKJNbZT20Z66XD4tMA+Z5J5LBBt5OEIe0TzrpBIy9PsAzLyZphj",
	"TwJXfNMTXWT4io6N5fo91CfCY3PgybxML04gEROpFzRhOg6FcHTL+E3AsL/u2SW/g1rCmAPRplfZQ5g3",
	"z9RaGhtnY+NMULiE4JOfc4SvKGSMA0y9yhdMF81l1Z4AL4CjIVK9UdK9mtBW2xbT2S+5FTVPJDV5yPqe",
	"9gx3xH7UcT52x9Twnr8g78kTdIbr/JL/oeYbS264iveCZf6wsQKRxdydPBvkB2wooVElvqMnihxZVhF5",
	"mVCx9ylLH3UfKtZwg8xzRY4f/JKbqnmxaKj+O3ixqE2C7QeR3m0KhWqCLJTe11Fjr7lbGyr7Kp4uNiCx",
	"zfTR/N23SZ3AdfJwXI/g7iUc78DE3hDwtywc9453PY3H6CQgnmxk8Prm/G1k8PK8UE4qsOnjckLBfpoZ",
	"CSGXiwiNF8i+/SGPhWCyQuLkO85iCUiyEZUzQAYMutoh1m6IE8ZDgUIs/oiBY5/QqUumOQeu637ZhHCn",
	"VxdIcSPCQSAsUQBYSIRHdG8wRGcX568Qx3QKXYROUcS4zHR1Eo5Nz5lkwDQRVROOheSxJ2MOKBaQZtTM",
	"2U8x9ZE7RBQFWKqVuxWFCjcQFsgnHDwJvoKK2W9u+HrJJ9fmnxpcptmkGgvow72iuINorqa/oAUzk7HN",
	"sdSE7GpaLe0QFfbKy2xauA2lMTv6TqyUyVgNojcGyu/IQGnxupiGCwSivU/JQ1g9U2QpiWeMkG7KSzd0",
	"Y3ps6Pk7MD1WEle7USy+JsXC2GlLudWyYlHBqnqNNNFwny9tkl3DejZTipMrfxMLrO30g0BhbL0LCQS+",
	"KDfGFtPWtkL/DqyvDZk2htfG8Lq14fU+usUehwlwoB7oJHX2c6XKceFDGDEFMSMuTLBnPJo5hGxO6DRN",
	"YJ8O7rLrcRAs5h50R3QjTeVVMlLyaVUiGBbVJLGtldCjDnwSB8HCLBX8bkP/f5nM1UtIHEaBFWoTJLWR",
	"VupbxGiCqkoXeOU+WzymJnerjQkYUQ/TzDhJT0RM/KST+HVpCUJnZExk0gppQlPSfEwlCRCmixF1gyly",
	"SofjoJQCQHLGBGSoa/OkdkWiRh2jtp2xhoBSyiaw75cxCZPStoJFlIowtfhDvzZ/wL6fcIdGDGnY0MOX",
	"AhxskrPe2DCSnJhpylqRqt3FenVZwuftQoQ+62Oc3uC1xyLYtq/EMhY7eZBr0u03fOIh3/yKKbs8EfWg",
	"duLXJS/LlTyw6HFi7Wwv/2pKXY0oDgIEU64Ldpnkrk68N2ka24jQ/M8uhz18jAKPSHXDqqFMNPb9s8IO",
	"VlK/Nt4IX2U8Vj6/bmPw+Qu6MyzRdIatXS/9UjftXa5bhY9DQX7oTbM6ZNF3N8nc8iM29PBXogeLxnkE",
	"riSI0gt/71MOk2pnWlt3wWZscnnyuc5P13gSNFL3d+BJsAEptr9xAds8xK+7PIsF7LXE32tuvoaqv44X",
	"+o1IejO1cenK3eTVfq3QGtelu/uJsLtIT9YQckPIn+ele1tJ+XNUPhmk5U0a49NXanzSB9SwqL9mFZk6",
	"liQ1aaUFKa1gtPG9q7ruyGZkhmrQeFc3bePG9sUJdPW+3vtkPtS3ZRVTb86EpUe+tuM2RqtGKv7uPNvq",
	"CrXO/lNMNEtCbTnF9Jr7qqGBb61GoLtYNrPYlAiHcTmlbCkj7sQo09BcE0b9V5IR9zxGBQuAxbKQkDe5",
	"F3UVOjMcMuMZz+VNr8uz3JK2uTvtKl7qERpibi7Qr/YCXW/NC4BO5aykVm45QQsQgjB6D/ttzsjj6NoO",
	"ey/CTpZ2D9K+NmM0tN3Q9tcrHFcT6gxzn8OYsXrX7k5k9UJr7nPMfWRWUiWxL5lzHVE/T7fRGIYauv+e",
	"Y40KiNhl7uh4+rbsTLGEijvXhe8FCySwJGJCwEe6j8l8oh2SFHS0dXYME8YBmbAjhMWNMNlS3KRIMmTm",
	"1bJ3SrkPxyuu9aoXCCuJYEKmMTdFoLJA0Buqz0CubG8jbzzTANzaDLA6WLlBoCDw+fXMrB7dYoE4eIz7",
	"poZgclpNeGNjE/jebQKu8GUB+bvikk5OyLAgnMRf6dCrB+ZDVQuh6QrqsSA32lZ8x/Y1Y93riVqvuhFt",
	"GtHmixA9m8ivQh25ZhO5vTpynW6jUUcamv2LqSNCzG5gsb3N7xVITmBu9Inr6+foBhbb2fquzUq2evkW",
	"s59h0dBUQ1PfqmlPSMy/+DWq1pARj2dYaq024jAnLBbBAgnJogh8NCfYGBAkixBQP2KEyg2uXL3b5rZt",
	"OMNf7baVLPriVM4ihBGPKdWF2c0ljV4n5kDkYWqzGysy1UmbJfAMzSs2sQ3Rs6ih+Ybmv2+aFzMPuCQT",
	"NQTYk5OkysJvI35cIPPLCKiSo2OhSDEdC2UGq46gUr0rOpYI46UL/4vFWb3fUgE5S6F3mkKv8Qz8C6be",
	"qSDAbCxlRauaKXnKhlhU3coVhL65KbsQ7xe7Cb8qG7uhqB3d7M2DV2W+oFLqqk3EdQSDvU8liF4zHotu",
	"wgWyMVplC7ouW04jvDfC+3eQe+j+ZN3+DJK8DhvbiLbXSvIbEHavuZ4b2v3aMgztgnA3tKuVUUyJYX/O",
	"gjgEL8BCFGn8SjkQqe8bhVhyHKBxwLybjisPZnsjPMckMHWGOAutS59AcyKI+lIyEz2DgwB4F70CEQdS",
	"ONsdxZyzW/BVM0YBMY7C1DGw2n5QsMK3el9ndmX11hMBNgE+Li0J+kNp2igBr+pi1om4XX3JatELIgSh",
	"U6TLrGFdP0BP6haBOSAWEinBbyPBkLAWBQOPiDM/9rSoBGEkF2qYCHNJcIACImQXvQCfYF2YzRaSw9RT",
	"e4nM0BxkzCn4iNFggW5nQFEUjwMiZml9NrOUcq78Noca2yaC34mxYp6epjrvhmP/BU0UBgdQio+Ogb7N",
	"/5DRYUwVxYIHBVOcBY1jEvhJsUVCNR1JSxRlvgMxp0LTT763kDhUIhShlq+454oxoZgvEJauRsuIShJC",
	"26RhVC28gJgaitRHZxfOVZqpoclkgeAj9qSmYuLNkkIvRIyoD1HAFiaTYyENWwBsQ3KbHbotd2Mn/EJE",
	"8+3IBQo/3OG5UkEOk7KYbb95bw34btt2ZGPJv7v7fwEAAP//f1y1j8bJAgA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "https://raw.githubusercontent.com/unikorn-cloud/core/v1.17.1/pkg/openapi/common.spec.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef1.PathToRawSpec(path.Join(path.Dir(pathToFile), "https://raw.githubusercontent.com/unikorn-cloud/identity/v1.17.7/pkg/openapi/server.spec.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
