// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	externalRef0 "github.com/unikorn-cloud/core/pkg/openapi"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y9C3PbtrYo/FcwuudM229LsiRL8mOms69j5+HbxnFjJ91tlZsBSUhCTQEsAMpRc/z9",
	"9jt48SWSImU5iV2effaObeK5sN5YWOtzy6WLgBJEBG8df24FkMEFEoip36bYR1xQBmfo/OzSfpJfPMRd",
	"hgOBKWkdt67nCJh2ICT4rxAB7CEi8BQj1m21W1i2CqCYt9otAheodZweu9VuMfRXiBnyWseChajd4u4c",
	"LaCc678YmraOW/9rL17qnv7K925CBzGCBOIXcIHiJd7dtVt6CWK1cem2ITg/K1hsPNTDrHRRBcKqVcka",
	"Fw8ISjn2lUsD9EuI2KpkoS+wLxADU8r0ejmgtwR5wFkBMUeAshkk+G8oWwMeIFeiiNcGlAG4hNiHjo/A",
	"9wiLOWJg5lMH+v5KfhV0vf8MLxH5IQLHX3JpMTy4XG4ruXtEwkXr+I+WWlGr3YpmbH1ot8QqUL0Ew2SW",
	"2LSAIuT1d+2sAFddi1ZnP8bLwwIt+KZTihaFWnfRoiFjcKXW7CMyE/MNiCTxA3GBPEBDEYQC6F5FgNRf",
	"U0s182Ii0MygiE+h9wz6kLiIbURl2Rg4pnUxSqfHfBDMJkjcUnazccWmXfFao4EedpmbMPHE9+ktBwxx",
	"GjIXcUk4DgJThaCaDs1YRced3EgOcmboJAcHkzRaCtcTkqbnQtimRywF8DoZpzvvAH7JAYuAuLbirSAZ",
	"MPoncsVG5DTtigEYDfQgyBmNvgPgmrGK4JrcyFYgZWiKGCIuKltmtEIQNS8AbPS9JlIyNNtEHZpTz0oJ",
	"ww7zIMdqB9/Bqeqhig41sYutzpQjN2RYrF4yGgabFVXTGsxk82LYZkZ9EBBzxJYVxKVuVrZUPczDrJHP",
	"TxGTurwLBToJxZyyKlr11dUr4MYdAbQ9S/ZRNNWDbCwk+IYy0nF9GnofXcrQxwXE5GNwM/tIA0RggD+6",
	"dLGg5KOAsyvkI1dQVso3OBKAToGAM0UFCyjcOYAziAkXCQLBRCmzU8oWYKI2/+MS+iGatNoTIuYhB7dz",
	"RAAiLvWQB1Y0BDMkwKT1bwFnP04p/e/9MxeKSdjrDcbyTw5k/71/5tHZpFVEZALOtqOvOw17xMUz6mGk",
	"+lh76K3+IP/kUiIQUT/CIPDlCWJK9v7kEjSfW+gTXAQ+kj8ukIAeFDAPgEvEHMoRSP59zQrrqN/bcku8",
	"dfzHZ/vd9UMuEOtgqdwrgLaOW0f74/6wN3A706Ojw87wyHU70Bn0O0eOc3QEp+7UQ4etuw8S0QPkyjUZ",
	"duTJEQ9G40M08DrTI+h0hqN9r3ME92Fn1N8/GE0PDoeDsaOJpBI22g38yrDU32XHdcmjIKpMCUgi07S7",
	"RgHWQDllCAp074MwIAydcDDoDTvLfncw6o47syDsjAaj7uGo2xt1DlzkDfujYSsBLcjcORbIFSGTA3w6",
	"HH8cD1vt1iwI1QEzvJS00opGabVbC+ohXx5d66Tf67XarVfmn0GvJ22xJSIelZ0u3p+fnZ/I6SjXe/OQ",
	"VVOpNNzaLQ9zwaheOhFhq92awgX2V63jloccDCX+3Ege4EuDApPwk0IOhqGEkWGd8k+IcX0Ig2G3p7dI",
	"p+IWMvRef1IriBlK67hloCTbhgy3jltzIQJ+vLdngNx16WLPCd0bJPjeYqVNw71qMO4yeCuXhZkIoW9U",
	"STmn/QPy6mBejCrleCcocFUzhX2yl0S9T50Z7Ui+0DHQP19HvYwN+H6wI8xMr/QydHzsguvTy7QRGXOJ",
	"W+R0fCeHPcijxkpTs7wBkxlDnKfJ38dcIKI8YH98bkGp3CDvFHvqD61eV/1nT+Ep9nx0jReIhuIKuZR4",
	"vHW834tWIrGh1W4FlPpy4DmCvpifzpF7E/+6up4zxOfU91rHg7ayqNkS+tFw/V67JTJTjKTsyul+124t",
	"0MKJlu55anfHrb5edb+nVsNE6/iwd9i7+6BU90+rS0YFdan/ftA6nkKfS95im6km6quUIW7Qkr2siShZ",
	"5Lg/7UHvcNTZ7/X6nWHfdTqHgyHsoDHsDQ/G40NvKkEeqHM7v7Tie4mDk3h9R4Nuf3zY7fe6g14NrM7D",
	"twpsNY053XXMfRd4DeY+ScxNo+G2mKbxYyMjDVWzXHwzFPRl9Scz6QOrTx5RurYWrArzDrvqPy11amiK",
	"PyVIXmLkYFiD5s0mqqpQsbcrhvoDiaZvH/opr5Rk3v1x3znyRrBz0Ot7neEUwc7h8NDr9ND+cIS8aX+M",
	"jlrFpxa7fuRg035/30FH487Q8wadodsfdo7cHuqgo7E76vWmgz7qtdq11WvZQ25HrVpfUqnl/Kzd0seD",
	"kVrGEnuIvdUb9y7TLQ6lDUNDpbRJiKNPYk6D1H40h4n2aZmlgm5d3KwjiqxfWStdaSx9EDH07WPpFz2p",
	"Kqy88KRSLqIve0526o7yYj20RRz65kBc7Em7rH8gT0PBvT9QRhhDrlm4VU2sJP7cIqEU7VIm3+UI5eqH",
	"lgJ3ZQGQ9vetn9vXkQZf9Py20NfvdeS5yteW51yHmW4+6q/BUh8Pqe723Kqz1txzk6LhSx+UnLPogASc",
	"2U/2eOSf9M+pM5j6cEmZorYjeOiO9w96nWFvPOoMvSHsHHmw1zkYHxx602HP9Y7keevYjRodDEWnLD1j",
	"T19CzNIYYK3ro4FRtpUBWHWypNl04vvUNZ6ozy1EoOMn/JGp89dLqDFNu3prpBYVcsTO1Dm3zgcX3Nl/",
	"f/PzrxdLZ/F78PttgJ3BUe+3Qf/mzYzOfr565v82mC/Pz56PXuPhp4s/Z+FrPBy9uXom0K/zpbv/y+zy",
	"z+Hs58H73m+rI+rsX/Tc2+D2t18v2G+/ev5/9t/f/r7/f+a/v3w3Pn/1duX9+u4n9+WLP+HgBfn9P6/H",
	"p/hEnL/6PXB+oT+26hCMRLgakkw2T5DH1xJdj41MtuiCyUzBUJPWlbq4MQSm+Os6VX1Yd3KtEUTVRVSi",
	"AQnLp0ID9aT8Ghl8HbH+2MigwekvjNN1NKAYpwkM+JyKq91oQNte7NXYrVnwdtdLKlLSjIDJLAOL/ICA",
	"ryT3+LzjwgfW37d30dV2xGnK/gmtzN6QNxiN+kfg5OTk5HT/4m942vd/PzvvX1w/H8m/nT8Lse+9If7q",
	"moVcnBB3Thlw6WIhAV8DX8oPtdK9eGFwiUYbHVf+ldBET35/wbCGChUZbRIV0P7Y7Y0OYecQObAznI6c",
	"zlF/OuxMx9Opc3S4f3A0ctM+We/wqO85016nB3v9zhBN3Q5E+7Az8g4OpmNvfzgYOq12i+O/0Uv8rHU8",
	"6PUigJ/6kPM6nl3T71pFnHxukany7zJKBf8rhHxur2lqIFf66Dcjk+mQxpuvok/sCm+gENCdL+yTjkgH",
	"1sK6t++Mpo5CCIlI/XEHHo6GHedwetAfO6535DhKCuce8EMcVN3LtPjAVGQSDyjhyESHEE599EYFtb81",
	"X+qdnmnJW8etnzEJPwETFgJG3f6o2+v0e4fjzs1yAb53JDP0/rfvrnqDDlx442GnN9r/AXw/c13w/TsV",
	"jAL6/e5Q9tKxKf3/fzDo9oY/mD+3wcuLd8D3wPfy32eYhAL7XCGl7v4DGHT3D38A/+uo3zEDXr2+BK8p",
	"ASfhDAxB//B42D8eHoB316dg0BuMookTy+0e9dWK1Z/6h6MfJuSULhaQeMDHBB2DZ2/eXH88f33y8vmP",
	"ew6lYm+58DEJ/+5k9yyP+8fLk7fX796dn/3YH8OjEZzud0bT0UFnuD/od+AYTjterzd2Xdc58HpDwCgw",
	"p/KjEKt+8perHgggwe6PnX6rMtakjjgfZ0wT+7bBYogicPPtCnF5qNuhSMj8RKSPXGMoUHfm037XQ8su",
	"4S7UkT/H495hb29J3I8+Fqg7Fwv/3wEU8x//e/+FoDeI/Pf+mTseoumhgzoDdNTrDI/6w87hPjzsjPsH",
	"g8PxeOgcHPRqQ8dsrxw8XDdKwwd9EogR6F8Y99I2ELJeH3d/ejQ46I87/anndobOgdM56o2RVGF6/dHQ",
	"m7reNPEcjFLl1Km20ew687fqY67CMZfQxx6wfexFDlc71tbXthtNMnul12JKrrHaUP/ooNfp9Tu9/nWv",
	"d6z+//dWHb9bBJpZd9id49l8gRZd2O/1uv1Zt9+bOVWi8NwgfGHD4c6JQD74D6IEXPpQYBIuwGF/3LsG",
	"31/drHx4g37QPXjreKgC624k949C+Xw6wy70T2kogTNQIRuUrVrH46EJ6VOTcIGJK8Dr88FIaZnzFU90",
	"6yei+05en7Xu4mH2B3fVMcCcW/nBm0bqoE0kJUY7O2vkPZNg/ZPOSdej6H9Dd6HoXgIxjQuD3kBKh85+",
	"/7o/PO73DS7oQBj9wkyyFB0XY5EEjofTo8H4qLM/Rr3OcL8/6DiHXr8zGnhH+95ofOQcODGShMRDU6zf",
	"tX1BxVFdvEs+gsks2kj0R+QlcZQGiHABdQyRCrpWMZpTGPpCwkz+5ZSSKZ7Jv7+cB+7qmfzv/PzVW9/d",
	"/+Wn7BKdI/dIAuNgOB56/aEzPTxAo94UHgzG+4c9uSPO5z+h1cUCWhajvQuqO+wfjQ8O4eCwPxgPjw48",
	"Bw6GzmjoHo1hbzycwtbdNnqxCZ6O91oDp5MoCr1y1DZtUQq5V9tJtAazG8zeCrPrxr0XonUc6J7WR5SH",
	"aEdInULa/U5v0BkMrvuD497wuL//+5a42YTLJ8LlrcXY79WLnS+PcW/bt9LHn9VP+sUY9FZ1w9+LME95",
	"IcUcCuBCAhwEQo48QAkQc8xB4EMxpWwR4+MDKIsNRj4VjPxQCyU36K8ml4DCTcgQkMNAgR0fgVss5jkI",
	"mo5TforqQBQk/9V1AUQ882KuCcDfNgA/SUr3elXSGvT25Tr7+3qt9fWbB3iRUqLGl75A4duR7h8N7Ta0",
	"29BulnY/bEO8vJR6jXxOUTFPP+xpDPGvYIiXv35JWulJhD0cDNGhO3Q7o8PRYWfo9Aado6PeuLN/pC7Z",
	"x31nui+RzIdqr/3eYHhX9ijmi9rWEcIVIWvuA6iniJ+LVcfs71EiaIqf7hK5dvB8aouHNSXcE64QA/t5",
	"iNn45hvG+cXc7THObZLzqRtD+8sT1dEbLvqAXLQ2blbSQtP8VGOp3uAZEhD7D+RAP1Bo2Dsejo6HI4mG",
	"2QUKGgCOXIYEkAO5SFo5gNMFup0jhmwapHc/bUThiuFklt/edG4RFzWRaoqgCJmOJLKX1lF8QWQgJT2G",
	"2n/o2oud3xdHy0T+pETL6uIzfWxFJ++p78hLBpKpvFNRyrgEDjyYu/pbP/9Of6cYYGze+0gccyDl5Gwa",
	"5T0wbmzKryBsvsXHz8WsYfMT2AaNHh8a5T/MvacDLqEDOXD/yJlORx2n5x12hu641zk8QqMO8vr93nB/",
	"NHaGsLX1Q+DtsbWxB58m0/uwFSZVsNTSCJUjRJ+q2dZwwC/CAbdE3CpmXD7q6jeAT09ip1/PfksY+5gy",
	"PzRZHB7utW/KkTSHkvxab0Mi8UahEV5CgdT1ZXTh2B310heb/eGgOxj1uuNxt380rv2CuExxWnsD33CJ",
	"hktEHRbNi/9d84AFdOMYgyk87o+P99Fxf3C8PzwejVvbZcWlt4hdmRDCezKXhzXoLI+pzJCepunWMKRG",
	"bfkHqi0f6jGKSoa6aphkGE/UMm9YRqPDNDrMw+kwdXlTNV9MgjvlpqvBqPEkfjVP4q4zF324X+oigwub",
	"kKooZxFGvDzZVXNj9ySw7N75sUqez27Ih6UeC2+HRoaPazB05P89e/7y/AK8uXx+IWe9fHv+/uT6Ofjp",
	"+W/q64Q4+898hyj4sN//cyO8P59L8Jw8ezlaOot38sfnzuIo/P2XE/t/z+T/vL6V/yv+nhB3MBO///rL",
	"6uL63ac3stXpqVi+HT17gU/+M/7Xu5f08nYvfLn3rn8G/4Uv+v7Fq99+/fvm8Lf55Rv07vbkZEJOfjqZ",
	"/336/v+cu7f+1S963DqjTkjeuCfPT/3f/vxt9unFn89fD/+a73P/4Pxq4AXP/r76dPP2undxvTo6/3k1",
	"w/BkQsRfg6NXN89/PX82ZaNf4Gzv7F9D5+j63QUbn+//+q7nzZ0315/w88PR6Fqu8NV/3ofwV7F0F8PZ",
	"7/95Rifk91/7vrt4wc9fvr95/ee7/uvrmxkcvB9NiAL184uzwmNo1UE3ebjFeHWDUlnVVJKvnzEXu5N/",
	"GznPmrdhAX0/L/rJViF35SK7u9bkTYYuNbjVk2txFMig7yMf80Xr+DC+0FIKKZny5b6cbMqXSod9SFUo",
	"5yg36kRJ0FqRpf+2W2z4tqy3dFa2p2K+fdUccUmLJLUQiQ00JOJNEIXZMrSgAgWUieSLtnHH/nSkMgjJ",
	"TtoyTDY63lsQsSfXkckEXWV/VSh7CyLNyZV4dDQeHTnDYad/0JPL6U07R+7Y7bhTzxk6Tm84VPgQcjjT",
	"tAUD6GKxerZSUaj93sH+wbB/OBjKQ9Bp8rwToclj3On1FXkM4hRUIZcUpvoeDYeHR4PD3qg/uKvPPt4P",
	"JOFX4ho8nV/xSd5VNZyi4RT/EE5Rm1GUXBwl8q/WqMgMXRcFAnlJTpJXP13nD51DDhyECLDdACQeuMW+",
	"ryqVh/4U+778K18Rd84ooSH3V90J+Y2GYAFXIKC+b8LrTWV4OcCCEiwoA1hwkMQB9VEzE6AReEIEBfAW",
	"YqGSePgoqbTSADHFJ+oCwYGeyVG7HUNFjKksLZioFIkfDbhabf3lYxqgFpgO9VbAdJGshUEXfVQMc3Tg",
	"uP2hd+R4w3F/2nNG8GDgOYf7vf7wyBkfwOpGSQ0g6E3k4Nbb5Hqn+sGEHl9nhFRgaQPKzMHq1h5FHBAq",
	"z4kIiMmEwOjodf1lMMXI93jdw3IpmfrYvedR2VEKzgjGCGoyxCDA4QIByewB9FWaGoA+YS74t312Zhd2",
	"v1zvBxIq5oi1QchD6PsrnQJngSDhcq8rMIdLlN513XOaUuZgz0PkfgcVDVNwUiFHDLgMqbxn0OfAowrt",
	"og1E6BYwvMQ+miH+GKjtFnLgIYKRB5yV9UP9bWhNnxZcSa7rQpVny1mp3aYaSm55g4iFh+SoKYhwlwbI",
	"poI/uTyPiFgBVVIw+S6G5IQQ5CLOIVslYKkTfCFgX+2l8yjVgIjK3UGgr+s1PJfwuR/m6MsHA+l85DHc",
	"TFCgAeX6EC++Zew4ISAk6FOAXCl8KQMhmUPiyU2oPoC6bsgY8rrgOoEjEAgGCceICNMOEm9C5Fceui7S",
	"edok0xNs1QXgfKpRDCsEkMfrQo7aIPAR5BKBpHoIsACQqwIUnIe1+QOh4gUNiXe/QyZUfJzKYQpOOCGS",
	"kBcz9Ug6KRb+LZ/4OxWfIVF0iokHYsFUF97yV+xdMioU8ljJsB34U2zmY+IB8VyI4HhvT37vRmbkh3bL",
	"QZAh9nGBxJx6/CMPA4lCyFN9EPQQ0646bm0KmxgcES+gmIhuwihVfCsziN6eNiKmWGXEQwuIfW027fq4",
	"CoCZd4BvAkTOz4B+3hpqBVWnRhQUeJi7dImY4ttSgmmQ24tTcDtHBMyxEJjMJgRKLqtnBBFcgKZ0zCX1",
	"howYfiZp1lcEr8aAJCsaNB/AHCDiSmsOKYlAtfh3IYnXNqe3csjEEmsjn6m8bnIGbodz0Y2XnlXbgZ2c",
	"vIXLfrc/7h48CJ1mN5JvjqkbrKjmASZSHuqDnVo1WV/wAzNeXXiGxJ4muicDlZYc5x+1qlGkDaeRU0vN",
	"b1pM5i3YKjd6x0biS4sWfQqkOlT/DAJGlULk+OhUA/5+Z5Ea8aPtv1GwactMKozmJfgto2QGNNJ9y8d0",
	"HeuNXrQZuQ++IgK68vykbeJSxpArgBNqXQQTLlioXjip1qEVkRPiqAElCJEHvFDJTY4WUOKC1nx4N3GF",
	"rBxeFy+u3g+ubEqM1AIvXlwBHiAXT7FxEAaICYwiP9uV8bNlO8pvwDjhorfuDqU+gsQUXNE6uBRdiYE+",
	"xA/jnT+RK+R5FEVsfd6UZwXo3BrJzKdmLAkWpB6GgSmjC23o6cjjCXm2AibndhtQ4q9AAN0bJNaafsej",
	"iZTuPoUu+o6D80tgUudNSHZKlbhAjmBzFgHwjiPtv8EcUH0HqXrwxEza6+NqdROouuZM2bE0FODq4uQa",
	"qDdx3Va7hQVa5MGGROuwfie9RgOjbnxKXDCT0tD8ATIGV+ogUhl+s1OcXr4DyRZySETChTzhKBkwlC3G",
	"w8Q5x9Ola7Ksj5+qx7KGjXHFnfKOOTvNoGM0Uh4yZkqj5CBhcWGU7JJVBZg8d+O7tz8rhcMw6jnKDrp5",
	"E3LsvPVnKp7kYsobm5NirdbJ+h4kV833mBo8Oz/LxS2tzJT21E6XTRvFUYWTCtst5Rq0cNtpyqpRUCaP",
	"inTEa95C9Jd1GCfvq3alxgkosGvV9td2gsR9zeaiKUpkZI8jWqsZKe9QEt1rQCHLfcoWmGp71245kCG5",
	"shx6+3WOxNxwZT21tAl0NU0PeUrb98ACunNMkugYCbNUcZyc7TCkXEwLIBmkTkmeijhB3VkXqEToQD93",
	"b6+x0XVWGYQ8n3r0EBKdTy/f8URnKaJmiMneuiJPXm+o7rVkbxTM0QIx6EszSAo48PJZ/mgmv3vZccyC",
	"UCNLXKSnfHbdSs2KC6YNMCFIRcnlnikBKmA7KgMKQq7df/Jw9TEvQi6MdrNSXhwyZVBrViFDb9FU8mBd",
	"T2KqnYsCshkSYE656G5Wa9QhRTs2YM9I0WLyKGVVUUGiimzJ8JwcbjQLwte65NL6bC8v36UQMxcV7QDq",
	"Cr9kydnBqi8+WmL+8vP5iJzOaq7mTizLUNJ1qPIQ0rRIENXLy3ccwCXEvlK5paqOELF2x5urfFwtQnoF",
	"k82ovth4QLknk6mYlbdB2yS7w+9dyDz+Q7zT/IXZ8gwbz++9bpilENPf7jBBK+m1t9NnlUc08SS5G5WQ",
	"0rMl1VJTVaKtKojlqaSZSkol6B25/y3SgbhvZUxP17dZx/bU95zFFC5i9UWUChNycuXSIOlfhV5d/cKu",
	"emsNIzXAPQGVylpaddVShb7Sad2SERv5+u5MGX2J2kU4EQaAPIBJiXlWJVOcCpDJwlF1TyxuExzjLa1t",
	"4/kSsZWY64gFEDW0DliCkMeVBz8kbj4vNsWucjUauEA2wkE1s9xW/6L9yvlaUrJe1joSOJCj8VC5fz3k",
	"pYYDU+zna16JsKrsiJf6k1UZMGLK5tYKpPV7ppWM3Cm0wqJemOVNo+8HdXaXTXOJjXPp8l+5xtjzSAU0",
	"0dtghghi6SkSZJM3+GUi6r98fPM+QM0jaFQ+yVmBOZ5JBZ0yRbDaX8xzJ7SVy7IzveOIRfx4ut253JWQ",
	"x68MC5RrSifKkSnv3hfhw2xLsy61nXvz3niUNcDYO/4AMrhAAjFtcOlYS81Eivnxg3DTrEeylCkuTFhc",
	"fgmwR2C/q3VaiyyOjNzcRTfdhBXRmIXQM0XVc71nqg6yqaamo3MfB/HE+9qedDJjbITPBgvnPi6TCma9",
	"WsPLIIzLsm1s/eZKwTOnhFpp+Ge2veT1DOfB593bc13lXdVUUZxdQWrK6EICyFwKHav+OSIkW7Gtwp7e",
	"p7use2Jxa21cBbAKvoAIxIVWja6rB/BUXQtB30feOiLY4nsbBjEXtm0b/GJMpgjNcoWureFXzYjXkf47",
	"NB3N1gqB9+Yql1WbWFkyA3zFBVokXXI56mlUbrDMwSdbaXVV+fRuIROrPQdTUgA5W7GwHAaUn+l2d3FF",
	"w009jDvyLq54uKnHT7rdXaIkYtlWTSO9UQ/xG0GDPZu7J4+sbHBCdlBD0pkQ5vhY1AQTXYpx0tosuc1+",
	"I1BFUI7XUIgqBTy3UK5/s+zVPpLIbuU1JngRLrRLV7aKQyElz+QowTDLHFK74N+7Z7R22/djtiYDRR6n",
	"1GU0v+PAx1Pkrlwfqaj81E2nrQhnXw6pH3VRz7YJt8z3NCX0q+LJv+PmHcA6MnK77kpa3Lo7QPcvBMv7",
	"tePKutyhALKrct/r25IkNikNPwmoZCXU5AVNuwXJqhhEpW7xmnVOq3rldNHfHHdc9sKgzNXUybialM2u",
	"r5kiL6y6WADq9oIj0U7FFcujd+fIC32kbqicVQBVlAckXiJUIGvt6Fy4/gpQYqLioum97EVGAtRSlSAu",
	"+tki+qXOAJXrJI+IQaWJkuegLlP0CMkjv4xoI07vciVoECR+LCKPYDmMMs7kcOjzy+XQhjSk1DzZsVU+",
	"4Kabi+TYdZy5iSXnIE9c1uMCLtCltYTzFvJT1FTfiYPXIRc6rFk9QAFnF1f2mYkUnSpoxae3iKmwZeDO",
	"IYOuNLPb9vIFUAbmq2COCG9LlsKEwiOkXjOJOYBxJ9k0upgknppXgAXlAoz3E2NLieGrIjUSRAsYVawZ",
	"77dbC0zsr/2c00hWTHwV17l8P8g9l2S1RBBQ6ts3Uq7stM4a12tdfpbrk6JQV8hcaLmYXFtC2q0V1Uz0",
	"3u9t7J4tv1mvd16lzhqrz/NaJYH9s6lWKnGwCrRtddMkImr0MWij0K6j0M5HQqKPxBn12OYWc5TFWh86",
	"+vYqgy8BlH3lCv7vH7Dz94fv/+jAzt+9ztGH/+8P88MP//6v1gZUsrtLVijNv+fL3aNNq5DkYcINWu1W",
	"6AW5bCpv8jpgzdExUwVki5mUjbaRvOr0/OwtT8adJQKJkjNFbCwB7e//ffz9v48Hoz96ndGH/xn80esM",
	"P/whwf0/f/T6H/6tftT/+8Nk0v3h8/5d9eZ73//7eP+PXmfw4X/+6HcG9sN/VYk9y6uVm6smeT4ChuQk",
	"R+K6cRec6ZA+dQ8x7inJe316GcGDKzzFHIQkCqtXjd6dJRoZTNXkdjgebqZfazVWrRebIci7uP5v1REu",
	"qUL0u7iKQp7MtihOmUhtajwa7Y82bSpOoF9/YwlazKqgcSYUPbrZgQHBhw2s7LWqXVxZZOhSxzkEF2sZ",
	"NaS7BXUdOGZ2byc2g23arjnm6hxb7rpINkZVpaueZlpIJytHl1yRx2CvrkXlnnAOf1irRF0Y50WBTvkK",
	"LmUXYPuA5aBCTI/d5qbTeT8odnGnz8cmmHgUTu68LW7t7S4cTIu9N1OVnqH6csyFxucM+BJ5GHKvl00I",
	"t1jTAxzkUzKTAiPfpZWoFV6DV2R5XrS6dRB9aFfFnbV7gA3ALoxmSQ7/uGJGcnGh4uVWpu8ObrlyVrMJ",
	"3NLA3xCwZtWQMi6bz/23Y7gJFfZOybJzPUI/h/9GuVhLGK+9dgcQ6Pbg/LIC0433XQHUBS40iVLaMNan",
	"lnqUBh2pLcJN6P9QnCQJuxo6R6WL8K/E1qK1tUs5XPb03qlcMpuFps458whF5k6EJS9h4HlcYDvit8l2",
	"1mndnOhZXGYrDwGjKlxRRdnQT7kD49Jc+ilWrkVtsedsk5fOUt/5GS95BhW/2IqcsFWsT9PrMmH35BhV",
	"un7yvyK/gWV5t8ldQ6LygrmLQE4ceRParSVjQRkIio688GnOtyytE3vamiSyY+Q536P4Zt12s4zNlgSv",
	"zALtxXblcFGzJBtayW20qC02XuTl1t+jwLXE8a9hzhcNlYpW3s4CsfTw0tXQM89PDbEma6YDF7Kl0iAM",
	"HKJHmcoNaXiNJfPT87O3EynpMwF+6rKTh+4cQK6CPaO0pMoNZFKxRHdFE2LjDmV7zdninDOZoe2NTXdC",
	"XlAGzDvnts4wsjcYRouDyY3Z/WgXutzHYDQhugHiIFV5ftQGPtL5bOK/9weHnfi3wWioUOTs1elld0KS",
	"cFZXY1P8CXk6NUISXpibmCt9ryRb4sUiFNJgnhA4FYjdQubl3D+m69hnT/JMJenmKpXCQoI9c06CGlgg",
	"cx2hwgCFTrvjoBnW2QJyTrcLwAYoT4hKR6hBCiKIas3oFjEwh/40M3Qb4C7qTkga7CrXRDy9fUL7fbf3",
	"gwLXDAp0C1fg+27/Bwm7CbEI1DHT6usVFcAMBeABdOWGKQjVk3cQtYqum8zuJSy6AzN/MdYszMXQTJ2h",
	"ZBCQTEgSZKn2Kc/fftKX2Stw+ynEfmtWeVl65Dqlon7ADhXEN9BstHkFFom9ExIF6occbaQndQWRxMMf",
	"ByOd6Kds5T8ODttp8jrUyUTMatbWoY7asouQG1RiSApNTz+iWd9OO4lL/XEnSbcH3Sjh0AIKd454ahf6",
	"Hnga+r7lB/roMQfC0iqP75kzYJSLJTRaL4NkhiYEc+CjqaiFABnGnyL4EhafFnAFsVjm4W2hLrPB9Fob",
	"oejZsX47v3kY88a+YBQeOgSJzaPodkWjLH1YKJvjAPX3P59cpEeIDyQGcpm/kURS9Nu3ljLbua9uuJ1b",
	"Mepc4FHMpuTNRYJEGyndIrUqnf2z4GnPljogAGcrAhfYBQvqRUquYUgTkpEBWGcAi6+7lLyVXAUvkL7r",
	"96gKxaMTcktDXypGS+ovVfIIJaA1nQAHiVuEdMYkhuQfGIWeC1UaTIkifEI4BYhwqR/Z4FIfshkCiNBw",
	"NldbWdGQgYAKncnQxqapTL0T4oXM5u/z8VTf8cmdqU4VXtWUPNwxaVjU453aR1VNx04qWPp1S4UHXiyj",
	"HFcyqBJdsoSTwdskTNo5enwlh3SJYVVMlE/RlK3rc4677cDdnF5DMWS/gP2rOMLGjqZVdtPVDccanl7r",
	"3S3Eri9ucSe5wVfgA1VIPQHoYqes3cYjcsdmqHV71aLozd9jVLcqPPjbBIlvyAO3M3LONXhqubc2pg2o",
	"nWAo6QwudlRXuCHYdubia4HooUrOrOoRBnZCpY8WJHaSI5Tk0dGZc3SeptQbEW5TgIpVYDLmecbdpAKo",
	"oXujXoCp676CeX+Knslk59UPSlRoe9KN72MSfsp112vueoYExH4cuZsnp2bJq/vUhWTkl1MR9ZiDSSJe",
	"WD+DyRCNUrMvSpJqycm+44lcwLqLfq+kXt9SwsNFIidn/htruQ634E19aqbM8/pEEHM6FWzBU/vsu554",
	"2jx6SwK9CPN1my/Kj7fRJ5Nb2VpIrQ2yBo/ztftvEZ3eOoymCErLildb/AvbOhXnXmfjCcLZWaaLaA/F",
	"AHuR2OZ6ZXqdesk0SYBLV/bQ/jdp3em0F3k+ciMMi7PRnU/tyw9pIxOdfsy8aElMaGx2viZeufZ3UoIA",
	"nyuTPWNqKkr3Q64i9vWjL+NVxosoRyuYIybZjnYdZ+eUhN1Rj3XsQx/etq9QOIp80IlZ5YKS71yUTwsJ",
	"tzshm6M/1oBWfHxPgvLvSfNfl9q/GKXamk8lAijy2Wdld3xFm2JP7RbHi9CHouANkh64NPjKNKmsUyXQ",
	"NkehUkZyqYkhG+Q5yz+JOQ02PpSKk3HLcVQ6208CzGmwC59ktLaKSrVddO6RRz6FTdEfumV1+CsI54A+",
	"Vee9iK3YRjoXz+PyWqU2uDXLSYMp9NFmMKkwoKwV2Lb5j1V6IQ6gAG+uzm1Ejb6KdugSdSfkfAroAgup",
	"wUo0Oz0/e2tRz0s88dAV2Xp7Pf2CXIXh6HtHSFa3Ur51J0Q5fikTKt2/chk5UU4NIyv1EoZRTA/X412f",
	"XgL9OESLPjydkHhZmNu1mBAgNUuOQuBij9WM+vOSUVcV7LU4SivxTKEyZsgzvZSdarz6yAZLrTn5ohUl",
	"xqyEXUUxYEY1y0E0hQswCPxVZZ6wjtMb+YMFUv7NgkQwZZBiexmksVEwODVJNTL8W722LBktGVdW7+WO",
	"uv7dCgPeqp65DwpL2hfvQa1kDRht8zYwn/QUiVr6a0vqWwceIgXOV0Q8ezUfL6A+BFXIQv4MqWiG7edY",
	"f5ivHkHJjVWikvxXQQ/KhbdjwOtejF3wtkxSPnkMJrtpLlK1AZ7qe9CI79sgjBTjrvlCjjLxGuZoSwv4",
	"KVyEC40eZetSyYeJ64ceAnBbZI11tjpv2b46nzcFgb84p89/WrauKm0kr81ebrXk2gs0dZIz1zlqqI2A",
	"LQsRycLzEVxd5O5tN4rsdlEjmSHu9xoNZo+k9NXG/d6UbUbdTeB68gZS3cv9bOcdXPHnreer8aGoYvuW",
	"nOher7Q2YdWDkFjlq/170G3lR1MZaBZf0D9+vr4bjl54Wf/YAbQb8Gy8pk6DiW+pYRW4OdNL2XxzvZPF",
	"FF9j62v9wvpI1zn1vwrTthit+hJiVmF5iXlP1vrb6Ia8gksX8SsKKAR058mEYIJWqaGUjyOlK8o5I2Xk",
	"LUJf4MBH4PXJ6V5cDQ18r4yYH0AgoaECLaFKSsNUAKgyPaMIVZOWJN9btn4gyguY9IqsZymFbmH+MDnC",
	"65PTaKElA2VLvMgVbQG6TY8Zbe6eqEibBFkNRC8/t01IX/Gp5ZYL0qfxKX5KXvquXHe9NC+kT3RYfOGb",
	"04gwo+flNpI+V/nRiUC8h3izbocuRo5ipdlmUX1MyrJcc10dWfXZiWqsRkqy922skaJSdhkdIfc1Rx2G",
	"mlroJlrbXtitw6SQ7ouNCUNOG4wIXV6qSDU25baMX7QkSbBKtFk0is4junkQkoitqMyTotDBXD6zeZgc",
	"/rSm2GxxYnZZIUfszJD+emUL+cWmf7RhV52oqkkq1ippTlEG9Eg2DgSEASXAhyFx56kcms5KoI0oH+FA",
	"fI6JwyihhgJTMIl9BSlvA5uUtNS5mZ/KVPk5VcWRvJwl+kWILkiS0GA2Y19xGhQ1ZCyVKo54Vwi3cnee",
	"0vweVWqp9K7uYdesDVPDg6f7FrjuctP9lqNetsNdu6p34vwsoc3DWJcvKrRzKtepODQ60ZXRxUrPUbrj",
	"go5n9/cpFkmOwhMzrFhuqYwZWAClGFuhAZZTNLo0S3t+r0r5jShT10ipB2QbdMbtRMT7QUpImNQopazi",
	"6ema9T2yptfO9M38Y6isyoHzs9KC3ZXUziKFrsw//GhVOsMZqpxygpeUqk+nO9aadEiRbm03JtEKYA5m",
	"dIkYibOGKJrpYIJVBmXiQebpWKIFXOk0yXqi9oRA8Pr89XPjWFG5upk7x0vUVkG0u1DVStH8fs76fA6z",
	"G2Fax6tTGc92fXEQ0Fut5j5xXfVBrki+iHJT4+JFk0TZjYuuNv14XkSm5enWKnfJFYuCyOMBxT0BUeEy",
	"RTWr6copv66odG2yzbQl9yQEBnxOxROs5Zfe2vb4sD7M5op+pk8VwymnChP0PKzTLl2mgLurspNosdSR",
	"ZZnnJWrtAUNRDTpbSy761wIsfyu5rBqjCmh9dfUKuHFfAOPO1VE9X1KU4H6haMmVfEVrXBUmGCpaUCGx",
	"kZJJHpcfqHzr2xNjhXGre4qKBttZxqBSrNmkcFZMdbP9HNUTy1TxFlXC3Qr8sJSKa5HMI/OIlGPjLoml",
	"sESiKvp+9UpaxKzgKAULuQCQuHOaYxBqeyO3UPgJ4JjMfNTxMUF2po62NQXywOmJtVZu0KrCk7NopoKt",
	"5y+C2DLoeQlkiqucW/6fqG9e5VVcNGDuGnUyvxPlHV4gIn7GXBQb6mfqN8e8WY7M2Ki3fghoBq0sM7Nr",
	"iH1rOfIyp3EuJm1aamalBYF/VXNZJFynub5uXg3620O+dDsLGhKhs2iW6nbrdWVz83CCixdXQI0JqB40",
	"equpF4SirJa57FV11Z7xfCzXY5tsaUVDA6yFm/GRTcJeb9+dUy7UT+hY/yGAYq7/cB9HzflZgXTU3nlM",
	"ZleVfMdbaD2X65MU36jkrqkE8059qLPdVDD6DNRd2aWORpyYqUQNTrSyz0CKH2bHadFNmVCdATaxwOQj",
	"bTLly/1WW/07zH2PnbPGPNGRneCbTgGQ3tP28nt9mE2g2XwlEEAmTTsf80VxgmeVtAayGYpeN6kKmnFC",
	"YwA5xzOiC9NZfjMhrylD6XYuJAAvJGUgECCmGAZxURecJARXyNGELDD5PrG4ts2mfH7JLbuxLCGVBvcH",
	"9aCqUqUz7bOuSzkpmsh74F8xP3vqoO6dpN3uqJ060RI0ksvfiEXfqfxL61Ls4sXVJpBdvLhK4HrRKt5x",
	"OEPFojY/w0XIk1dMsQhyVjrjQybAFAbQxWL1bJWbbkBQAX2bVtn3qVI+E4PFRWeJGA9zK2drv7B3knNR",
	"KPACcQEXQZz9Sa/+FnLgQy6MU9lLziT/0JE98yRdyJFXsBVoFIFYQuhtyS61tpQNiE1BsASnSsNXLLp/",
	"Wx7D2DXw5dMBf8XctToSJT1wTElFlzYJLlg0fpqrbTHNlultM2uL6+XnoGslXm+Z14d7iOriJ68ZVa6m",
	"BrdRedusObHonvcxPuNLH1HlcJGo2y7iRVJrKBWhG1SwhM2+jX1uQWDwfW0l8oPk/i/xs4zMrCbdEvpC",
	"xeUlVIu1vAdmlelhy+FbLyVwkeF9HyinPDEPVYJnM3+Ny1tFlni82xxFAc6qnlhaDVtPVpHhrdH+Sw+u",
	"5D7929QFarCcLWRCjUUa96qWelfqyjZfkPxsnxYlO9hLYZ1gUFpcMwaJiAqG05QaURauRnIHlhxNQkWX",
	"IZlTLgpzv2bFUw0YOAgyxF4jMac5pPBMfQWC3kitmkHCVe6NhW4eOxzmCHqqGpxDvVWr3forRGyV63jY",
	"cmkbclo4ZevkiTINJn5MGnK6DBUiXkAxEZW9O9vC9n7HhBijOe/3XiKCGHaB+gwWiEsG01bX4lBgacer",
	"uj5U4tcg5w1X/qgnQCDGkRlVnx1AnwJIVOUKo2C+ur6+NE1c6qEueC5/1hWyHChtIdPwzUko5mDQ7Q2y",
	"KXOcUKjmemxT4EkeTsAwEpBFMkdOoF2uJ5fnHFD9wGwO5QSUJ/OOOavEfOmKiSo70kfDBVs2+sOAtt3S",
	"dPvRQwQrO5FQ8XFKQyJ/dimZ+tiVvTROfZRfTcRzS55khGIfF8jD8KOx581sH7WA+igo/ahKd6g+AaNy",
	"Suj46KNLiUBEaF3BwZ6HSC79qNV+TJ1X9vjeI+ZIoBh0APqrYyuAqBHy2QiDLvqY95TrHcF/hQioBiBH",
	"PiZES7mdYYG9vo178vI4F+XP0EH+e+iHuTJRp8hKJFT2ZXOgqpy1E1mwlTEvtxfZgZL7Jpi9gyYEEw99",
	"0ka/jVaVmK8IDQqBmJzz//7R6xyddH6Hnb8/fP/v4/i3zsfuh8+99rh/l2jxw7//q3U/til/xd6l5XDW",
	"AMgrMobI+RmAYi7P003KHlWNhi4RW218K5CUXB8rJp7fgYy+a7c0e/1omPzHiAIfiINHRToKAXqdkiy2",
	"XQ05zqXJ9jA7UUPnJx6x+2kXHGbOukqAf086TjoiSizYytEm9797uLfLKsEvU46le0SJVIgMsTuwpaCU",
	"aEytS51qjKfKV8G7Nc9rs7PhIY6qIpasH15Fb+AujqxWHE/uadnV7OSgbO9XCPpiXmTtSyDMVQulein3",
	"P0wZMVafCskNobek1W7p9lLt99CMQU/xBy3o72kBrFmRa+tdh5uU2dD3paKYgZjiv7cMmyTHmfSJZRrV",
	"dRIHEp+ipI9RtU4YzvTlmro4gwujgC8oQ+qZMfqUX0WDmOoTO6KPXG1IanhwtkvhLOAsPwhE7ubDdmd9",
	"mRtikEuqUbvquBogZcNkwgaSvyrs9VDm807R+cHZowQHdt+u+2A+r2G9jyRMr3FR8RNVKjDFA28hB6of",
	"8rqVr9PmGa6zY5GdYmrfUJxKzjoysNhWNkgWdz+BEGuExX6VN+dnp1r8GMtHWutpVptUGVNOlF16qUzs",
	"fO5CF1BaL1GsfCJGCiz73UF3vzshlwx1GPIRVEEUxANLyDCUfFpuiFAB3JAxRIS/ip1FGTNuOZl4/5pM",
	"uol/7muqmWJB5hFC/l3SsxD7XmJ38U19ZHyHusC3GU0VAV8EyizVTsgJcTCBbAWgAAYKiq67AJyhJfIl",
	"RwCOnIcDhpTnzM6nMxGvRwsWFksyi1DZZK1NWWjvmFnKR7IrNo3bOieyOdrN+TyhYkh2pntaJwWM9SGt",
	"kRLubarNPyuInFXhxLdzGlWlz/qj187DBozXFQdmgurioChdUKj9TNHgBU88dIXeCjs3UR+bd25H3LBz",
	"mN63Gb7qvtcTHWVAXkEYqGJt9h4EYJ7yURkm/WfIBUCfMBe2EjH5Tli2PSGQrNLak/JLxEp/yLVn1kEE",
	"TbEwicejh9b4b+RNSLQEUxouWY1oK9ISMDd3hYAzsIBBoNbJHCyYZGTGF0e1304XsUMcgTlcIlWxPUAu",
	"hj5YICh3OCFKVJEViGhSMX75X0wEUr5n2STkSApXRDyFQzqdnadyyZnw4Qkxarz6FEG+rbqb8vqqjhUU",
	"aCYFIwJYVGWgJ5YA5K6LuWa+b1Miqfpkr58FnFXnj2rMD/c+wk2BGNIAeYirFok9aypGIkfIlfLAaf+N",
	"ugw5CZNuz1znKIsffmGGeHyvkL5ugqmRFC/w6e26c/SUemjtj++Y3zpuzYUI+PHenr3I7pIb3kWhxJjO",
	"LeJi2CXchT7qunSxp9e/txzspUaK3HSt488SEnJt9xpdjZCKKlSfdOl8qYfkpISQB2Uv5mMXsuQvjIYi",
	"oaTYspOYR3JeamEpYtQ58M196oQk6bILgCkByZAqOgWmIXE1hZpAgNiVjz4FlGuteY5nc8SAL7WeqFTj",
	"hCiN4tS8JZWrje8H2pql2gp1PHQ4ElzXq0oxXags/NS924SoL3bLkhax8FFcv/LKbP3k8jyhoxy3+t3+",
	"frenqmtqNG8dt/a7ve6+1kjnCrn2urfI9zvKst3TTv9O5H3uFHupzyWL0k4Kpd6v3z3LJUWnJ5c9QyI/",
	"MET7OdQw8XEHKuxMe9BWim/nXZvLcaklsnNPXWaKX5Hv/yQ39KbgEkO53wNKTD6iQa9XxESidnv3vzt5",
	"a8ZS1PCpM9fXc8eChUj+TmjH8plOsvC+biH77MEA7y37e0m/Jd/7nPLqnt1ZCs1zSbXOo29adAEfL7DE",
	"fEX11mBzGVLtoJ+6qtLXWckYwQlJJwWxdpMpa2cFakxFJkkewJxqios0fdelIRFcKhae9VnytnZ8ySFN",
	"lHhsNwYML7GPZihOFwvSq5mQpIJimYVUNTTGOZBjrv09UUIMU5NVZYGRM+K/EQcM8xuAiS7GiJZIx+3C",
	"FJx8BG8KsfwlEsrWjo/GumPl0knKo56L0icBft9/kzz3N6lTj891K+SO1xUjabs13DFdONB7q69407P0",
	"dzpLSCynUKSXmGd/p/NEN+zJSUY7BpkUZYxAX99ZqtiIFBuxeKtsxnyd5I8PUv9P85s7/fJggYS6Zy2w",
	"N+Mme2kec2k/tO4+VOdLpLDm6mtIoKTjKK0xALbWqM3FlHIXOVDyRgF9QKiXceLqWkeqwGl3Qi6oQJqF",
	"qeBDaN6xJsv/5/hsQIBYFA/YBpAnCRcydWdvVAxBs/VdA8Q6pr5rIT9QoWDJJM61CT6qxboNuce10Rti",
	"b4j9QYjdSvC9z/YGs9FMvrJmsiMkaG/sGp14EnXarYDmWfX6ERKAgKDbRAw2yZRHTjPIS8o3cshLc1KX",
	"djUZHUnxpmfUWxXTsG2CYxVpZZiaieFJMt5+ZT1r1TDefwTj3Rm73PtsMef87C66ckV5j4Dl31PPGVTR",
	"SLJKeBog59TFiskpJqZdi2kK0wPdg8bOowWvqyiDnZ4edF0UiCwaNkRVk6iGveFOJyFUvKAh8R6nxtQo",
	"J9+K28SabJHjeRtzaUtG1WtEesN9Hq+9tp2qvrlXrIw8iHGY0nb+oW6jR4kBlWy8RMW+nRp1MR9P+cZq",
	"mnlmdfey8qIxGonQSIRv2JCMWOve5ygdXyXrspyOd2g6Wkq+sMtrbMmGdh+5LfmPu+zSVlwwX3FpzRbz",
	"jV2ZcRWYRq8R4g0jaMy6Kkr95m6R7vAFjEEL+1lUrS2fuWaLtoKrdMUb6AouWR0ES8xECH0wxQzdQt9X",
	"PNeWAVI+MpcSwagPJCN0JPIpNxcNhf5FMDidYvdpG23rlXsfyHa7Sh/wFhZcpuL9Pey4zEiNIGgEwbds",
	"zaV5495nni6OWM2y20ToOzTu0qSeKeXYGHoNWT8RQ+/r6CJlF2obaHxXhlhNAu81Erkh3cY026VpllEB",
	"Mmp/mMMhdB5QXoFLXIZfiks8jAEwaNhNw26emAEQ5c0r0kSiR3NP2VVhqyM/mIvCZrTbgjXpQrL3ckro",
	"IRpm1DCjR8CM9j7rH6r7H/Kpd6d+B7WyK7OuxtPQkOyT8TRE8r3U/M8nsd2Z/Rvoq9dIuYZkGgt/Rxa+",
	"prLKpn0JA9idRb/OAHasKA8aFtKwkKeqKO+5lHDqIxqKXEKuI+7FXKUMlsMBPZ5OuPmltYDT1Ja2UQnM",
	"Lt6oERqybsi60QzqagabO/mIzMT8iwRyFXE9jji3Bde343spd6BlfmbYr8r9oq3dg/9d6TEaBtgwwIYB",
	"1jaNvhw3m0PmMeRQKp7sfczW1mnuJc4ryDygIVZmo+74Fsdy6FfxcTX+4IaDPyoObrKHqqqZX9pU5XQq",
	"GjZXg81d0an4emzuKj6uhs01bK5hc1XZnICs4XAVOZyEVcTb9IPUW8hBwNAS05CrIvA0CJAHlhjayuhB",
	"qojyF+KG6lQbRtgwwoYRVmaENGj4YEU+SAMAU4W1EOsCW5UKMZsfjiElXpAHfCgQS3BFyUi/BlukQcMV",
	"G674z+GKOvEizytPoj4AD00xQQACtT+bE9Gk65ghOmMwmKv0FqZElE9n6tcAMqGKPnUn5DkWc8TALVyZ",
	"kq9YJ1QMGF5ggZcmeQfmUcbIKFNrXKyLh+4cQD4hqVl96kIftbO1JL7jkrlIOHvA8amjslSaCjVIuHJN",
	"0J3bWjtzyAEWHNBbYkvVsJxksekqVW8CRK4EdG9UlbAJsQPk5MTkVG6bzLhlfIkaGLrY1hS7gPvY1VVY",
	"J4TPIUOeBjoQc0bD2RzczqFAkn0ukDuHBPOFBBlcQuxDx0eAEpN9U/WyGynPxa8LYaqz3upSyODJVhc7",
	"Zt4mW/M/ME2+Ofu9z/oH+ScPCYj9PFYkGEZLxAH0Fph0dPkpWyZLdeLdCVGM6eTyXNKEStwTVZXmSC5e",
	"IF2KTyWHhZjoompmHaqjoDq97YSEJDGCStUKZ4o0OSJcc6wEfW8IO9VLVEYfurXV5YoSvFcnubcGcGca",
	"bNsToB6g0RSaG89dWieWrnfGHtAnDZPitKgnvk9vual4J6l50rKdoqRjk5YS4lY4mnzVJieYpMxFd0J+",
	"nWMfWZHt4xsETnWqL8UmpAzHZIp0+eDsDFKRQP60LRUCcIt9HzgMwRuApwALyQukUaIr2ou51FoIahsF",
	"geus1FIL0hnHJgR9CnzsYgEwATRkgCMfubZYVgnPsQUj1/a/C47zPHsS2/Aeu7KL3JI8Df9p+M83xn+m",
	"PlzSvEemtvKlbhDVxSzVuxWpRxaJGXoXtPnCrHIbkjTLaDwTDb039L6HF3CGSshdfd+G2vXAuyD2c73E",
	"rao3qK4NqX/zpD4cDHYMsIBRqSBDx0enVJm5DWupzVo2ZmRIUbv2PEAQhI6PXfDu7c9dAN4QfwUYvDUM",
	"QRXYiZITtwFVPlNTAAcxVYR/AQW3jlDwl0tvB2ARcgEcBKaYcSGbL5G6UdH19e3o292hFLObujXkZE8N",
	"muKnbVW5VsNOGnZyf3bCw8UCstVGkvVULSf1F0m2rXZLwJnkOC1DDh/udqBm7H1W/64li9gmF0Qu1Z7r",
	"4ZvbzYYTPB7KjJKjpCgzlwbblbX0r6k2VAjP0HS6nRXzbScJL76EzK5nG9MoJ3/2vZJsNrZRc/m5Y4ZQ",
	"Y7cCzq6Uq5+ybVlB9ZR4ZYQZNdqCIONscdtlwWlIsCHBb5cEB3tT7CMuKIMzVExnJkrThvyY9l3wFomQ",
	"EZ64q5Pi1XxuA4ZmkHk+4qrgrFgFqAvKSVX3tLebcs5Csh28SKy8LvTvDcJ2zQP+JURstV1kbP2uVmnL",
	"9vywFRvTIJbn837QMLOnycxic0XRoWQKIKYta6i8SP5ZMpEqCV0Nryj03WXouH6yKd31/WCTa65fGdcb",
	"PL+v6d846AocdNUoK18+731O/FI5JWsR/cV+uCQFvkjO0DjaGkfbo3O0VZVd9TTd0ki1WOcF2NxwYRXH",
	"jjk4P6ukwW6gu14juxpq+qLUJBG7shpYy/ZKCbHqmU8VNRVrk2EFktpWs9QruF8+04Y6m+vlx6u9Ghq8",
	"j/bq+pDzvFi0OLgsfgVmxanp1DbvT9RL3Lj0NaOCutTnbeDCALpYrPTbF65es9kLM+DOIYOuQAxzgV3e",
	"Bc+JnEQ91GPq/sfD3KVLxKJ5qVocBzzEQi1oSlWkPGbglrIbn0Jvk9c5vYNKSoAFUV2O+hD+nlO5lsbp",
	"8w91+oAYFfOIPPqcInZJFQ70IXFLL23sGxOjYvtwhRgYAtkbRN3LiWu9bT5t/ZxaUeMkrsI0apQM3wm/",
	"kWf5zJ5Rw2z+IcwmTcEJNvNz+kNFL3NquBJfc5Yh1LYJkti6E5dzesAG+xvr4NH6tlNEWEbSRTrD3uck",
	"NVT1cG+g/YSfO0X9P6emalzdDYE/Old3ZYJrP4gqbl5pl5Nfriq+ifZ6jdxsyOrr+Lxr0FQ9azIt2upU",
	"/Nqk3IbVKOxemu4OXOANxT42Tbd3tNM5XEqmPnZFo01X8bVvo00Xp5WxEt9knEoJ/P04sQoANpUJcFbA",
	"Q1MY+gK4dIF0/jgY/Y3RUCAg6ISIOQIaDKpiGRQgQGxK2YKDBeR/hYhBD5OZTbu3REyV8jE5pE4uz4Fk",
	"PJghDqAAPoJcADghe4MhOD0/ewsYJDPUBeAEBJSJRFervZhEflGuPP28Y8ogFyx0RcgQCDmKc++lHJ2Q",
	"eMAeIgh8KOTK7YoWEjEA5MDDDLkCeRIqer+p4aulqduYvmZwESejaVyVD3S/YU+hEUH/EFdjIsOT5aER",
	"nVV0L5ohShyLF8k0UjU1LTP6TtyJ0VgNcjeexEfrSTRYnE+xOfrO3ufoTqqaz7CQoBPeQjvlhR268RE2",
	"pPvofISlpNRurIRvyUrQDtVC3pS1EkoYU6/RFBp288V9pxt4TT2TNpLodVylptN3HCxCE7iHke/xYq9p",
	"PjFtq8HvwE3a0GXjIW2shCoe0vtYCXsMTRFDxEUqkZX5udR4OPfQIqASXFoVmEJXxwUztKBLTGZxoup4",
	"cJuBiyFOQ+ai7oTUsjneRiNFP61L+2FevQHTWio08rSnoe+v9FKR122o/UknrM0g7iLwjZIaISZYKFVf",
	"/hVQEqGn1O3f2p8N7hKdxNFE00+IC0linKgnwPrFm9XgVdp4TObYwSJqBRRxSe08JAL7AJLVhNjBJAnF",
	"wzEklXwExJxylKCo+umv8jSJKk5nM2MF/aOQNUDPK2IMOrdlCVso1FAq8YR+ZZ4APS/iCI2W0fCdByjh",
	"NaiTm1o7IaJ0eXHuSh7bzfmGcVGq1+1e03zR2zG1wSuXBmjbvgKKkO/khiwvrXZDsk/NYFd3Y/lEVpwc",
	"dlA5PWMmtHAtWyN4FnkO29mvuoTMhEDfB2jGVCEcnYLRqtM6t1obYJL+bBNJo0+B72IhpZscSsq3XeRu",
	"HKwlaGyu6b+9F0XpFJiNI+Ufcs+fIeIEH7vKfKmauirVreTyPydta91UA0mU3U0qq/SIDQ08dRowqJtG",
	"2lIiKJTqe59T2FM51dQmKZpwdKVJ5io9XXPR3ijSj+6ivQbhtR+5zqzvqTeJx3ydeSOp9xrZ1pDxV7rA",
	"rkXD9Uy/jEStc6m9UQ8NqxLa/bTSXaTBaii3odwHug7eVvP9EjUGBnEhgcZj9C16jNTpNAzpn1OsoYr7",
	"R05a6vaJi4PUlqyy644cPXqoBnXvKUsfPpTrsZDHunjc+6x/qO4KyqedlAdIjXxlxm18Po3K+cjjrKpq",
	"jNZ9kk8iGY2xmD56jWxokP6br3Nl5UY9h0eB5hUWk8aWCthOfBoNkTUvbh91HfpShW/PpYRTH9FQ5JJt",
	"HbEn5giY4YAeT4fJ1pWGp6klbSMazSreqBEa0m3k47cjHzd7v3xEZmJeUNGxmII54hxTcg9nZ8pBYgnZ",
	"DHsvSo6Wdg9avtJjNMTcEPM3pOyWU+YcMo8hh9JqgnUnuneu6/MVZB7QKynTwDO+T0vFr+JtNH6chsqf",
	"zruVHJLlBAZ8nkewV+ZLREBAUOBakWlj7VWY/cMSc+lCSLyCasRtR9vKzjZ99Vj3uuhQq27IviH7L2L0",
	"cjoV34RgvqJTsb1gvoq30QjmhkKftmDm8xu02t64fYsEw2iJlJfq6uoVuEGr7YzaK72Sra5s+PwntGqI",
	"qCGiR2PDcgHZV5eScg0JdXcOBbiFHAQMLTENub8CXNAgQB5YYqgoXP4OEPECiomoIVHVbhth2vCBpy1M",
	"BQ2+Ok3TAEDAQkJU4Vctg8G1pF1N5i4kJqejJEqVqlIglqBwyRS2IXEaNBTeUPhTonA+dxETeCqHQObA",
	"BEYld0Emrtu+RnsTICKV4pBLwovHAonByoPkZe+SjgWadeHC/0mh9B+2NCVOY9CdxKBrYlX+ISkRSigu",
	"+T6mpFXFVAlFQ6zKhG4JZdf3M+fi+mo3EfZFYzdUdD/Z3URjFSRxKCSnylRbRfTvfS7A7IpR/qQO2Scj",
	"/4sWdFW0nEYZb5TxR5cQ4v5E3P4Cmrl6jFCLkjdq5jXIuNdI34ZYv3rah11Qak03WBGJFHjdTTmUHB+Z",
	"zsoMnBD7XlQ1BZMpZQu147LbrpARrhxl6d5cwIXkK5gIqj5bD5yDCWQrAIVNzjwhAi9QWyeMkS1cH+ti",
	"KMQDp+dgBoXOdLxEDE9XAH2CrvBX4HaO3XmU4RnzCfFQ4NOVzjmTz27eGxBsw0NqoJhJc21mayzYr0uZ",
	"EvssatgM5BZPE8RpcePD3d3d3f8LAAD//1VYM3lMgwIA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "https://raw.githubusercontent.com/unikorn-cloud/core/main/pkg/openapi/common.spec.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
