// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	externalRef0 "github.com/unikorn-cloud/core/pkg/openapi"
	externalRef1 "github.com/unikorn-cloud/identity/pkg/openapi"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y9i3bbRpYo+iu1cHpWkmmSIilKljSrVx9ZfkQnsa22bKc7ocerCBTJioAqdFWBMuPx",
	"Xfcj7hfeLzlr1wMPEgBBivIrSM8kklDv2nvXfu8Pns+jmDPClPTOPngxFjgiigj925SGRCou8IxcPrpy",
	"n+BLQKQvaKwoZ96Z92pOkG2HEkb/nRBEA8IUnVIiel7Ho9AqxmrudTyGI+KdFcf2Op4g/06oIIF3pkRC",
	"Op705yTCMNdfBJl6Z97/OsiWemC+ygMY5dqOEngfP3Y8M7Fablywa4guH1UsMRtq5/WlQ9jFRU2OUreq",
	"WVZ0tzMz/XMLuvZ5TP6RELGsWdgTGioi0JQLsz6J+C0jAZoskZoTxMUMM/oHhtZIxsSHuw86iAuEF5iG",
	"eBIS9D2hak4EmoV8gsNwCV8VX+8/owvCfki3/29YWrZ/Ccv18rslLIm8s988vSKv46Uzem87nlrGupcS",
	"lM1ym1ZYJXL7XU+WSOquVatzH7PlUUUi2ehWYFHE+5guGguBl3rNIWEzNd8AOAAPRCoSIJ6oOFHI9Ko6",
	"SPO1sFQ7L2WKzIgwM3McPMQhZj4RG0EXGqOJbV0NwsUxd4bkwjAGoBlRt1zcbFyobVe9xHSgnVfnRlhZ",
	"2CaQOw9DfiuRIJInwicSMGRC0FRDokE4O1bVveaXXgKFKwhRAmx5ZKw9yXNWRNzK0yyOuPORJozecMG6",
	"fsiT4J0jru8Wg97gQe/Bu/hm9o7HhOGYvpNELIh4V5g4KNndHq4jP2DVnawdwE4XEwv+O/HVRui27arv",
	"Ix3oE16FmzMobmUPF2DHqjr7/GZ3OnZBpkQQ5pO6ZaYrRGnzisNPv9ce/vq7JchsE0KaV2BWi4tumJ2v",
	"3g4QFBa1h2s0Q1XdYm7ZO12iJH4iqFo+FTyJN7OztjWaQfPqw1wZdeczLY4T2BUD3jRYKjSrW6IZ5g5r",
	"0wPYRcn5BRHA2vtYkfNEzblowm5fX/+I/Kwjwq5nzcKrptp9JxUjmq0VSZrPBbHkbFAgZz6PIs7eKTy7",
	"JiHxFRe1ZEEShfgUKTzTMB9h5c8RnmHKpMqhA2WaD55yEaGxPoG/LXCYkLHXGTM1TyS6nROGCPN5QAK0",
	"5AmaEYXG3t8Vnv1tyvl/HD7ysRon/f7wGP40weI/Dh8FfDb2qlBK4dmu2LTgYRJtFmVMs+ordsPsfKN2",
	"ALjAj2YMItVDHlCiN+LepZfmA/zJ50wRpn/EcRwCJFDODn6XsOgPHnmPozgk8GNEFA6wwmW3uiBiwiVB",
	"+b+vCY5d/XsHzll6Z799cN/9MJGKiC4NvI6nb9k7804Pjwej/tDvTk9PT7qjU9/v4slw0D2dTE5P8dSf",
	"BuTE+/gWUDAmPqwppcNnnv/g6PiEDIPu9BRPuqOjw6B7ig9x92hw+OBo+uBkNDyeGPTdSmz9RVCQR6Dj",
	"+munT1SLRpil0nRv7SadwHUhCFbkzhdhjzCZJMNhf9RdDHrDo95xdxYn3aPhUe/kqNc/6j7wSTAaHI28",
	"3Glh4c+pIr5KBAzw/uT43fHI63izONEXLOgCoNhLR/E6XsQDEsLVeeeDft/reD/a/wz7fZAtF4QFHDo9",
	"f3P56PIcpuPS7C0gjhvnIIh2vIBKJbhZOlOJ1/GmOKLh0jvzAjKhGODnhghGQu/MCylL3mvgEBQzlVJx",
	"+BMR0lzCcNTrmy3yqbrFgrwxn/QKbpIJDKYADzx7StA2EdQ78+ZKxfLs4MAecs/n0cEk8W+IkgfR0oi6",
	"B83OuCfwLSyLCpXg0LK43ln2BxJsA3kZqNTDneLI18009EEvAL333RnvArHq2tO/XAe9FZn2zXBPkFlc",
	"6VUyCamPXl1cFYXijErckkk3nJSQB7hq6pMcbaBsJoiURfQPqVSEaVXdbx88DPwVCS5ooP/g9Xv6fwca",
	"TmkQklc0IjxR18TnLJDe2WE/XQlAg9fxYs5DGHhOcKjmF3Pi32S/Ll/NBZFzHgbe2bCjNQRigcN0uEG/",
	"46mVKY7gTS3p/rHjRSSapEsPAr27M29gVj3o69UI5Z2d9E/6H99qceH98kpwxX0evhl6Z1McSvIxa6ab",
	"6K/emaf82INemQh+5h0Ppn0cnBx1D/v9QXc08Cfdk+EId8kx7o8eHB+fBFM48ljf2+WVe4YWND7P1nc6",
	"7A2OT3qDfm/Y3wKqy+CtAVktQk5vHXJfx0ELud8k5BbBcFdIM/CxkZAmulkpvFkM+rT8k530ntmngMnn",
	"OCLmYYUJvJOe/p+nb41M6fscygNEDkdb4LzdRFMWKlPqZad+T0/Tl3/6K1q7M29wPJicBke4+6A/CLqj",
	"KcHdk9FJ0O2Tw9ERCaaDY3LqVd9apm6CwaaDweGEnB53R0Ew7I78wah76vdJl5we+0f9/nQ4IH2vszV7",
	"DT1gO1g5Hsws52ejZj8bHullLGhAxEuz8eCq2OIEZBieKGJPnLxXcx4X9mMoTLpPRyz16W4Lm9s8RbaL",
	"ZbqKUHovz9CXD6Wf9KaakPLKmypolz7tPbmpu1qRdt8ScRLaC/FpIODUH8Bt6HMfDLUQJohvF+5YE/cS",
	"f/BYAk87vMkfSx7l5pdWOO7GD0BR5bh+b5/nNfik97cDv36nKy9lvna8522I6ear/hwk9etB1f3eW3PS",
	"Wnpv8DRc2XfdgMDTXa8OpA8KH18Zfav91CtopntczA5iQbqGwHcFwcHSA8FESjyDbo/fKyIYDrWnAkFO",
	"H4cmZMqFtg7qxToFCgWzDA6s7g7rZaVjaJeEK0FiLEjgfdzOZrB+LOfmSjdJJBIrKqdLhNPF2t2iWfam",
	"wQyfGkNgzirMUHjmPjm8gD+ZnwvAPw3xggtN5k7xiX98+KDfHfWPj7qjYIS7pwHudx8cPzgJpqO+H5wC",
	"ojmnncYdLCktiNhWkXGFqSiinlNrnA6tlKMl76aT5eVVMPP5VgX4wSMMvHAyRXAB8cwStpim07w10YtK",
	"JBGP9D17l8PncnL45ubnX54vJtGv8a+3MZ0MT/v/Gg5uXsz47Ofrh+G/hvPF5aPHR8/o6P3z32fJMzo6",
	"enH9UJFf5gv/8B+zq99Hs5+Hb/r/Wp7yyeHzvn8b3/7rl+fiX78E4T8P39z+evh/5r8+fX18+ePLZfDL",
	"65/8p09+x8Mn7Nd/Pju+oOfq8sdf48k/+N+8j1ui0RYsBDTPocfn4hm+NjTZoQtYxs5S1LrWZjyLYPph",
	"W8eqt+vaxTWEaLqIRjjw9uO3gwPbsVdraPB5+KmvDQ1amP7EML0N65nBNMOxnHN1vR8OaFeL6ha7tQve",
	"za6nXW7tCJTNVs6i3KPjM717ct718T0LTrvrRrfWgBrM/oks7d5IMDw6Gpyi8/Pz84vD53/gi0H466PL",
	"wfNXj4/gb5cPExoGL1i4fCUSqc6ZP+cCgb8MHPwW8FJ/qY0cEir9jQzYmJiBzwQmZvK7PwxroNCQ0OZB",
	"gRwe+/2jE9w9IRPcHU2PJt3TwXTUnR5Pp5PTk8MHp0d+URkenJwOgsm03+1jUMyQqd/FBJThwYMH0+Pg",
	"cDQcTbyOJ+kf5Cl96J0N+/30wC9CLOU2KnXbz8jDH7znT67hP4Jzdf3vBMu5s49tAVzFq98MTLZDEW4+",
	"Cz+xL7jBSmF/Hrmgn5QHNo91/3ByNJ1ogABAGhx38cnRqDs5mT4YHE/84HQy0a9w6QWvXBQGw6o5q8tV",
	"uyvocLik78/90BpFO/u52G2tnvkLNv5k9+UTQoTUpm+FoMEEyzRuKrtl96ULP5RcM2ELKjjTJDW76Vjw",
	"ILG6lTtqVIv3ag4kw9uR/adb8i/3zxakvnjejVkD61hYuLL7cYbIriw74nu+va0Pb1uAN/2+k8jtG2EW",
	"aA/VnvXpljFnklhXNiZ5SF7oiKKX9svWak1liI33Mzi2IevDho56g6Nevzvonxx3bxYR+n4CDETwv0N/",
	"2R92cRQcj7r9o8Mf0Pcz30ffv9aec2gw6I2gl3GkG/w/w2GvP/rB/rmDnj5/jcIAfQ//fUhZomgoNSE3",
	"3X9Aw97hyQ/of50OunbA62dX6Bln6DyZoREanJyNBmejB+j1qws07A+P0olzy+2dDvSK9Z8GJ0c/jNkF",
	"jyI4x5AycoYevnjx6t3ls/Onj/92MOFcHSwicOr7o7u6ZyB5f7s6f/nq9evLR38bHOPTIzw97B5Njx50",
	"R4fDQRcf42k36PePfd+fPAj6IyQ4srfyN6WWg/wv130UY0b9v3UHzZW1hSsuByPbxAWWOQjRCGi/XRMJ",
	"l7obiCQizLklwhoTRXqzkA96AVn0mPSxcVM8O+6f9A8WzH8XUkV6cxWFfwef4r/9x+ETxW8IAz/o4xGZ",
	"nkxId0hO+93R6WDUPTnEJ93jwYPhyfHxaPLgQX/r07Hbqz8eaRoVz4dYVfpzq5Ld5YScptQ/nJ4OHwyO",
	"u4Np4HdHkweT7mn/mADb3x8cjYKpH0xzQbaca0Vos42urrN8q+C8BQ7tCxzSALk+zuos9Y6NxmLXjeap",
	"sSb4YBChekOD0wf9bn/Q7Q9e9ftn+v9+9bbRVadHM+uNenM6m0ck6uFBv98bzHqD/mzSxGXYj5MnzncX",
	"2JoQ/ZNwhq5CrChLInQyOO6/Qt9f3yxDfEN+MD2kdzbSXsA38LKmfschn1Efhxc8gcMZav8yLpbe2fHI",
	"+h/rSaSizFfo2eXwSEtm86XMdRvkXJHPnz3yPmbDHA4/NocAe2/1F28b6Yu2bt+U7O2uSfAQjvV3Pme9",
	"gJP/jf1I473XMd8zWBj2h/A6dA8Hrwajs8HAwoLx2jPhvd6Z/XXpgAQfj6anw+PT7uEx6XdHh4Nhd3IS",
	"DLpHw+D0MDg6Pp08mGRAkrCATKkJKv6Ewpa2eQEdoWyWbiT9IwnyMMpjwqTCxuFR2we1Q/kUJ6HyOuYv",
	"F5xN6Qz+/nQe+8uH8P/zyx9fhv7hP35aXeLk1D+Fw3gwOh4Fg9FkevKAHPWn+MHw+PCkDzuScv4TWT6P",
	"sCMxRiOnu+PB6fGDEzw8GQyPR6cPggkejiZHI//0GPePR1PsfdxFlrThJ9let4DpPIjioB60bVtSAO7l",
	"bi9aC9ktZO8E2dsG6VSCdRaVU+RHtFZ1T0BdANrDbn/YHQ5fDYZn/dHZ4PDXHWGzje3JxfY4aXzQ3y7Q",
	"pz4gp+MSVZx90D+ZCFscLLeN1amCPPiG1Bwr5GMGkb6JJAHiEOVIJYpDrCDUMYPHe2AWW4j8ViDy7VYg",
	"uYF/NW0MbGJBwD4RY0UhQc0tVfMSAC0GVXyL7EAa0fPZeQHCAhtz3EYL7RotlEelO4XAecP+IaxzcGjW",
	"uj1/cw/hczVsfG24nHwz3Ncb0+Jui7t/ctx9uwvyylrste9zAYtlMQqxFcQ/gyBeH6qXl9LzAHsyHJET",
	"f+R3j06OTrqjSX/YPT3tH3cPT7VjyvFgMj0EIAux3uugPxx9rIvg+6SydQpwVcBaGq35LcJntOza/X2V",
	"AFqgp/sErj3Eeu4QBVhDPfGSCHRYBpitbr4lnJ9M3Z7B3KZ3vmAxdL98ozx6S0XvkYpuDZuNuNAiPTVQ",
	"ajb4iChMw3tSoD/QYNg/Gx2djY5+9dYXqHgMcYiCGCcyn4CUgySPyO2cCOISyb3+aSMIN3TBdPT2pntL",
	"pNoSqKYEgwrUXK41Wqf+BamAlNcYGv2h7ww7v0ani1wGulzL5s9n8dqqbj7Q30mQd74ESFBpTs0cDNyb",
	"uvpLv//uYK8QYGXeu7w49kLq0dk2KsuG0MqUn+Gx+RIzNVSThs3x+i0YfX1gVJ5F4I4KuBwPNMGHp5Pp",
	"9Kg76Qcn3ZF/3O+enJKjLgkGg/7o8Oh4MsLezlkLdofWVh78None250gqYGkVgSokkf0WxXbWgr4SSjg",
	"joDbRIwrB10TN/vtvdjFiPMvCWK/pmwpbeaT+4uQLyiS5hjQz3uZMIAbDUZ0AaGCV3mDY++oXzRsDkbD",
	"3vCo3zs+7g1Oj7eOuq9jnNbyRrRUoqUSaYeozZKxbxoQYT/zMZjis8Hx2SE5GwzPDkdnR8febim8+S0R",
	"19aF8I7E5X4FOkdjGhOkb1N0awlSy7b8CdmWt9sRikaCum6YJxjfqGTekoyWh2l5mPvjYbalTc10MTnq",
	"VJriiZJWk/jZNIn7zvb19m7pvihpBFRVeb4okfUJ4lqL3TcBZXfOKVcTPrshh5wOFt4NjCwdN8fQhX8e",
	"Pn56+Ry9uHr8HGa9enn55vzVY/TT43/pr2M2OXwYTpg+H/HrP29U8PtjOJ7zh0+PFpPoNfz4eBKdJr/+",
	"49z98xD+9ewW/q3+GDN/OFO//vKP5fNXr9+/gFYXF2rx8ujhE3r+z+O/vn7Kr24PkqcHrweP8F/p80H4",
	"/Md//fLHzcm/5lcvyOvb8/MxO//pfP7HxZv/c+nfhtf/MONuM+qYlY17/vgi/Nfv/5q9f/L742ejf88P",
	"Zfjg8noYxA//uH5/8/JV//mr5enlz8sZxedjpv49PP3x5vEvlw+n4ugfeHbw6K+jyemr18/F8eXhL6/7",
	"wXzy4tV7+vjk6OgVrPDHf75J8C9q4Uej2a//fMjH7NdfBqEfPZGXT9/cPPv99eDZq5sZHr45GjN91I+f",
	"P6q8Bm8bcIPLrYarG1LIRKgTbP1Mpdrf+7eR8qxpGyIchmXeT3aNyIdF9vbNyZvBu3pwxydvRVGwwGFI",
	"Qioj7+wkM2hphpRN5eIQJpvKheZh75MVKrnKjTxR/mjdk2X+tl9o+LKkt2Imw29FfNtPXkWb4uLapryF",
	"gDJjwH2cV86s5V90zXlIfV399re395iVMS//FLYNsAdJiV7EqVOvIBFXBCzO+fi546776VTnK4JORg7N",
	"Nzo7iJg6YFO5mqu9yWk2oSM7kIQNh53lSjw9PT46nYxG3cGDPiyyP+2e+sd+158Gk9Fk0h+NNEwmpmzH",
	"B8/HMfapWj5cak/YQf/B4YPR4GQ4ggs22fuCc2VQ9BjSYAGKDrM0WIkkge17OhqdnA5P+keD4cftSdib",
	"IRCfRpRLFvOifpP2spZatdSqpVafjFptTaxqDGi51L7blffHvk9iRYI8QVuvb++yq86xRBNCGHLddEbV",
	"WxqGkPpmmoRTGkJoAZZL5s8FZzyR4bI3Zv/iCYrwEsU8DG2kgdRgpQeIOKOKC0SVRHng0B8NTUMGssdM",
	"cYRvMVU6n0lI8vw7j4nQ5GqHc5jgwKbU3Y20EyF0zhrKdMLId/bEvI758q54pu48JzxYItvF63hKYJ+8",
	"06T76MHEH4yC00kwAlXq5Ag/GAaTk8P+YHQ6OX6Am4to252D2UcJkL3ML3lqIkjMFCZFpj6ZDuLCXq9p",
	"HXAiEeNwW0xhysYMpwBgq3VNKQkDucOVQexMSP07XpgbpeKmcAapNmsOQRJHBMHjg3CoU/cg8p5KJb/4",
	"G7QbcVuWZkuYcTUnooMSmeAwXJrMQBHBDLIHkSWa4wUpbnyH25pyMaFBQNjdrisdpuK+wJKCfEF0Rjgc",
	"ShRwDX/pHlK4A90UDcmMyK8E826xRAFhFCrcLZ2S7g+Ld+bO8BLosI91ErLJUm+40BDo5w1h7kiAxhYO",
	"Rfo8Jq62xPnVZYrQ+lwBm9l32WGOGSM+kRKLZe44TfazXP29QpKp7Q6FMlueT9tUHsMR3Q1+jHHGHnY5",
	"CFnipjgyZ+WHmEZfOIycM5Qw8j4mPjzKXKCEzTELYB+6D+K+nwhBgh56lYMUjJTATFLClG2HWTBm8FUm",
	"vk9MKjuggUosewhdTg2gUQ0GcMk+lqSD4pBgCWAE/CSiCmEJAESlTHahFYyrJzxhwd2umnH1bgrDVNxz",
	"7p0iQUbm0ydLE/Uv/N5fa+kDYHVKWYCy12qHU4dfaWAlG80R6pF2u4QC1XmXC7aGBEdnBwfwvZeKu287",
	"3oRgQcS7iKg5D+Q7mcQASyTQfQgOiDBqTemkEZdEnbAg5pSpXk541mRsZRCzPSN+TKnOHkgiTEMT9n0P",
	"l1ZxnmXX+CIm7PIRMtHAiWFiTSZJxVFApc8XRGhKDs+aOXVnZ0a3c8LQnCqoGjVmupSomRGlR4MM1usK",
	"qCoRzJI3wN9QI78eA7PVx8LQBCoRYT6IgkS/EdywBT5m2drm/BaGzC1xFxCELVHfZVncDfJSG6GZ2MiR",
	"3ZJMj7CO496D+8LZ1b2Uy27a7JcWiqAM3klzvVPHShuvCGTH2+FUE+auldyRpILYJ+U7w4VUccxFKDWv",
	"6Zf+fJat2bE+ZtOWGQAJmLyPgVna6SZiwWE0oNoX5vjvdiOFEd+5/hsfPCPGAUdp4+hvBWczZKDvC7+s",
	"VxlvGaT7ga3IJVPYh1sEKcbnQhBfoUliOBXKpBK2sA20TtzTOWYTguwpkgAFCdGlmUmEASIMXyRzJXju",
	"1YZZUfmheAI/Y0WYv+xKwiRVdEGAPoulVshMQu7f5Ar20MbVjLJyGliqLltEJG9+TGdwms4Iv6dREl1n",
	"Cs/RSceLSECxd+bp7h0voqzQaACaTCI0nDHfKMXx+8sXV9eQBqUPKrUIv381FzyZzeNEPaMPY+mdHfX7",
	"H+/Vpllys5tMmmnFbkYSJXBoTr7rLJ1mxILB09Ux+hzGg+Nu/6Q76Bc0k/s0HqwWhPqyrQdfRXGxvDZ/",
	"B214bgXbl9qqBv+1imSfy5Wxheg/NURvSdobOVnapr2cv520Fro3w2t7dsXOz59cI0m07CURyJsh1TyE",
	"AJbdlvEDdYy2E/XM3cZEKErkJqPfh7QKCNj/VgTGiJoKXFwAOwoGL4VYEoZaARAuCPCrqN8bszG7Jros",
	"Xt/KkprrEQQHXZ2dnyG9BrtC2UPnKOaWq9Bg5L7YdnZrWA8xZpyFSyM9Ao+lVSb6s25LJeIhaADVHNuK",
	"CCa5gw1Zh3320DPDSJyhk+PO4elp5zT7/zFzrcbM63iWPT3zKFO6zIDlQbyzk+PD0+yflO/QJwfHApt2",
	"jItNwgSqxZkWCd93eUQViWK1TCOCMnNr7hqs5bV4Fb/MCajPdYkwBizp1Yvry3+i84ufkdU/GAEalhD0",
	"ULOb0zPp29P2ZTjSdFijvRMkSHySlTbMcVU99HhtLRJFCbD9BEWY4RlINwsixuz5k+vFYQ89otJOo2+J",
	"x6b+o1OFgbF4kbteGPC/jBbArCXClCEC0qtPAnNZFcc+4TwkmFUce96ovYpq8A1J83FtOFPP0WixQduT",
	"G+ht2phPgBIDHaoKCPmwKY0jMqn78oUV7FhwbUTnnUBTwSNjMDGBjWP2cIksFHWQRpkY+zdErTX9TqYT",
	"adX3FPtQwPLyCtnM3GO2OiU00yPYjj2EXktibKLZVeoeMjeTsaT6RlWLBE9gGLAH8USh6+fnr5BOuQEk",
	"Cy6p7GxYug5nyzVrtGfUy25JKmEzpts/YCHwEn4vFhBZneLi6jXKt4AhCQO8/i2rNYKhxfHIe1syXbHk",
	"4/r4hXKPa9Q5K+hZ37FkpyvgmI5UBowrlRdLgLC67uLqknWByTIT/uuXP2sFnVVmzMnqoJs3AWOXrX+l",
	"oGIppLxwKe/WSimu74EG60O8yvsMXD4qhS3DCtX2NMbLTRulaQHFBtutpRq8cttFzNqiXmUZFoE++9oI",
	"npdB2XqgQeqEa44vfUyTRO+3eCRAnme8a/9omDUayN6T3EyP8q26NEoTOOGo0AkuGKu5d+bNqJonE2Dp",
	"i8ogm9zwIL6ZHUCHj2lxzdLN6C/rcJOXJ/aox1VYUd9p75+5OXLc9OZSk5p3XIWydLl2pDJYyyIlq47h",
	"brdphv8UF1nOPldf5urDUHfIhbYfO94ECwKnW0IKHbcGBNAeIDVlkzEKSKANFwGKsD+njPRK+IxCWdSS",
	"7Qii7ecRgrfLFKMqxBqQ3qyHdAksywt31l649VcsTmQ5YcvY6Yur1zLX2XG3H10t1rLeWPv3QW8Sz0lE",
	"QIsFrUEp/PRh+Wi2slfddczixAB8Vp61fnbTSs9KK6aNKWNEx0eV3ilDmslE2HI3KJEpM2uvWfO/gGh0",
	"utTGaTYV2KiEE0Fekik8j6aS4NR4TigsZkShOZeqt5nj1JeU7tge+wqDU43ita9IWoq24Yth2pc9FLM4",
	"eWaK7a7P9vTqdQEwS0HRDaAdp2uWvDpY88WnSyxffjkdgenM3VqF0zpBKVYgLgNI2yKHVE+vXkuEF5hq",
	"SQZYZUkIczaTF9flsFoF9PpMNoN6tPGCSm9mpVZy2QZdk9Udfu9jEcgfsp2WL8wV5tt4f29Mw1UMsf3d",
	"DnO4Ulx7p3hXZUiTTVK6UTgpM1teYrD1BDu6dnSZtLBSQ7cGvFPfJgd0KOvbGNKLlU3Xod19L3/+9Xub",
	"lT69Cxtw6Sa6X0agsN+SHVUe6vJT8XpWV3vt8zjvAIODbdk+t/CdGb/CAHc8q0IJjqarBoHtWncqWN7K",
	"pauZVjHkCvHSnCM3CRBlNcqAJmnPdazE6jnq7rnFbTrHbEtr23i8IGKp5sbnHKUNnXsMIyQwermE+eXP",
	"i63cXMqk4cjqY4jDWpb7xXj9lDN++eLP60AA5onjkXbOAWVffjgt8ZW/E5k9YnXEK/PJcUGUCK3hMTyx",
	"80cp8k2lUxgeTKdLKZvGOHOaVKWb5lIb5zK1rEtF/8cpV2tDkdGMMCKKU+TQpmzwq1wIe/34Nthdz6N4",
	"Wgt4skRzOgOZgwuNsMaPR5ZO6Mpwr870Gtxv3RMz3e1ePtagxy+CKlKquMnV1taeFp+KFIsdBe7Cju5M",
	"frNRzj5UuGXHWOCIKPDEg6swhkpDR6pJcp6gbqZ+l8HaJuqJXmRjl8rrVX8dmhO9VCdHZnbDzV1M0023",
	"no5ZeYAXcJOkXB0bxYki5jSdle9rwY9sa7tjx8oYG49og2h2F11PA32EXsPTOMkqiW9s/eLa+1he9buu",
	"61p7oOiClp3P65eX8EgksS4Dqum3PimwBxUZeUHLHorVIuMN9vSm2GVdu0+9tXH1gTVQYqRHXCmOmVLw",
	"iE61Ix6GMMF1QDCNNg5i3WU7LhjBynopmJU+ra7sfDPtgwkM36PMa7dWeXiXQTXBvptwF92/rt7hTNkO",
	"bFQmeDAvpSJRXhtawkanNf7rdKvQyrDVWp16i4VaHkxgB+V3H1CpBN90i1w+Mu1AK5dqeOt7WE0wFPci",
	"gpFwc4+fTDuALSwoZqp+q7aR2WhA5I3i8YFLmFtGGJx/++qgliitBMtm16InGHvDUa8/GnubjWR2v+lR",
	"paecraES2CtejUr+5It9IJxL0upWnhn/E6NNh1ZZiB1QfUlyJL9OF7iPF2j/T4Xb9t2eC5v2sYzW6+/y",
	"O4lCOiX+0tfGS+tA5bR5rgy78w3UP+pwXA2TOuqgVMmXYxKrJ/9O2ojzdWCUbt2NWNF1tYXpX3ksb9au",
	"a9XagRWCrtpyYgxVeWjSYkj+oNI70o6DmW2s42G2rD6iWouEaZH5wMAJYEVBSW7DpKnMxX02VYjCqKWa",
	"0FVbTZ1KrLuiEtO6BWPhSxXg2qaDtOFIEtUpxKvC1ftzEiQh0cbByTLGOjIAsyDnQLOq4zIFaMIl4szG",
	"VqXTB6s2pNxRAzPEfPKzA/Qrk3a51D6RIoPOzQz3oO1YZoQeesF8Usif8M6AMBIE+3Mixyy3Xss8TYjP",
	"I2IcQkLw+QMMogx8RCSdMRyeQRiw9hVJIiLkmMk5T8IAKUA6ZFO2ou/BSyw3+g8ImzHHBiUt1Rt7Fo/H",
	"7B8JSeyZ6hgoGAUgiU/08a76UP7//+//h2yXKRdjloJxFgaHqX7OOATpiACoYCcbGu7ftdSRy6kClUpw",
	"g6ILEi7RBKaE5kncQy/JxPU2wfCYuYD/wknm4GFCoLUgGpC1mi8OsU1yQY0rXWIcMBOmaDhmWR4LcL3U",
	"8c1Z5H2m5DWBtaQIfgzhMVNERBTcSkyonjvdHPpfpXTSnJ/X8dypeB0v2yT8kibgvVY8jnM/6m56eeUE",
	"I16M0tzAJc/65dVi5LzDCpwsdPTqB9xkacyPvY3xJbfkEooDYtlDHAJiiR+1G/nFnPg3b4alSwEZbmJb",
	"o5jz0GUt8aHT+hNivi5fzQWRcx4GNg7GuKwO+jn/1UEZV0DXXYXT3of9jd3BN5cnasfeCbvT6su0kPnD",
	"Ljd2FU/4LuLQz/m57lcqym8LoJgwIkBR3QSIQtveeKyhZ9p5QWGhzPuKETheiq4P70BIFDhvApHRmTxu",
	"qSQmul9nZkGPnl+jEE+M3TjCaVXp40O9LUUErOC/f8PdP95+/1sXd//od0/f/udv9ocf/v6XMhQt292V",
	"zUn5ZljxgpXv0aWyzHMtyo+9jpcEcSnBKZt8m2MtETGMK+sFDep9MZwLIlCdi8tHL2XeGTfnXZmfKSVI",
	"udP+/u9n3//9bHj0W7979PZ/hr/1u6O3v8Fx/89v/cHbv+sfzb9/GI97P3w4/Ni8+cH3fz87/K3fHb79",
	"n98G3aH78JcmDrk0CMmrNQJRwiUHEDxpGsJblLrzPzJ+ztpcdtzXD++ri6v0PKR7DBOWhufrRq8f5Rr1",
	"is79o81kySkNcBi+mOrImDrqX4OaEFlSxnvl8dHTEQJ8o7Sfn+aKa7z4mBW6rJkFmhTO4Pjo6PBo0xlk",
	"NQ63330OdVcFlixZrRnd7sAewdsNBP0ZiSbNkFM/nBGJJqX4mbEXWzzr7qi3OceV3buJ7WCbtmuvuTmB",
	"h11XcQia59jmNousivFFmpB6ipY79ubsU+kNl5CTWPD3y7pnIXXI5DZGBl1BF+T6oMWwgfOd2+am23kz",
	"rLbqFO/HBRx+LXadsl3ubOCpHGwnAmtj5z52PqycYC4MsX60rKHWZ8U5WaPZcgpkoZTAZ5mArL4kF3Rj",
	"NQUu6UAHMhxpd9IpZLMDhsw6dEgSmswrdsGaQ+itE9R0O+uH/7bTFDDXjGobrrHSpy0//FfnaVUKaA3t",
	"xSt992A4LlnNphP/Tq7f5IrnquOK6qh4+euyG0HPcdQf9Vt5aUYYlND3tBxPDWF3ziqggdPt0eVVA6Ke",
	"7bvBUVcodAGkTMSd1YXlU+zgCTCveBMGFMhUiXuXxXW1JuBMSMghLljxck+s3Nnti4zl9VLpWWeql6a+",
	"fFvv5X6Icn43JWS52iumU0tjV4HHBGBv5glMJPTXyRHshReQNa9IGR3ajfzYSUq4SXupj7Ja72UwnJaC",
	"d7ZOiGTN6xay+vAmYLdUxeAA6NEmBaTD/8tHsiZYNm2WGSWaiOM1tOc8N/Pu+rDnbpv3qgqzK73KCagl",
	"0i9eEoEO/5rqg9zbcZu/PDBadTzqR7HXyWmJOt5CiLjuJqsgtzIO9QvnfHLb2hm5V8coM6ulQSOm7WZ+",
	"JWASdClp0sfGr4BzumnssG6X5Jy7pfNXNwHo1aYI8z11nc1BwBrw3Ivre/WzZVfeWT3E2suDRjjN7L+S",
	"oMTSCJFrhXwsFpobs+eQJiHQGmZLNfMyzBi4phUXY+3GIBN/Dra+QoCx1vDZzL2pFXjMnOcztDc0OstS",
	"vDK0s3z1xuyJTpShswZ1TDbag+EoXRzOb8ztJ9QKbtjH8GjMTAMikask2YdKn0cdFBKTATn7+2B40s1+",
	"Gx6NNIg8+vHiqjdm+XPWpkrIAxFkyU9SAi+t0dJYN6EljaJEgXJjzPBUEXGLRVDiWWCW79Tzqzf5SNe8",
	"kzrVZgTHvnJPituzIB1zkSYRizF3TsiMGlNtye32ENpwymNmcsHoI0XpiRo28Rbyf+JwujJ0B9Ee2CKL",
	"x65zkWbTu5QR3/f6P+jjmmFFbvESfd8b/ABnN2YOgLp22iCTuDFEdGIfNsydZTVtldoE7e7hLHpDO381",
	"1Lg8KTN9hyZ3zZjlj6zQvqClPewXU8+Uqmg1YL+0q7yqvXJTr8OkM8T6xDfgbLp5fSzGVO6mBHzdiE/a",
	"upSHw78Nj0xS6LqV/2140imi14lJNmtXs7YOfdWOXCTSgpLJIxOYyMT17XTysASlSrJfhg96aXLqCCvw",
	"dijswnh4TJMwHLP81VNpHBkAXGTmQbJyjLBYxtP1CsxmZMyoRCGZqq0AYIXwFxC+hsQXH7gKL0vztZqd",
	"2SDGro1QlWbD5IrZPIxpVzWKTCaMqM2jmHZVoyxCXPk2ZyEyb34+f14cIbuQ7JDrdMMsfUW/CtFvZUd3",
	"ZQ93UwGnnSu0v6sJ9UrhINcGHriUsyoWkamIL9yRDUTo0ZLhiPoQbZ3yuZYmjZlt5npbv57MmKmfXCAs",
	"NCIdTTsCrv1s+Zjdat8pyhaQ6QteKJtLDVAFTYi6JcQk1RYE/iA4Dnys66gAZQTvKzCTSGCRnO97iMWM",
	"IMIgY6reypInYFVSpgKGczzVlaDGzHpVKetOphcJO9OdGoT21UQPWoUNfN7+qrYPiOp4hkpnjO9WYFng",
	"mte1T+7lLfLNII/GcT7j3TrTp8skjBnkNlPGzY6kPLBLAgYnDu/uUYEPsZ4dB8OT3GOp3/2uNrJLPTnV",
	"madXkHkFl/L31CkRLxqZHWrkvWpC8Y0K2dtaFrJuezAqFNdw9mGbm9okmW+tqTUy+hq4gI8Ry4a2/p6m",
	"ZIhO8WfolS4V5tzfHVZ8J8csFRdhIDOIkZ5A/aPdZ6UVcDTlJBjkH7AvmCkooMeYxTxOQmwdJaHKTSaG",
	"whCme2KRzRQti7mUVKe8cKzNxsu1rVbvtLnEvoW5wpkoKvHnk6s68iSvQYz/KpHemjRv1JXUHnS1at9t",
	"4+tS6q/Qo915uqqI76+U1W0Q7r3pML4gBejekLpU3txKu7gxFc7W+Qzz6vhqi0cDU9OuM1fbl9IIwJJZ",
	"dXQbnZjXoyKPZMdLIwJLRrDZ4Ph0LfhOugo9ahnb8hWB1fbphxL7Nzo4WFt4Kub9KY0/XJ3XROrB2AUr",
	"WEhZ8r7UYGJo7COiMA1/SibQXZHS12qWd0Qp2NZTDhlGh7di7N2kQ429EqTRIs7zmhyeMNl3MuepY7ro",
	"y9C4YKJUcsVyypNswDr8iqQqhZlW8qtkR7FSqaki18pqwGQ2bRm+5Q+9CvJNm09Nknfhm/O72fmpWhtk",
	"7Ugu17w51JxUHtOUYJWIBgye7v/EtbYgk2FB043ncGdv2Y7SPVQf2JPcNlchSBKTUdA2yR2Xqc9rxE5g",
	"tU3qozIrhX0Pq/PfXk5dVB2oKJjJqmmjBXMTWpWJXHthpdE4c0aQjTabFH1BNLKHiVQFUcMEb6Y1J9Cc",
	"CKLFgrI5dWkHE0Fmgyhlx0X4SZJaAXKzwoLyMYRaq0iUb8KtNvgyrR1a9fVd1qD+nUz9hlzfs6Xf/Olb",
	"IWB3JF2fl2h9MoLjKtnXPKWpPmuVC8ls/QUq2/EkjYwsX8Oi1HpE2iaNucMc5Jawhlror5WXoEGZ1eW9",
	"mvN4Y1hkVu8PxtF1AN4rNOfxPjTb6doaigdu0aVXnupINjlEmZbNzx+alx29JH4iqFpWJpQ7R66JTSp3",
	"Fyp5XZjtfollYWdVNLO4t69Og1rY4870tHhSSUgaQIFIQrIqrHdcVQwibFEb9OL60rmeGZXjhC/AUH45",
	"RVaJr3EIHCUcXgW5GLd+T//voG8yqBiFpbbOY7a8nRMBY2nbCBdKF03V+r1JmhXL8jNmCaPU+U2a8SB2",
	"zkTHGfaEZrYFsxW7Fusrp2cpYdp8GogtY6eCvJdlA7E688rMBV41hgy40yvotEUc26pX4ZpGNl1RbsxG",
	"0FXl82nZ5xJAy4xDjQne2qwbiV96SOXGNwAwrTegzl5qoFEJPLVpsVYeJ50Huma0vAPmdrGI2kliJwh4",
	"qXuWBorXtK/eg17J2mF0bHB0OeppFHX41wHsWz88wio05YQFzoElW8D2J6gde8pnKPj87D7HemIaHdYJ",
	"G2uEJeVxjvdKhXcjwOvKpn3QtpXkuXANBqHKgaoDye+0q0BK952rUoFwbxnzy4V6hktYwQi/TyAFVbxp",
	"XXCGlPlhEhCEdwXWjCHdJjr3s9P5N8PPQ+nLg2XXWaWN6LXZGKGXvPUCjSVi5ZzNUBsPts6RavU8vw4j",
	"U+n29sPL7uZbtTLEHuNr7xaquhk4N53Gn0EK2tabZLXzHnxKytbz2YiNpcI7k5s7BX9uAqyG0Z+rA20K",
	"mGzobLHNoLsGQ66cZrXLxDdBvPdDtivdJ76BM9rPCW10HCielNyRmapQ1xaXstmXYC+LqXYsMI4WVbpL",
	"+HZHnaUe/r6VlTBJZZHPVyVFbCvTbFkh4ApT0eCIc/Oer/V3PjNlVUOfZ6FRWCnwGcwlUFS8SSHQcjiv",
	"XVHJJUMbFCWhonFI0LPzi4MsjB19r2WuH1AMpwFrjbFOIia0S7cpm2034vJClSv31i9EKy3zSpz1tOjY",
	"r8zcCCM8O79IF1oz0MrB6RXtcHSbYq0t+KQr0ke2BbLW31sl4touDSPBd1yQuY33Wa6N2sQbpuuVNasZ",
	"GeJpxbs9w4oY67sza0usqNQqiAmZ8lzApcu3qnVBZXpkzgKqcja/zdtbX2OpubE4cjXsrA93XpELwFVo",
	"Udzud4lw6rlDgizcy+55Vlqif4877ngRkbK0NsuPSYRZVxAc6CDGQPuPGKOg0ZLZ+o8RZS5YcFDKVWJZ",
	"dhTPjItDNoFpqMe3Z+PCQtwp1M5Ue3fpMrL9bnOd5dbk89LrQunMqWF5wwlVzSpLy2GtTZh3P8PKPSVp",
	"TiZFI7Il9q8vpZoOXdmMMecmtK0yA0b6DudSwKRdyjTZABPBfeTwcUNXA0C1wO9qHHxlgj4se1v5XvfZ",
	"i1hvjhT8IimbNQLzi3qKmMvyzrhCfiIEYZDnPH1D7gzwjjqWA33BIL+Laqiqnnyp08AdGMLCQjfxCrsL",
	"HOtnUn10lWodSx82qHPy5cc3Fxw2UXm5ajYNg4tsh/IUUC7bOTSCFPcuXsOUdqYk1Mlk6YxxQYKzQiGE",
	"MUvzLuS4aYIWA53TPk3nr6ArMgkOdFCLjf7u5d3Rt2LlUj/+UnrdAEXW+63JtDsAiltWIol4ZEnoep1B",
	"+ALvqsKUOR/oblpjsuD4nNencYHMSM4jEyUxZyjECfPnBdF2slRkI6alIJVBVO4yapCwQheYB/qKwh6x",
	"K71QC63lBRvgsk39x7JceCY0Vn/O5S9zBtyaaj7V6fX0kKsJ3jaO+LHy3OqNNkUu56tRauU3dget1tow",
	"W9hpTN8KA01pXZN66FvtsJojrHEa1bicN9jl/Za2VuoF7Ey/JuQ8UXMu0uLVDU+rYohHFW8DVF31sw4I",
	"ux6m8ioUYeVcSSVwrIu7M6QECMBpbEpWucMFb9udXLLfM/+AxovPepWv10zS1TH3sHabLj7CiggI1Xfx",
	"NMbnHQvjueKcOC1So8wjouN66AwqPjYbq7wI2Kf2y8+qBLisVT+RJahSene3/1UxFpVoZZ9MIE91RNsu",
	"pPgAVeoXrzXBOHcZgDYBdkWvRvlNudB8cSHjwQYZaben/M1wxTU1NZpVnu03KVttbz21vfYmX5XfRGNm",
	"HzJF7mZguKwxLtQZcbfn9pvRvIzvr+PdTaseelVk2VPeXKdES7mL3j0IEQGRcN0rwsTFHJtqTzlZQph6",
	"SDJHcTuQMiot66y0Oz1XprSfzu5CpBJc68+o0qGBygROZU+zJW5NoDRHDms59Ys9M+jGR9m0dmwkoAVc",
	"1YwviGBZsj6N9l3KqK5JwwIsAuOcDCFkuvCMmagzZhg9u3z22Jo+sFBI1waEFHVE+UV5jmSwIYiumwXJ",
	"9XhIJA7JmXnzKJuZolkhwUKuiW89dI58uFX3B6QEnc1M1RFEWVcP6y4ZJdLe6FjXIgkpCfJ7i/Ey5Dho",
	"ILt0vAUPk4g0pkVvdPNSr4cSwaeWEt3N96H8HdgPX7qNaWmzKFTgcrdK9VNJFvKZuy1pyDtYaO/KWyNS",
	"fuNyYdEfpdnppj2qCiqkmcTLz1Zs0FJuxqNaPeeXJpLkDE+r8sct/kQCiE2fEzSVRKwIEqzKIDtTPEOt",
	"yr29mrsrmRHr/JT0sX5dmV2KzO0d9BS5t6WEazDFJnMckX7tyXsqNXtjOsu8x4QpZnqdko5GbKuBjnp+",
	"NQ8SJblPXSFQs46IMM1tKGJrubodmFHWbzcgC+pXxYU4OweWks6As5lpS7HpoxNKdAyW4gWmIZ6E5dk+",
	"6BaUJDuRUtQ0u0z3o60RdQbjNEGdxFOC5qvm47SpI/2rp1iV3S8tHnvdSLjaDTeu1ucpsbSUrmcz5Odo",
	"zJZAlcH5d3IFvrY10KxAdyUW1PgRwuevi3jdkXQ18BjUzba8inqfvEa+gbtMW+MMyHAs51xVK9xh0EQ5",
	"S5Y1xn4toFDY3e4gsT7MxoNyfZpoH0sK6+PAuJLg8Kpwvvs7U0mihYmXWskIoZcfC6KliDAE8dUsLP2v",
	"O7Py3ZRyqZQ0AO4qhpVuQ/LKmeQaDKjkqkuf62qmuiq5dB3jv5YxYdPwO/rkXv9Yscd7ddKtuopKYlO3",
	"/6/O4le/+92JUYNx7ypS7jFPdi3KbCpK1jDB8+5zNE9d3MTk1Ah8G7wHtSRsK6z5+swq9QC5T3ypeMcZ",
	"guoGcKKJJKLiNo3tFjN/zktUlkbn9RMpzbwIet6QdEPKiJupa6i6IgG6OHcasxuy3Ayw2UwVWy/obvZp",
	"Bc4rbF3+JB8uYsWM63U8xhkpTZwk5bz8kAxE2xNYOVujoizt595n26bhEWYDlp6hKbRxnspoIMxVq7of",
	"6d8mNptdGpCX9jZu1HZQa4aipnHCrIjspD2TeG5dSpS6xAxV2sRhnaOydHWphySeSMKUzj4wZoAevdwQ",
	"vVSvJdEkMR2kgjzUqfAfE6ZLAggS8QUOe+hS2QIDkCI7IO+7ODQKC50svmYGk5WuGfu2etyZrbSEdStp",
	"XIrUm24lfynVQZdNc7rmrOGl7guyGaDtDmS124l4wpTR2NRKGmvYWqHzef7kGukxETeDpuqLFJIcuJc9",
	"drqrcXYoR2gztq3YUDU0skWPrc1wnPT7h/6cS6V/ImfmD8DDmj9stupUW2guH5V1/oLUVdk+mmutzDFe",
	"hNgkfm6giLAH70OXbeSz3Ew1QlmulUu1UZ3ZL6vRuIxJal/KLzD/SrGpXBzCszSVi1H5u7S+xrKHfHWC",
	"Lz2NZHFbuzNU68NsOp3N/h4xFqBrCKmMqqvNwbUqLGYkTSLDpznLoq7mZ3XoKi2R1RuzZ1yQYjsfTPAR",
	"IAdBMRGabDAfbPa5lzqRZMwiyr7PLa7jSrtdXklHdBxhKNTk+qHnbc5TY8DWmLm3RZ4CWpSgUNNikYWL",
	"unPFSLejTuFGa8Do2urJHuHli+kvhNyUJXJ6/eoCBVinK78l5EY/A/ADeBTY/ijmIfUpKaB6xFmAl7CD",
	"hEjz0y0JmPtZzRNhf5wKan6QWCXC/pjo3jUUwi3+CuZeWs6wqtC6C8zEEbxbq8su8IVbEtPiMjKftCyC",
	"c7QCH6D2yTKcdmFt3QjH3RuylJpG4kiz7Out7DARjjedQ6XzuzuJlLUtHobxEtnziWziIUuPsGTtZbe3",
	"XF3pCv9Ymkb+2vibpaVab8gys2wXh7cZsNJIwlOtjVNEwDj//Rvu/vH2+9+6uPtHv3v69j9/sz/88Pe/",
	"VPApiviKBFe4rsojEiTEigJ5xLoKo+1l3K6odEtDLyIqpalcqZsYKv2EhgRdO3rIuXLSQ+Zpp4VIlll7",
	"7VG6agb5DfeHo8KWv//tvw/e/vXgh//U//1LuQuJrjnWIMileP8vXb8Mi6BlYLN8bjHSte1W8dJqqMgN",
	"nl9yA3K5AtjVxsW8mdoCr72WEihb5WA22XtXTL3Wu8sEDNdB8zrr/aXhyBfDyxsw2Y6NrwLmEsc826CE",
	"kKUnXMLb3hBSEv34POXJ0q6mThYoKDaxQ6sFKmCGBlt0WHbJFBELHJZxD9cr1NrHAQFmL8cozHkiQngW",
	"A0xDwyYAdwFr5kzNw0ZcwArGr6/Dfnf6s6Z4GABr9AzWUcsZ6ZXqse2ay3mjNJfi8GQTgxo4nmxL0pfn",
	"5cAzxd7NjgQ0d7XwftOIvJg+wsvys3A1JOFMKEM//nj27NmvWi3Q81bekP7g7W9ABP5n+Fu/e/j2h7Pf",
	"+t0j86df/7I5+tZtqgZIgTXfKCF9pyvtrOtpnj+53nRgz59c516XqlW8BiJe/VKUVwBIoNOqKE0ZAp9j",
	"ubZWH8fYp2r5cFka1a24wqGrXxyGXGu6c4OlRk3K1PHIKwNF4z8XnJf40cCVS4WjOPNlNKsHV8YQS2Wd",
	"74L8TIFTe5fR/0SSoGIr2Kq6MgWI2VYit9zSCjgVT7AGpmpjI50oV3TSAB5NHzkXiCWhUdldvbi+/Cc6",
	"v/jZZLjVeCOJ9mqXaWlDxdEUh7ZEdr+HfoED1opem/Q2ZUcM80c5e2ySLACvl0aGPTKNkWuNsubQzuZl",
	"6KHH76FgClVmlU2moExnTs6vTOY5JEpkbiVwALoApKmECoHXcGREIqaDEEQ3wgzPSJBbqaOc6DlnXd3Z",
	"PSMgxkirONdu/+Q99iEZAZbIufB/CUbqzBL86WsefzkFevOqk6oFFVUhl4/WV5ZRwjuakwuVcFfW1vEk",
	"/YM8pQ/L6ECjJ9S9Cm/voN+rTke8ogLeUjTfqPTdrHEVaTzJV5qAtXhLjYMH0277iB4srKGWPdmgus3Z",
	"/Hax7tkj2ETtq4NeXenelHg3fW5eMPtSduCBMFoM+/JpwSXf0LAQuYYuM4fRd9hMNO4F7SEAC4kEUYnI",
	"aJoOd0ibFF+73GNWHqVrScLaMcAH4Dye0ocr/Fozzmr1vdxJw5ZTfRbZ34aj5TjlVah2Gy8OWw/S21U0",
	"rrKU3gWwCzrQLbTxqa6jWUXjfV5eutZNT6VZ45TaJP5FiCthpvGsKRgURZU1SFh9JvNP6OpB1AJITbiO",
	"abIar7MvFhoJrGmWmuOUhGjlp6Bc2GCIdK5mjHY5IaqjgXaNJkyWVFGh4jLWuOps2lSD6/xW6jlpmNaW",
	"YdeMRBY+G5kVYcRSVlu3sBG4ZoNTWCb8+Yv3/yw+8jswYtut0zqnGW7TRI6UM3A/u/yl+Q4oLZYP7kNg",
	"Hp0JzJRzCLOBV+4sCuaYNd+tsoGBjYCDMXgw51JVli1eZQu3O4YJwYKIZ0TNeQnpeqi/IsVvCENKYCZ1",
	"SZLINM/pAwkOiPA63oQHS6/j/TsholwHuPvqNlT7mNQtVbrioVkgfGaiISyIOWWqsdHsDid85/siQvCS",
	"hMFPCSOC+kh/RtYS0dExFlhRsApopzMOsDZcJwUVo54jRYQkdlRziUABsfF0s0Lej69eXdkmPg9IDz2G",
	"n42oP8GSBK7hC/AmRcNef7haUsi51JmxnYscrFFQorBIORCYwFg6z68upcmGY14HNecyX5dtsszNl9dd",
	"W4L9zr5Vnosmskfb8QwOvwsIo1oJxrh6N+UJg58hEjikvtL5UeFG38FXm4PGg8tMAe1dRAKK3ymXVlXP",
	"9s6wK+8U5+9CLDQLkLBYcJgSHqh3NgeFYUYnNAgIK0Ukvdp3hftavb43REzgUCw42NDCiUuFoUcoJykC",
	"++RdWe7F14z+W6dmwD5BJYxNLtigXtZ3h72+jbuT9swG/zOekPANDpNS5kXDQb40eAjNkc4+0cnVc9fK",
	"SthhqmgBYpyj/RNiXTyNUtPl3wDgX1Gjg7r8vPurtq/9/Sz7rfuu9/ZDv3M8+JhrUWFu2+4w4FcaXDlq",
	"5+TwMislYZePEDBcTFE//xqhgEqfL4hYbszhlH/L3pnee6anVQ/3x45nSO07S/Pfpah4fwTdzSwqj/VV",
	"4a1x7bZ436XPY3Jvm9GjVwT12y11Km61ZGk1V3B3tM6rB2uUSo2DefbiSXhnLXGOiBZ0uXeIw2kQe+N2",
	"gNww8F4W1qXvNgNYrUQ0iZH2rQW8pwtrCC7rV9hQDb+Pi9sqXqr0ztxq9nVdboAfCQ7VvEozBOcw1y2s",
	"wwzIRwVxx3FbCbth/JZ5Hc+0104DZCZwQAL3/O9BUFiTOtfT6K+dnnYrCENt1yqemybKt4LaEtirySlq",
	"WK5XeUjIfUqrZhpPILB6JTPjNgvAA8Tf8LwRF8TkIXuval1/9ocopewScIF4tuenW+FZeaiHdp/c+dKv",
	"Sv2PKlKH2HbN4dbG9ax4FeV/1ZAckJXP+wbtT0Ez4VCo/3JdhfNhDQlCootG0KiC59HqvQJhBP8C3Y8U",
	"87LV+hbMV+jQ/h/0AqX7srzZSpayciK7PhtA9+78VmS8Y7Va5sXlowvzOOVC7YokOM9cFnQwe1Z12QwO",
	"pWuNMFPUTzM25MKj0GLQG/YOe2N2JUhXkJBgHTnBIE2hoJhZp4aVAguO712R/xbjcfDX8biX+88eZDyt",
	"FvddQoxyc/BDnTYx22DmxZTK7gkzlNGM1kHaS0iLtEafOWYTykAZgxWyB2GqpiD0iCxIyGMikM3BKYhW",
	"v7n5TKHnhr7eLv8o9Yku1uuE0UoRyc5SP5JbsW3cMSWn7e1u5NSsY6mb6e7STAWpvWfppYak2yx2DysC",
	"hXV09+2cu2x3awrutVtxIfzbvhFpOr2mb0RVkZDEKKvSwSsyjkQ80CrDjTu3fnGbd+5G3LBzXNy3Hb7p",
	"vsuSbhWOvMHboOOpnW0FUVnQclmC/XsilTFaGXtTwNl3ypHwMcNsWWSsoE1ONkikUe9OCCNTqmx19zT5",
	"LP2DBGOWLsFs3ARA3xHBFC7NSq7wDEU4jvVSxYQqARTNKvS4Uf7JHkKv5kQSNMcLghg3emUcoohgphPZ",
	"mnCMJUox08SQC+3rRLQOG5okksBzS5gx8+kpcBCgLIp4zCy3rz+lh9/R3cl7HMWhtor6WJEZvJMEUdWU",
	"kp47HIBdV5PPcgUpwKn+5PwkFJ41J5R6zLf7uMVNflUgp9yT7UbhBnyH80GwAz0oDGRtC5vUQuesqH3Z",
	"PnuRWwUNZO9FfrYNSYty/RqkLXKtC4mLtj+OGhXLearSuNsZXNkp7n/7JjvkFrHgaQpLRhIlcIgmIfdv",
	"us6Xwoy3daR4bhnVPoOFRs9IQHGFqDxfSrB+pA4eEQloEqEJ9m805SysshAaEsAtSQn/ZouoPJNJYRlX",
	"WUBxyakFCyIUlTrBRtoO+TiW/wVESZKU+54lWGCmiFGDEbHQ8F8Wao7fX764uq6dzIZ9IMriRB3wRMWJ",
	"suUcYVBYDJLE5yzYHLgc4fevTA2rOFHP6MNYNppapX1AHonIhGpv+S2mLotyWAeTunqNmyE0S7MKq8Q2",
	"Bc6n8japVFg08jkpnMXOfifro1SXo3TnCfELExpSOB2Es7sH0bzmsNePlTBfLGNV5/C5sHmBHeOuOTCt",
	"jrQXKAhKhzGynVQ5Nwm98nIvSwuq11XOli9s/dNuLoO2A2+3LxvJoV1n4nzIrF5dB6BKlxIAj81emY/m",
	"BuRzRK4xIBiy+DEdeLvdUfYpdxcXaWfjPeZp7n1kkH/pMshjhfgtk2bPBbpB2YIwxQVwx0osTfZ0pzZ5",
	"YispyJpoWu114d5UO6GpwJAzzdtM2C43Np/mTh/Y6mubIDbvsWh86SKCmbTf88mCTE6nTMPzX1aWCTkj",
	"dp588sVIV/oo5KJu9Jzn6zKu5CIwPL1NVaBEQmpSTGT0oZp0lbNhiyyZ9a55NM1p3HPaTLPOujivxdql",
	"fBUZMd3G7vgwVb/y+p1BxXfmqwsOKZ5S09iQtNceQkMKK6gEv+/yyRyc6+9zl4tMZ0bUqhP3YvSqE6vt",
	"r4rK87SKClYoIIqIKM0clC7bFZRgQSqaYSm5T7OaT5XRFq8ynzAS2CGzR/GOj1/uRasx1hcZrzdZn7TS",
	"YDFmLcODDYqOXNqw4kpqA9K8FdCr5hXTfC/22NLc/2VhF+Wxvq/WY32dx7sdNPewgQ5ySoVUxslLRCTn",
	"1a77M552Lz6IgvhcBNvobO+L49AgRf157ipXYkM2A2xcdQP7Adyqx7oOWKojMOzSUg3qaiSGRfFOHvI7",
	"BUpjtJaONn2+V7GKBlefS4Mc6YstS0AU3sw1BUqu/COkW7A1dIxXNTgbZ56TVdKC4z+oIDJzUC56r+PC",
	"SBq+Qn677l95wQOy9sfXIvTOvLlSsTw7SBVWPXYjeySBe+3eEqlGPSZ9HBLNYpn1HyyGB4WRUgc/7+wD",
	"nASs7U6j6xEKWgn9yfv4UWe9mPKSojcASy7eK/NCBfAVPFE5c6VW2ZvssPYvmk0vaOMDKvTrpR28xyyv",
	"mO8hR0F0JifokDDfSBo2vixzCCbvY26l9TmdgYwdgv3TTSzHTNsWL2yFA8zyXsYd89paIoNkMpFEaclk",
	"xfCCBVl14B8z/cVtGQgrVSHRsXp68dd26+dXlzlr5Zk36A0Oe30AaIuG3pl32Ov3Di3PrYHroHdLwrCr",
	"HV8OjN9wN3Vd7Va7uF6CjcI4M2lz/3pACywpvT1Y9oyo8nhDw3voYbLrjnUMufG308UaS2NxYNxUQwcv",
	"i/eUqF9IGP4EG3pR4QetfXdjzmyp2WG/X0Ui0nYHe/HAfmmH0wjxvjs3rv5anoPfGe86UtO1BMOGVjqJ",
	"7wDH9GAxOMgbDuTBB15Q/n90SFrmveZdpt+M+QqFNKIA/BrxnQ+HL4huh8OCz/s6/zRmxWKCzo/C4G9q",
	"VMsQyWVjppIbpEvN/r7PE6bkmOXYTtkxPnIwpNOzpK4ksaALGpKZLYAFugFUXM2Y5e2Ujl7A022AboIl",
	"lcYjzJ08CjjI7xqD9Yz0DyKRoPIGUQbISBBZEJPgBBfOKST4phLQnxIFK0TZ1Tj/TVh60RRUCtXnMX0z",
	"yFt5ZNHkk93rTvCdrSsD0o432j9qTHDw0jAqxYkG+54oYY5kaATMTXW476nSsJ38PEf7PzvKFBEMh0ZD",
	"pWOuCiTFwbBmrMtZlN/efny7Sns+mlSkEVE6cqOCKc+aHBTpzZX7ANk0GtMol429xG1Xx8WmNcThnbYc",
	"rXQlawveZBMsSEQUDhHjwYrLp36UMXrz8/nz3pg954pYBSWEuGNbacDNpCvLr/tzaeuL43s6CMs8EmOh",
	"A4EsxwE17EkhKj0mouuHiVREVNIGHW6a7nYX5HfnsxPqu5lbxG8R/xMgvnvZDz7Ezl7fciyfl2PZExB0",
	"NnZNbzwPOh0v5qXVT02ONowYuc1l/Sjc1hqxvOJyI7W0fiIy9RdZ4Z00kXoIYe2VaOya0Ix1WlrqZmMD",
	"80R40Jj/WrZE+E9HhPdGOg8+OCi6fPQxDdkgZdUC4O+FZDo6rQhb5hQSTuHvQvOpWsc2M9Ad8O0yXfA6",
	"6zLc9wU6g3yLY/vBsVF/tO95GFdPeMKCr5afalmXL0XZ4oS7VGO9i2C1I+nqtw9+S4y+GeFuN75+c6+M",
	"W7kXSbLADv1J9U1fJQQ0EgjtGe5dAszIekGptqVMaFd3J5EwHaN9INoH4usRPFNKe/AhrfbZSBqtR+s9",
	"ipoOsZ+75bWyZ4vN35zs+aczoxmpLw1jq6Qk+xL7GpCRfvvKt3ShFQN3EAI2d0uZi08gPLqz18U0akRI",
	"185U3ZA9dF34A8K+kkD5MFpQoRIcgvc1uQXHICDBlEmFmW9UbD5nSvAQAV2cAPxpLRlPlPlFCTydUv/b",
	"FvKK53mPst518YJ3kPjcUp/CCHeS+1ZGat+F9l34iqS/Iqk8+FCA5qaS4Ca836MwWMT86+JqW8GwRfRv",
	"VjD8PMxKncFuA9bvS3DbEuX77ZPdYnIryt2jKLfCI6yICUkJwTDBkbIB0bhKPhXRuB+BYdhSn2+Z+oz6",
	"p/uexhWsaeWSolySFiapYofSkMJvWaECm7xXRYqrFLIDQYSud1SdmCFaEtgyYF8fbTr4YH5oriUpR+a9",
	"akf0yq7tulp9SIvE37A+JGUAapUU5Ui3P+XEBozrt89gi0GtHuJ+9BAG6RorIGrowf70Duv0YM+M9bCl",
	"KC1F+ZMw1gc+Z5KHxKT3bqQNqGQGdG49Mxwy45nqRp+aR7gobGkXhsHu4oUeocXyFstbvuGOfMPmTiFh",
	"MzX/JM5rVURQEilhgt3JYEG56GihHfazEsN0a3cgh9dmjJYetvSwpYd3laM+HXGbYxEIMuFcfbPGnp1F",
	"2VIL0Y9YBMicGMKfzETkCPaP2XW12uWWpn/lNN3mcZ1o5cwnFm0ln6qW8G1B+K75VH0+wnedXVdL+FrC",
	"1xK+3QmfwqKleQ1pHpxVSu1MGC+UAYkFWVCeSAjZVTyOoQQGxVrHCb8jwoKYU6Y+IX3Ut9qSxpY0tqTx",
	"DqSRxy1lbEgZeQzluBPGXJERInqQU8/+7PLyCaIfHBKgECsicnQSSOvnIJQ8bulkSyf/zHTSpMCUZRVm",
	"9AcUkCllYKnQW3TZKW0ilBnhM4HjuU4cYsv8h3ymf42xULpwf2/MHlNdXvcWLzumqCiVtmQujaiiC5sW",
	"hWaF5tIsulm5Lpn4c4TlmBVmDbmPQ9JZrQXynbSVraH2UMgnOl+oLTJElA9rgmKnZvtojiWiSkL91bSk",
	"WUki3442zZD3OIpDgqBMzrXC/g1MHoyZG6AkO6nksG02k44U5mqYIBkTn06pj2RIfQJd8ZjJORYkMIfu",
	"yluj2zlWBAhqRPw5ZlRGiOYKpiJXRtb0ytcjrq6fAGGJFgh2sjVZONnJXmTnbVNq/5nrGlggOPhgfoA/",
	"BURhGpbRJCUoWeg64BFlXVNKzJU8051kb8w0hTq/ugTkgJNipjYZSGgEFq+IK+xNkE6jqyvg2XXojoqb",
	"jMNjlrDcCDp7Lp5pHJWESUO6coi+wQfWLFFLiOTWFFiuzsjfHPde2oN7ZI5td0w0A7TsQ2tOvS8hxuH4",
	"3kgFeW/OpDpN7Tmk3Ja2kiFg9thzndIcb2NPv+zuxbTpxG0KNsDSqDdmv8xpSNw7HtIbgi5MZjVNMuBh",
	"p2yqVUMErc4A3AUJpx3gEtAtDUM0EQTfIDpF1JQT9pVEERcwAbAyjHQs1yBN0nBgjUyCtzEj7+OQ+lRB",
	"HnOeCCRJSHxXAa2G/rhKn2v73wf1ebx6E7vQIbey56W1lVpa1NKiL5gWTUO84GWhsq66qWmQ1j6tZcw1",
	"2iO/0HMvePrErnIX9LTLaDUZLfq36L+K/jTCM1KD/fr7LshvBt4H7l+aJe6C+mYRLeZ/XVkyhsP9n1ws",
	"uE+kBI3TBdfCcUtsdiE2GxNPFPDfqCwwipNJSH30+uXPPYReQB5pgW9NE1MsKU0c3UFca11tMSMixmzK",
	"RYSVdKpU9G+f3w5RlEgFSskpFVJB8wWB/kY7mY6+m12mmgBtWy0QepqjqY7Ia0rHWurSUpe9UxeZRBEW",
	"y40YHOgyXfovgMVex1N4BgTIs9jx9uMe+JCDD/q/azkxdkl5UYrEl2b41oDakoevT+zIcDXNClPA1VKs",
	"7DRm7D8nX7G5kyUMuwk+X3ZK92o75+p6dpGmSrKd3ynjaStOtSbWeyQO221Y4dm1tiNwsStlaJ4psA5P",
	"00Y74GeWRG+33D8tRrYY+dVg5PBgSkMiFRd4RqrRzjqOOp8j276HXhKVCCZzdkF4fO3nDhJkhkUQEqlr",
	"D6tlTHqoHnNNT2dJhTkrsXj4JLfybS9gH6fY2fKa/5EQsdzNX3f7ro6rW+35difCZk4ZrujNsCVv3z55",
	"y2QbjZZAI1CGak6qeZL/89uPG5WROguuIx3XDMdyzhW64uCIYDWPkSY4gS5Rx0LKCPiAEqaQnuvadB6z",
	"gEhdPE8qrEgPvYioAm0jF4hEsVpqf8ietDOkE8DcRCLGUSKJ6Nq5xiy2DbQTJqyTs64ZR1O1mAipDSrk",
	"Pfahrp5OPoTDkIguaEpDSgLkxuiN2SMyxUmocjsUXBnnCl2fz0gi4MPlfMnCJZosx0yvOjC9Xees72MG",
	"Cq2gWoe6QhC3z1Vmur4ZblKRDhpTjJZa7E3h0ipKaxWlzUhUOd9z8CH3S+MMwJaQ1aQAziPkk/wMrcKz",
	"VXh+AwrPpmzBdjJFrf9hJl0gak2RVIcsUIkuHzWSFTZgYr993Frk+pzIBXDemOHeSugtvHLNE+1q5LpX",
	"vr2cXY9t9BUw3lQqCAyt5ttRjmH3Q4KF8X/Kd0D1fP6YCRKHWNsL5gRNk9Lupm0PPdGhatnK7EeGI9IZ",
	"s9hw7SS4whD1JRGNokQBn/VfSPpzEiQh0YsQxEaG6HA4iMiCM16VIMasmQiBdpUgkgZUcldpwkDR3VIg",
	"twS3rbBUXWGplY0qnhJLwO8iG/khlrLMJTXzMc2CR20fZDt1bLSaDul3LmXA9ynu81B2kI9j7FNNfyOq",
	"LF22RnAghgL7igigsL7sIUO+dHyv0DbdgEqfQyyrm5frxYFvGtXEVuuR1ZxQgSAUJOQ42GQ6Ku6gEUPp",
	"jmjb5/g+VLQXsJZWT9vqaVMQrkD49HMB8QFDJjjEzK+1wrqINCu6hXhJBBoh6I3S7vWItt62HM9+Lqyo",
	"NfM0pCGbe9o73BP5get86K6ppT1/QtpTROgc1fm5+KGhnagwXI3NY5U+bC2n5CF3L6aP4oAtJrT+6N+Q",
	"maWAlnVIXsVUHHzI40dTY8sGapAzuRTowc+FqVqrS4v134DVpTEKdu6Fe7dpIOoRspR734SN/fZtbbHs",
	"izC/bIFi28mjxbdvm1qHm/jhpBnC3Yk53oMmv0XgVp3fqvPvps7fhQevzm3luAKbAq/AFBxm2Z0QcvmU",
	"wM5oTYwQ8EZMZkuc/k1wCGhTfMzAjGqOQVdsxNqVEpw2JIqw/HdCBA4om7mEoAsidO0ym9QOMmIBNaKC",
	"SIQVCgmWCvJaHgxH6OLy0UskjLUUnaOYC5Xr6jgcm2I0zeJposKmAkslEl8lgoAxIcsKWtCfgi3CXSKK",
	"Q6xg5W5FEcAGWLsDKrShF07F7LcwfLMEmhtzaA2fZxmxWg3o/VlR3EW0T9OfUIOZyzrnSGqKdg21lnaI",
	"Gn1lDpG35sbs6HvRUqZjtYDeKii/IQWlhetyHC5hiA4+pIawZqrIShTPKSHdlM/d0K3qscXnb0D1WItc",
	"nVaw+JIEC6OnraRWq4JFDanqt9xES30+t0p2A+nZTihOn/xtNLC203cSWVduNKUkDGS1MrYct3Zl+veg",
	"fW3RtFW8torXnRWvd5EtDgSZEkGYT3SiPftzrchxGZAo5nBihl2YYt94NAsS8QU4VadJ+LPBXYZAQSRP",
	"hE96Y7aVpPIyHSn9aZ0jGJXVVbGtgemBC4f4maVZKgl6Lf7/abJvrwBxFIeWqU2B1EaLwV8RZymogizw",
	"0v1s4ZiZ/LM2JmDMfMxy46Q9oYoFhKk5jl+Xx6BsTidUpa2QRjTg5hOmaAiVxsbMDQbolA0nCAgFEPrG",
	"Jckm3CExXxmr0USpbWdswKBUkgkcBFVEwqTlrSERlSxMI/owaEwfcBCk1KFlQ1oydP/lDIfb5N03Oow0",
	"r2eWdldmYne5XF2VtHq3EKFPaozTG7z2eUx27auwSuReDHJtyYCWTtynza8cs6uTaQ8bJ69d8bJcy2WL",
	"Hqbazs7qV1OuawwFBxGZCV10zCSodey9STXZQZQVP7s8/FDey6eQrEoPZYK+757ZdriWvrb1Rvgi47GK",
	"OYJbhc+f0J1hBadzZO165UvT1H2FbjU+DiU5rrdNHpEH3/0kpCuO2OLDnwkfLBgXAbgWISof/IMPBUhq",
	"nC1u0wOb08kV0ee6OF3rSdBy3d+AJ8EWqNj5yhlsY4jf9HiWM9gbkb/fvnwtVn8ZFvqtUHo7sXHlyd3G",
	"ar+RaU2a4t3dWNh9ZEFrEbm14W+y4X9VBvVdGfJPUSRmmFWCaXVcX6iOS19QSwn/nAV3miisYNJaRVVW",
	"7Gnr5x267kk1ZYZqwbh90FunvO3owDpbcPDB/NBcM1dOJAoKOT3ytR23VcG1JOGb89Nryjs7bVY50qzw",
	"ztUY02+fxRYHvraqje5h2U7/VMGDJtWYsiMruhcVU4tzLSvasqJ7Z0UPfM4kDwlPVCm92Ob51eUHzXDI",
	"jGfcvbd9lS8KS9rlibareKFHaGlG+05/se/0Zt1kSNhMzSuKJFcjtCRSUs7uoI0uqKwcXtth74TY6dLu",
	"gNrXZowWt1vc/nJ58HpEnWMRCDLhvNmzuxeRoFQ3/SMWATIrQbixctoh9Y/ZNlr9U4v333KAVgkSu3Qn",
	"XV+/lt0ZVqTmzXUxj+ESSayonFISIN3HpIvRXlxwOloJPCFTLggysVoIyxtpUsy4SSFc0syree8Mc++P",
	"VlzrVS8RBo5gSmeJIEG6HnsIekPNCciV7W34jaf6AHfWNqwPVq13KIkWfzU3q0e3WCJBfC4CUzwyva02",
	"JrTNR/et6wRcxdMS9LdfUj4hR4JwGrSm49XumQ7VLYRlK2hGgtxoO9Ed29eMdSeDu151y9q0rM1nQXo+",
	"VV+EOHLNp2p3ceQ620YrjrQ4+ycTR6Sc35Dl7jq/l0QJShZGnri+/hHdkOVuur5rs5KdDOxy/hNZtjjV",
	"4tTXqtqTCovP/ozCGnLsMagXQKqNBVlQnkhQQSgexyRAC4qNAkHxGBEWxJwytcWTq3fbvrYtZfizvbaK",
	"x58dy3kMKdMSxnQ1e/NIo1epOhD5mNmU0ICmOtO1IiKH80AmdkF6Hrc43+L8t43zcu4ToegUhiD25hSt",
	"0/Db+CUX/f0iJgz46EQCKmZjodxg9fFg0LumYwUzXrnwP1nU2NsdBZCL7PTOs9NrHRD/hPmKahAwHxla",
	"06phHqOqIZZ1r3INom+vyi6F++V+gsmqxm4xak8ve2vwqk2yVIldjZG4CWNw8KEC0BuGfbFtqEA+FKxq",
	"QddVy2mZ95Z5/wYSNt0drTufgJPX0Wlb4fZGTn4LxO63z3OLu19aWqZ9IO6WerUqjKlQ7C94mETED7GU",
	"ZRI/CAcy831jJFECh2gScv+m62qq2d4ILzANTXEmwSPr0ifRgkoKf1TcRM/gMAT13Usik1BJp7tjWAhI",
	"5QbNOCOICxRljoH1+oOSFb7R+7qwK2u2nphgE+DjkqwgqGa3ROnxQhezTiTs6itWi55RKUFZqWvTYV10",
	"QU/qFoEFQTyiSpGggyRH0moUzHnEggeJr1klEsVqCcPEWCiKQxRSqXroF6rmPFG6koRd7JSGiohOOsWt",
	"rp+R+lFStiBMcbGEGRjXifSmRPlzcP4TBIV8NoMfWeAWBuvK7tQNC+uTCmp8aI2rSgQjQQ85p0Q0xTRM",
	"BBw6FzpTHzWp+swOSZAOBA3tcWvi2EPPSECxXoEtKYiZDxcUm/NykyHOwiW6nROG4mQSUjnPKvWZwauf",
	"mjcFeN+1JMBeNDCLDEQBiNtn6E+odzEwgDJ4dK/Cm+KHgmBmOm3Wz3YtV6epdVoB0/ZGmPlzLgzBxa4O",
	"aL2a1nUtpaAdxHVj7fidUvPJ0vCWjix1gJQ931QY843dYZv+6wtN/2UhoaVZf1qatU6sGumALcHjLPda",
	"mxffSqI0ikNqCAdVMiUVYO0dsxxXpztZzoEEwCRgH5IWAqNAI1clFE+BbdM+06VsQapjzijO1hpls6XN",
	"CuRhU7RqsaqNw/im1NIGrEsJxjpbc/DB/NA0h5hp3UPn9icoR5hIkiYLD4jCWsixkWauEGGtqtku8I1d",
	"SatHblG/zSzcVF1dg+5VemjcRGbZkBfNNIKqAX6Y6OqbwEAERFJRYBBYLpiTT7QHWQAuYopsFEiq6UG/",
	"fdxbbfNn1jbX4t12grR7grfJtmb65Er0R0ThACuj0YM1VWdiK8OvHdnwTZnYWkxt3+I/T5b/Jqw3EVIP",
	"seZ3bQp/o0lCwwDZZogyrZl3LHRViFUimNQyfrG3VDiC950yqzx0Xt0TyrBYIqxc/e8xUxSec13iB1r4",
	"IYVD1tTk4tJllOAwNJ0uEXmPfaXtAtSfu0EQlWMWkDjkSxKskx/7vNsD2IVUbHfPtpS6nfAzYf3X86AB",
	"fLjLc2XoHSTlQdr+5a31c3bbtiMbh+ePH//vAIBKWrBf/QIA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "https://raw.githubusercontent.com/unikorn-cloud/core/v1.17.1/pkg/openapi/common.spec.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef1.PathToRawSpec(path.Join(path.Dir(pathToFile), "https://raw.githubusercontent.com/unikorn-cloud/identity/v1.17.7/pkg/openapi/server.spec.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
