apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-security-group-controller
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
rules:
# Orchestrate Unikorn resources (my job).
- apiGroups:
  - region.unikorn-cloud.org
  resources:
  - identities
  - openstackidentities
  verbs:
  - list
  - watch
- apiGroups:
  - region.unikorn-cloud.org
  resources:
  - securitygroups
  verbs:
  - list
  - watch
  - update
  - patch
- apiGroups:
  - region.unikorn-cloud.org
  resources:
  - securitygroups/status
  verbs:
  - update
# TODO: delete me
# --- SNIP ----
- apiGroups:
  - region.unikorn-cloud.org
  resources:
  - openstacksecuritygroups
  verbs:
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - region.unikorn-cloud.org
  resources:
  - openstacknetworks
  verbs:
  - list
  - watch
# ---- SNIP ----
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - watch
- apiGroups:
  - region.unikorn-cloud.org
  resources:
  - regions
  verbs:
  - list
  - watch
