// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock/interfaces.go -package=mock
//
// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	v1alpha1 "github.com/unikorn-cloud/core/pkg/apis/unikorn/v1alpha1"
	v1alpha10 "github.com/unikorn-cloud/region/pkg/apis/unikorn/v1alpha1"
	types "github.com/unikorn-cloud/region/pkg/file-storage/provisioners/types"
	gomock "go.uber.org/mock/gomock"
)

// MockDriver is a mock of Driver interface.
type MockDriver struct {
	ctrl     *gomock.Controller
	recorder *MockDriverMockRecorder
}

// MockDriverMockRecorder is the mock recorder for MockDriver.
type MockDriverMockRecorder struct {
	mock *MockDriver
}

// NewMockDriver creates a new mock instance.
func NewMockDriver(ctrl *gomock.Controller) *MockDriver {
	mock := &MockDriver{ctrl: ctrl}
	mock.recorder = &MockDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriver) EXPECT() *MockDriverMockRecorder {
	return m.recorder
}

// AttachNetwork mocks base method.
func (m *MockDriver) AttachNetwork(ctx context.Context, projectID, fileStorageID string, attachment *v1alpha10.Attachment, networkPrefix *v1alpha1.IPv4Prefix) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachNetwork", ctx, projectID, fileStorageID, attachment, networkPrefix)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachNetwork indicates an expected call of AttachNetwork.
func (mr *MockDriverMockRecorder) AttachNetwork(ctx, projectID, fileStorageID, attachment, networkPrefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachNetwork", reflect.TypeOf((*MockDriver)(nil).AttachNetwork), ctx, projectID, fileStorageID, attachment, networkPrefix)
}

// Close mocks base method.
func (m *MockDriver) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockDriverMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDriver)(nil).Close))
}

// Create mocks base method.
func (m *MockDriver) Create(ctx context.Context, projectID, fileStorageID string, size int64, rootSquashEnabled bool) (*types.FileStorageDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, projectID, fileStorageID, size, rootSquashEnabled)
	ret0, _ := ret[0].(*types.FileStorageDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDriverMockRecorder) Create(ctx, projectID, fileStorageID, size, rootSquashEnabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDriver)(nil).Create), ctx, projectID, fileStorageID, size, rootSquashEnabled)
}

// Delete mocks base method.
func (m *MockDriver) Delete(ctx context.Context, projectID, fileStorageID string, force bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, projectID, fileStorageID, force)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDriverMockRecorder) Delete(ctx, projectID, fileStorageID, force any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDriver)(nil).Delete), ctx, projectID, fileStorageID, force)
}

// DetachNetwork mocks base method.
func (m *MockDriver) DetachNetwork(ctx context.Context, projectID, fileStorageID string, segmentationID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetachNetwork", ctx, projectID, fileStorageID, segmentationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DetachNetwork indicates an expected call of DetachNetwork.
func (mr *MockDriverMockRecorder) DetachNetwork(ctx, projectID, fileStorageID, segmentationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetachNetwork", reflect.TypeOf((*MockDriver)(nil).DetachNetwork), ctx, projectID, fileStorageID, segmentationID)
}

// GetDetails mocks base method.
func (m *MockDriver) GetDetails(ctx context.Context, projectID, fileStorageID string) (*types.FileStorageDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetails", ctx, projectID, fileStorageID)
	ret0, _ := ret[0].(*types.FileStorageDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetails indicates an expected call of GetDetails.
func (mr *MockDriverMockRecorder) GetDetails(ctx, projectID, fileStorageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetails", reflect.TypeOf((*MockDriver)(nil).GetDetails), ctx, projectID, fileStorageID)
}

// ListAttachments mocks base method.
func (m *MockDriver) ListAttachments(ctx context.Context, projectID, fileStorageID string) (*types.FileStorageAttachments, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAttachments", ctx, projectID, fileStorageID)
	ret0, _ := ret[0].(*types.FileStorageAttachments)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAttachments indicates an expected call of ListAttachments.
func (mr *MockDriverMockRecorder) ListAttachments(ctx, projectID, fileStorageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAttachments", reflect.TypeOf((*MockDriver)(nil).ListAttachments), ctx, projectID, fileStorageID)
}

// Resize mocks base method.
func (m *MockDriver) Resize(ctx context.Context, projectID, fileStorageID string, size int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resize", ctx, projectID, fileStorageID, size)
	ret0, _ := ret[0].(error)
	return ret0
}

// Resize indicates an expected call of Resize.
func (mr *MockDriverMockRecorder) Resize(ctx, projectID, fileStorageID, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resize", reflect.TypeOf((*MockDriver)(nil).Resize), ctx, projectID, fileStorageID, size)
}

// UpdateRootSquash mocks base method.
func (m *MockDriver) UpdateRootSquash(ctx context.Context, projectID, fileStorageID string, rootSquashEnabled bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRootSquash", ctx, projectID, fileStorageID, rootSquashEnabled)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRootSquash indicates an expected call of UpdateRootSquash.
func (mr *MockDriverMockRecorder) UpdateRootSquash(ctx, projectID, fileStorageID, rootSquashEnabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRootSquash", reflect.TypeOf((*MockDriver)(nil).UpdateRootSquash), ctx, projectID, fileStorageID, rootSquashEnabled)
}
