// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock/interfaces.go -package=mock
//
// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	types "github.com/unikorn-cloud/region/pkg/providers/types"
	gomock "go.uber.org/mock/gomock"
)

// MockProviders is a mock of Providers interface.
type MockProviders struct {
	ctrl     *gomock.Controller
	recorder *MockProvidersMockRecorder
}

// MockProvidersMockRecorder is the mock recorder for MockProviders.
type MockProvidersMockRecorder struct {
	mock *MockProviders
}

// NewMockProviders creates a new mock instance.
func NewMockProviders(ctrl *gomock.Controller) *MockProviders {
	mock := &MockProviders{ctrl: ctrl}
	mock.recorder = &MockProvidersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviders) EXPECT() *MockProvidersMockRecorder {
	return m.recorder
}

// LookupCloud mocks base method.
func (m *MockProviders) LookupCloud(ctx context.Context, regionID string) (types.Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupCloud", ctx, regionID)
	ret0, _ := ret[0].(types.Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupCloud indicates an expected call of LookupCloud.
func (mr *MockProvidersMockRecorder) LookupCloud(ctx, regionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupCloud", reflect.TypeOf((*MockProviders)(nil).LookupCloud), ctx, regionID)
}

// LookupCommon mocks base method.
func (m *MockProviders) LookupCommon(ctx context.Context, regionID string) (types.CommonProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupCommon", ctx, regionID)
	ret0, _ := ret[0].(types.CommonProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupCommon indicates an expected call of LookupCommon.
func (mr *MockProvidersMockRecorder) LookupCommon(ctx, regionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupCommon", reflect.TypeOf((*MockProviders)(nil).LookupCommon), ctx, regionID)
}
