apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-security-group-rule-controller
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
rules:
# Orchestrate Unikorn resources (my job).
- apiGroups:
  - region.unikorn-cloud.org
  resources:
  - identities
  - openstackidentities
  - securitygroups
  - openstacksecuritygroups
  verbs:
  - list
  - watch
- apiGroups:
  - region.unikorn-cloud.org
  resources:
  - securitygrouprules
  verbs:
  - list
  - watch
  - update
  - patch
- apiGroups:
  - region.unikorn-cloud.org
  resources:
  - securitygrouprules/status
  verbs:
  - update
- apiGroups:
  - region.unikorn-cloud.org
  resources:
  - openstacksecuritygrouprules
  verbs:
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - watch
- apiGroups:
  - region.unikorn-cloud.org
  resources:
  - regions
  verbs:
  - list
  - watch
