// Code generated by MockGen. DO NOT EDIT.
// Source: ../client.go
//
// Generated by this command:
//
//	mockgen -source=../client.go -destination=interfaces.go -package=mock
//
// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	v1alpha1 "github.com/unikorn-cloud/region/pkg/apis/unikorn/v1alpha1"
	types "github.com/unikorn-cloud/region/pkg/providers/types"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// CreateConsoleSession mocks base method.
func (m *MockProvider) CreateConsoleSession(ctx context.Context, identity *v1alpha1.Identity, server *v1alpha1.Server) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConsoleSession", ctx, identity, server)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateConsoleSession indicates an expected call of CreateConsoleSession.
func (mr *MockProviderMockRecorder) CreateConsoleSession(ctx, identity, server any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConsoleSession", reflect.TypeOf((*MockProvider)(nil).CreateConsoleSession), ctx, identity, server)
}

// CreateIdentity mocks base method.
func (m *MockProvider) CreateIdentity(ctx context.Context, identity *v1alpha1.Identity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIdentity", ctx, identity)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateIdentity indicates an expected call of CreateIdentity.
func (mr *MockProviderMockRecorder) CreateIdentity(ctx, identity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIdentity", reflect.TypeOf((*MockProvider)(nil).CreateIdentity), ctx, identity)
}

// CreateImage mocks base method.
func (m *MockProvider) CreateImage(ctx context.Context, image *types.Image, uri string) (*types.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateImage", ctx, image, uri)
	ret0, _ := ret[0].(*types.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateImage indicates an expected call of CreateImage.
func (mr *MockProviderMockRecorder) CreateImage(ctx, image, uri any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateImage", reflect.TypeOf((*MockProvider)(nil).CreateImage), ctx, image, uri)
}

// CreateServer mocks base method.
func (m *MockProvider) CreateServer(ctx context.Context, identity *v1alpha1.Identity, server *v1alpha1.Server) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateServer", ctx, identity, server)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateServer indicates an expected call of CreateServer.
func (mr *MockProviderMockRecorder) CreateServer(ctx, identity, server any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateServer", reflect.TypeOf((*MockProvider)(nil).CreateServer), ctx, identity, server)
}

// CreateSnapshot mocks base method.
func (m *MockProvider) CreateSnapshot(ctx context.Context, identity *v1alpha1.Identity, server *v1alpha1.Server, image *types.Image) (*types.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSnapshot", ctx, identity, server, image)
	ret0, _ := ret[0].(*types.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSnapshot indicates an expected call of CreateSnapshot.
func (mr *MockProviderMockRecorder) CreateSnapshot(ctx, identity, server, image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSnapshot", reflect.TypeOf((*MockProvider)(nil).CreateSnapshot), ctx, identity, server, image)
}

// DeleteIdentity mocks base method.
func (m *MockProvider) DeleteIdentity(ctx context.Context, identity *v1alpha1.Identity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIdentity", ctx, identity)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIdentity indicates an expected call of DeleteIdentity.
func (mr *MockProviderMockRecorder) DeleteIdentity(ctx, identity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIdentity", reflect.TypeOf((*MockProvider)(nil).DeleteIdentity), ctx, identity)
}

// DeleteImage mocks base method.
func (m *MockProvider) DeleteImage(ctx context.Context, imageID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImage", ctx, imageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteImage indicates an expected call of DeleteImage.
func (mr *MockProviderMockRecorder) DeleteImage(ctx, imageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImage", reflect.TypeOf((*MockProvider)(nil).DeleteImage), ctx, imageID)
}

// DeleteServer mocks base method.
func (m *MockProvider) DeleteServer(ctx context.Context, identity *v1alpha1.Identity, server *v1alpha1.Server) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteServer", ctx, identity, server)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteServer indicates an expected call of DeleteServer.
func (mr *MockProviderMockRecorder) DeleteServer(ctx, identity, server any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServer", reflect.TypeOf((*MockProvider)(nil).DeleteServer), ctx, identity, server)
}

// GetConsoleOutput mocks base method.
func (m *MockProvider) GetConsoleOutput(ctx context.Context, identity *v1alpha1.Identity, server *v1alpha1.Server, length *int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConsoleOutput", ctx, identity, server, length)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConsoleOutput indicates an expected call of GetConsoleOutput.
func (mr *MockProviderMockRecorder) GetConsoleOutput(ctx, identity, server, length any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConsoleOutput", reflect.TypeOf((*MockProvider)(nil).GetConsoleOutput), ctx, identity, server, length)
}

// GetImage mocks base method.
func (m *MockProvider) GetImage(ctx context.Context, organizationID, imageID string) (*types.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", ctx, organizationID, imageID)
	ret0, _ := ret[0].(*types.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImage indicates an expected call of GetImage.
func (mr *MockProviderMockRecorder) GetImage(ctx, organizationID, imageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockProvider)(nil).GetImage), ctx, organizationID, imageID)
}

// QueryImages mocks base method.
func (m *MockProvider) QueryImages() (types.ImageQuery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryImages")
	ret0, _ := ret[0].(types.ImageQuery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryImages indicates an expected call of QueryImages.
func (mr *MockProviderMockRecorder) QueryImages() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryImages", reflect.TypeOf((*MockProvider)(nil).QueryImages))
}

// RebootServer mocks base method.
func (m *MockProvider) RebootServer(ctx context.Context, identity *v1alpha1.Identity, server *v1alpha1.Server, hard bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RebootServer", ctx, identity, server, hard)
	ret0, _ := ret[0].(error)
	return ret0
}

// RebootServer indicates an expected call of RebootServer.
func (mr *MockProviderMockRecorder) RebootServer(ctx, identity, server, hard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebootServer", reflect.TypeOf((*MockProvider)(nil).RebootServer), ctx, identity, server, hard)
}

// StartServer mocks base method.
func (m *MockProvider) StartServer(ctx context.Context, identity *v1alpha1.Identity, server *v1alpha1.Server) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartServer", ctx, identity, server)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartServer indicates an expected call of StartServer.
func (mr *MockProviderMockRecorder) StartServer(ctx, identity, server any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartServer", reflect.TypeOf((*MockProvider)(nil).StartServer), ctx, identity, server)
}

// StopServer mocks base method.
func (m *MockProvider) StopServer(ctx context.Context, identity *v1alpha1.Identity, server *v1alpha1.Server) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopServer", ctx, identity, server)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopServer indicates an expected call of StopServer.
func (mr *MockProviderMockRecorder) StopServer(ctx, identity, server any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopServer", reflect.TypeOf((*MockProvider)(nil).StopServer), ctx, identity, server)
}

// UpdateServerState mocks base method.
func (m *MockProvider) UpdateServerState(ctx context.Context, identity *v1alpha1.Identity, server *v1alpha1.Server) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServerState", ctx, identity, server)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateServerState indicates an expected call of UpdateServerState.
func (mr *MockProviderMockRecorder) UpdateServerState(ctx, identity, server any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServerState", reflect.TypeOf((*MockProvider)(nil).UpdateServerState), ctx, identity, server)
}
