apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-server-controller
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
rules:
# Orchestrate Unikorn resources (my job).
- apiGroups:
  - region.unikorn-cloud.org
  resources:
  - regions
  - identities
  - openstackidentities
  - networks
  - openstacknetworks
  - openstacksecuritygroups
  verbs:
  - list
  - watch
# Manage references.
- apiGroups:
  - region.unikorn-cloud.org
  resources:
  - securitygroups
  verbs:
  - list
  - watch
  - update
- apiGroups:
  - region.unikorn-cloud.org
  resources:
  - servers
  verbs:
  - list
  - watch
  - update
  - patch
- apiGroups:
  - region.unikorn-cloud.org
  resources:
  - servers/status
  verbs:
  - update
- apiGroups:
  - region.unikorn-cloud.org
  resources:
  - openstackservers
  verbs:
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - watch
  - create
  - update
  - delete
