# Helm value overrides applied to the pinned Identity dependency during Region
# integration testing.
roles:
  platform-administrator:
    scopes:
      global:
        region:volumeclasses:v2: [read]
  administrator:
    scopes:
      organization:
        region:volumeclasses:v2: [read]
