apiVersion: apps/v1
kind: Deployment
metadata:
  name: unikorn-region
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unikorn-region
  template:
    metadata:
      labels:
        app: unikorn-region
    spec:
      containers:
      - name: unikorn-region
        image: {{ include "unikorn.regionImage" . }}
        args:
        - --namespace={{ .Release.Namespace }}
        {{- include "unikorn.cors.flags" . | nindent 8 }}
        {{- include "unikorn.otlp.flags" . | nindent 8 }}
        {{- include "unikorn.identity.flags" . | nindent 8 }}
        ports:
        - name: http
          containerPort: 6080
        - name: prometheus
          containerPort: 8080
        - name: pprof
          containerPort: 6060
        # Note, this is quite CPU intensive, especially when going wide!
        # TODO: profile me.
        resources:
          requests:
            cpu: "1"
            memory: 50Mi
          limits:
            cpu: "2"
            memory: 100Mi
        securityContext:
          readOnlyRootFilesystem: true
      serviceAccountName: unikorn-region
      securityContext:
        runAsNonRoot: true
