apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unikorn-region
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
  annotations:
    {{- include "unikorn.ingress.clusterIssuer.annotations" . | nindent 4 }}
    # mTLS is used to authenticate other Unikorn services
    nginx.ingress.kubernetes.io/auth-tls-verify-client: optional
    nginx.ingress.kubernetes.io/auth-tls-secret: cert-manager/unikorn-client-ca
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
    {{- if (include "unikorn.ingress.externalDNS" .) }}
    external-dns.alpha.kubernetes.io/hostname: {{ include "unikorn.region.host" . }}
    {{- end }}
spec:
  {{- if .Values.ingress.class }}
  ingressClassName: {{ .Values.ingress.class }}
  {{- end }}
  # For development you will want to add these names to /etc/hosts for the ingress
  # endpoint address.
  tls:
  - hosts:
    - {{ include "unikorn.region.host" . }}
    secretName: unikorn-region-ingress-tls
  rules:
  # The the UI is written as a JAMstack application, so the API is accessed via
  # the same host to avoid CORS, and therefore uses routing to hit the correct
  # service.
  - host: {{ include "unikorn.region.host" . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: unikorn-region
            port:
              name: http
