apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unikorn-region
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
  annotations:
  {{- with $clusterIssuer := ( include "unikorn.ingress.clusterIssuer" . ) }}
    cert-manager.io/cluster-issuer: {{ $clusterIssuer }}
  {{- end }}
  {{- if .Values.ingress.externalDns }}
    external-dns.alpha.kubernetes.io/hostname: {{ include "unikorn.region.host" . }}
  {{- end }}
spec:
  {{- if .Values.ingress.class }}
  ingressClassName: {{ .Values.ingress.class }}
  {{- end }}
  # For development you will want to add these names to /etc/hosts for the ingress
  # endpoint address.
  tls:
  - hosts:
    - {{ include "unikorn.region.host" . }}
    secretName: unikorn-region-ingress-tls
  rules:
  # The the UI is written as a JAMstack application, so the API is accessed via
  # the same host to avoid CORS, and therefore uses routing to hit the correct
  # service.
  - host: {{ include "unikorn.region.host" . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: unikorn-region
            port:
              name: http
