apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unikorn-physical-network-controller
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
rules:
# Orchestrate Unikorn resources (my job).
- apiGroups:
  - region.unikorn-cloud.org
  resources:
  - identities
  - openstackidentities
  verbs:
  - list
  - watch
- apiGroups:
  - region.unikorn-cloud.org
  resources:
  - physicalnetworks
  verbs:
  - list
  - watch
  - update
  - patch
- apiGroups:
  - region.unikorn-cloud.org
  resources:
  - physicalnetworks/status
  verbs:
  - update
- apiGroups:
  - region.unikorn-cloud.org
  resources:
  - openstackphysicalnetworks
  verbs:
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - region.unikorn-cloud.org
  resources:
  - vlanallocations
  verbs:
  - list
  - watch
  - create
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - watch
- apiGroups:
  - region.unikorn-cloud.org
  resources:
  - regions
  verbs:
  - list
  - watch
