apiVersion: apps/v1
kind: Deployment
metadata:
  name: unikorn-physical-network-controller
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unikorn-physical-network-controller
  template:
    metadata:
      labels:
        app: unikorn-physical-network-controller
    spec:
      containers:
      - name: unikorn-physical-network-controller
        image: {{ include "unikorn.physicalNetworkControllerImage" . }}
        args:
        {{- include "unikorn.otlp.flags" . | nindent 8 }}
        ports:
        - name: http
          containerPort: 6080
        - name: prometheus
          containerPort: 8080
        - name: pprof
          containerPort: 6060
        resources:
          requests:
            cpu: "50m"
            memory: 50Mi
          limits:
            cpu: "100m"
            memory: 100Mi
        securityContext:
          readOnlyRootFilesystem: true
      serviceAccountName: unikorn-physical-network-controller
      securityContext:
        runAsNonRoot: true
